{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.10.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.10.jar",
          "size": 2089651,
          "sha512": "6fc52c79b59d8e046035a07eb2e1b66ca6a3c34b3174695a8b06757ddf2826a41f4f3e2f9d573788d9b303ce528b3d6447ac8d919d6bc717fe261e7f54cee57c",
          "sha256": "35e38a756415e7d580ddde74bffd557b21963aa23f67f7eddf41b577a92ba6ad",
          "sha1": "09d2296ae5c54ae9fe8163c85fd5829cf2756d99",
          "md5": "7ee6e35dfe01dea88f2595d152c876ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.10.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.10.jar",
          "size": 2089651,
          "sha512": "6fc52c79b59d8e046035a07eb2e1b66ca6a3c34b3174695a8b06757ddf2826a41f4f3e2f9d573788d9b303ce528b3d6447ac8d919d6bc717fe261e7f54cee57c",
          "sha256": "35e38a756415e7d580ddde74bffd557b21963aa23f67f7eddf41b577a92ba6ad",
          "sha1": "09d2296ae5c54ae9fe8163c85fd5829cf2756d99",
          "md5": "7ee6e35dfe01dea88f2595d152c876ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.10-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.10-sources.jar",
          "size": 608242,
          "sha512": "e7ff525b8f59560f84e6e9431b9c2eeb9dc2b92306c0c8283fbb1559898f301de880ac0f44d972eaae8e541f9d37dd8cd1a2a9c369a456a9681ac8ac8723094a",
          "sha256": "323b8de3bcb529c207dfa98089819c6503dbb45488cb9cded79176adc01366d0",
          "sha1": "8238f88700d680a667ad5609ba57bd5b2ae3a89d",
          "md5": "be82901b6621fd38b828dbb9b861bfa4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.10-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.10-javadoc.jar",
          "size": 262291,
          "sha512": "b5eb8d2b1b6c69febc258aebe0be1b498fcf73ca47f74e92ad0fae2134101ec9a5cee4c62877c65bad3922f325c67ce1409eaf9cd592b21c08fbb227d43cb9ea",
          "sha256": "75add4c345d906be340fede0b964f6a3fad242116111e2e6382a4c1e29cc6428",
          "sha1": "514769feedf6a4360246e254a68c2b2fe16856b2",
          "md5": "dc5c14d29ba859f4d3686766de4cbad4"
        }
      ]
    }
  ]
}
