{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.21.1-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19.jar",
          "size": 1670591,
          "sha512": "d3261c51cdd4e8d129c9272ecc6a413461e278aa13c9033fa98e1e85652a59e7de374b6ebdc6c3a4224b03b122daa817fe68c0037bfc8105d18a858f56c839d9",
          "sha256": "d09c01112bdc05b0c0c35cab56868a621264b1099c0b019f68a4b4b949414c78",
          "sha1": "2da5a3be8e87ffeb4673e8266e53b5a9d5ed1e84",
          "md5": "fb3b8e09698acbd6a7b5dd5caa66344c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.6"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19.jar",
          "size": 1670591,
          "sha512": "d3261c51cdd4e8d129c9272ecc6a413461e278aa13c9033fa98e1e85652a59e7de374b6ebdc6c3a4224b03b122daa817fe68c0037bfc8105d18a858f56c839d9",
          "sha256": "d09c01112bdc05b0c0c35cab56868a621264b1099c0b019f68a4b4b949414c78",
          "sha1": "2da5a3be8e87ffeb4673e8266e53b5a9d5ed1e84",
          "md5": "fb3b8e09698acbd6a7b5dd5caa66344c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19-sources.jar",
          "size": 80461,
          "sha512": "65329f714869f9dff2e1ab0020e94e8d2e7b0197fb968b137a2e2f48ceed9f39f03832e244c6add99c722b80a3f132b5d71639816dc4fc9a417e01e4f2fceaa8",
          "sha256": "230484057fdd12afb0f0b5cbaf74ce2bd7cbb09e95b71869e57b987e8be88b23",
          "sha1": "d47f25ce291a2b00aa58b3ea5de24ac2907bcfbf",
          "md5": "7773fc6c6b4b7c87de71a2dd3e6ac44e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19-javadoc.jar",
          "size": 86644,
          "sha512": "a4c5390f30be93dcc3eb71cad656a6f1d9662f0ac731520235849843c5d9c101a87784e131bfc9af25b9beef8abfc9957083c8b67d88aeb8a370d186954cac58",
          "sha256": "4d053736c20061f93c014d88955813b1d06612fd5b56e61740ecbb80f253fe72",
          "sha1": "a76fbd5f8df0a171d83fd40319f1817dd53ffc16",
          "md5": "c01b54a65f6dc43fcca1157548d22203"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19-dev-shadow.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19-dev-shadow.jar",
          "size": 534559,
          "sha512": "cdd48bfcd19106dc36adf2720c7ab346db61077a1d321562e155fd31b21c9ff08d3f3cd104bfe1837af9649c69b729d03c954a9ed300a8bacf9d13c85d0e1819",
          "sha256": "f2c1b78e14d44f9e7b7d0ef8e55efe72e909e255154637b7de7805521a0ce692",
          "sha1": "ed239ab9d6618ae0acfc464b89a52e44fd834720",
          "md5": "b53d1d313ded424b76ede3306b9d6fe3"
        }
      ]
    }
  ]
}
