{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.21.1-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19.jar",
          "size": 1668285,
          "sha512": "95348314c59f7e0d57daf0d9b57cf0a75e35202a1eed59f3df6f57f113784bbba0a85b2c24436ae65010f1918d0874a8ac61ac0a10f920b5bc82ae14a447733f",
          "sha256": "452c99e47c9400b0bff411e9c8f994ff264ccfc640b97a49dc51ba5937ca8a67",
          "sha1": "4b1e31067f07f58c56802cbd36a7cfa0090c5e61",
          "md5": "e0bd34d0a27e7583a0be2ac771eaaa8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.6"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19.jar",
          "size": 1668285,
          "sha512": "95348314c59f7e0d57daf0d9b57cf0a75e35202a1eed59f3df6f57f113784bbba0a85b2c24436ae65010f1918d0874a8ac61ac0a10f920b5bc82ae14a447733f",
          "sha256": "452c99e47c9400b0bff411e9c8f994ff264ccfc640b97a49dc51ba5937ca8a67",
          "sha1": "4b1e31067f07f58c56802cbd36a7cfa0090c5e61",
          "md5": "e0bd34d0a27e7583a0be2ac771eaaa8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19-sources.jar",
          "size": 80461,
          "sha512": "a5003a0df0e3933c86300467b5f7efb39f7c81931aa1c36d610aedc13b01be031751636778aaa8302bc9556c574cbba67575b5225219add8e781edb96ec3df0e",
          "sha256": "ee2814bfc4507923dde3d4b8376df9edb717b4df9a41a62b56de3687513dab41",
          "sha1": "346b0d7405201ff9452c2c54763178e0e3b2591d",
          "md5": "765a8a522b36afbf4e216546fff3ff14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19-javadoc.jar",
          "size": 86644,
          "sha512": "a4c5390f30be93dcc3eb71cad656a6f1d9662f0ac731520235849843c5d9c101a87784e131bfc9af25b9beef8abfc9957083c8b67d88aeb8a370d186954cac58",
          "sha256": "4d053736c20061f93c014d88955813b1d06612fd5b56e61740ecbb80f253fe72",
          "sha1": "a76fbd5f8df0a171d83fd40319f1817dd53ffc16",
          "md5": "c01b54a65f6dc43fcca1157548d22203"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.21.1-2.2.19-dev-shadow.jar",
          "url": "dragonlib-fabric-1.21.1-2.2.19-dev-shadow.jar",
          "size": 532392,
          "sha512": "eda21b54f1335162b2fe08d030ca047642d7afdbd7d034e7c5f87e83899fef2a7643f960324be712120d300ba688b228057188a11f771823da489e898ec8d1f7",
          "sha256": "3544445627d4e4b3da1943394914d4e4870792ce3f9b610d4b6600b23090c8b9",
          "sha1": "a1ff5e822586bc1445b71481bdcbb930f9042259",
          "md5": "4f076336f9d0f20c9dd0593553b7fa88"
        }
      ]
    }
  ]
}
