{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-neoforge",
    "version": "1.20.4-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19.jar",
          "size": 1367112,
          "sha512": "b18bac15487d9c11dfca5190f9418ef48edbb38fae627cf227e709092a6ca395e7c8c7409eae50be7b8253be6038a595aabc68e8f19b54a550baf52ab07b9ce4",
          "sha256": "80a62cbb0554aab5747a1fd9a5eb5bbc321b5cddc18b83855c0d446cf4837428",
          "sha1": "345d0f618a2641f8b3ef4a50476b1623c17f7da9",
          "md5": "67752e0c36d410df3d63fe7a57a13d01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "11.1.17"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-neoforge",
          "version": {
            "requires": "20.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19.jar",
          "size": 1367112,
          "sha512": "b18bac15487d9c11dfca5190f9418ef48edbb38fae627cf227e709092a6ca395e7c8c7409eae50be7b8253be6038a595aabc68e8f19b54a550baf52ab07b9ce4",
          "sha256": "80a62cbb0554aab5747a1fd9a5eb5bbc321b5cddc18b83855c0d446cf4837428",
          "sha1": "345d0f618a2641f8b3ef4a50476b1623c17f7da9",
          "md5": "67752e0c36d410df3d63fe7a57a13d01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19-sources.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19-sources.jar",
          "size": 297721,
          "sha512": "b3b49a03f035683d08fefe6be563990d09c7dbe56315993529002d96d70c21a35fc1c3c6d327eae5538e1f9d3c6199505999ccf9453f1a2e6dbad7abecdfe3fc",
          "sha256": "74e03e4c71a95dad2a07569149f1f0c0cd8219cbb693888a8b8b8f397a7939f9",
          "sha1": "6a800c1282578f77e4317ac8ef5e06bf478efae9",
          "md5": "a742fb446f19131b4b482ed30d63e60b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19-javadoc.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19-javadoc.jar",
          "size": 74871,
          "sha512": "ef239280bca21a22154b4c0adb2d5f50f7ef8d08276a884464ad86bdef15f9a4ab0ff1fc4265cc6a3d03fee58e4af49efe7869d4c993af57cf7e421dc46f257c",
          "sha256": "ac9b377aafc3e59c59332d5adb9f6d4981c25359bbe709a1dbf605b9b454c46c",
          "sha1": "65078a123195b71ccba1cd4ffbb78fec369b9358",
          "md5": "c9669fef43815d85788466e03b660a48"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19-dev-shadow.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19-dev-shadow.jar",
          "size": 755457,
          "sha512": "8c639fb576f60d47cb9cdeab70cb57584eac9cb05f998ceda4f437aa04e372a0de82f06d6be66741a99a243029f4a71fcd0173ab19c0c84545715dbbaa402ff5",
          "sha256": "faab5c58e98c60672865a1688622587ae10ac353714a9dfb402d8bb20864b7ac",
          "sha1": "03d9f9f211d81069ef5b511a8370d716715060dd",
          "md5": "ad1fea52a9377bec2154880f46aeedbd"
        }
      ]
    }
  ]
}
