{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-neoforge",
    "version": "1.20.4-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19.jar",
          "size": 1365497,
          "sha512": "81e5eb8a0ecec2e9991f44dfd4d19974416d40e983b1aee2aa8669f8c3fe67b5483cff30fffede5591b36695a2b4aef1706683d81b7144245972ce0e81aca0f5",
          "sha256": "09b1ccd4161ddbc0dbf9b51294b725e2b7173cac14f9afce095ea27453d7a4a3",
          "sha1": "7d9d46ef4edbb43eaf566278506644cb06120d1e",
          "md5": "7fbe467aa877a40ec5d5ff58814f024a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "11.1.17"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-neoforge",
          "version": {
            "requires": "20.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19.jar",
          "size": 1365497,
          "sha512": "81e5eb8a0ecec2e9991f44dfd4d19974416d40e983b1aee2aa8669f8c3fe67b5483cff30fffede5591b36695a2b4aef1706683d81b7144245972ce0e81aca0f5",
          "sha256": "09b1ccd4161ddbc0dbf9b51294b725e2b7173cac14f9afce095ea27453d7a4a3",
          "sha1": "7d9d46ef4edbb43eaf566278506644cb06120d1e",
          "md5": "7fbe467aa877a40ec5d5ff58814f024a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19-sources.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19-sources.jar",
          "size": 297721,
          "sha512": "1f743c16581adb7dc0dc3fd5960243ec60d943076bed8c9215a5d234ea613e98f2b383e44c90dfee4121a5411aec8dc7f41dd6222a691013f26aa66a067d4aad",
          "sha256": "c9480c81a138686e563411a5f11da39546de8d7023146765b63e28513811d3f7",
          "sha1": "d0fb6569d11d0fff1ce4b91d5715d341e801f30d",
          "md5": "679ddf7432ddbdaf3aa6413ddf539016"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19-javadoc.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19-javadoc.jar",
          "size": 86186,
          "sha512": "d81287cdf070a2cc2ad323854d1c9a35b9a01b3ba57305b24af2930ec17f7a02231c155ca62355087d5a027937a0cb47bdb1f7646fc80426e091e12e5ca077de",
          "sha256": "a4cdd939e9040fe4178d7cad948fdb5c80a126b6e1755bb3cfb8245302efb333",
          "sha1": "72930de64dd7eba81a5c5274255d3ba407db5d22",
          "md5": "673f685de5d6262d8d9f04c232ecb546"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.20.4-2.2.19-dev-shadow.jar",
          "url": "dragonlib-neoforge-1.20.4-2.2.19-dev-shadow.jar",
          "size": 754411,
          "sha512": "a84f53b92d72f4018de37ca826b42cf4de4661ae26ecaff308f56538a4b97a8fa35f4951f53d3eefe238e5ef52aba43216170520a46590ada01bfd03f50206b2",
          "sha256": "f56581525d64bd4ec8da1efc0e67f4bbff3460594b49cb4d64d390bdca3ca7de",
          "sha1": "d0068ef1ee809f4a3f3cea62a08b69c031be8bc0",
          "md5": "3cde51c17c596d4b31f3ba7c4ffed922"
        }
      ]
    }
  ]
}
