{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-forge",
    "version": "1.19.2-0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.19.2-0.1.7.jar",
          "url": "dragnsounds-forge-1.19.2-0.1.7.jar",
          "size": 1617970,
          "sha512": "d15a8d708ce5eec01fc8ead8747a3a7c9a89b114ecf75fec66522792201fd6de0c365c96f98ef49e57782469f423ade498ae27c2ef64dcee1b709e5fcdd29619",
          "sha256": "cc6c63102d79eab718508ff7a2c2a4782907d7702948ee35408317acf093ff6f",
          "sha1": "87b998f3cdc2e429967082bc0679d71baa234ea0",
          "md5": "688238479a7098f3822e69009b44f488"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.19.2-2.1.11"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-forge-1.19.2-0.1.7.jar",
          "url": "dragnsounds-forge-1.19.2-0.1.7.jar",
          "size": 1617970,
          "sha512": "d15a8d708ce5eec01fc8ead8747a3a7c9a89b114ecf75fec66522792201fd6de0c365c96f98ef49e57782469f423ade498ae27c2ef64dcee1b709e5fcdd29619",
          "sha256": "cc6c63102d79eab718508ff7a2c2a4782907d7702948ee35408317acf093ff6f",
          "sha1": "87b998f3cdc2e429967082bc0679d71baa234ea0",
          "md5": "688238479a7098f3822e69009b44f488"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.19.2-0.1.7-sources.jar",
          "url": "dragnsounds-forge-1.19.2-0.1.7-sources.jar",
          "size": 331926,
          "sha512": "775c44cb3fa70b79582453b0099434504ddb90026165b03e77195a510c6f18555216e3afafefa8b1ead0fb6f0b9c8e4e93b92a583a1afb92e8f57d8f662e119c",
          "sha256": "7a9413d558defa8e2240e41179d71e6c230a4d81c75472eb4d65f6a8434e5af6",
          "sha1": "d7db82ba42db9abe9d50859238297c6bb237e54a",
          "md5": "35d29990c5fd6a1ff934158fafb8eecf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.19.2-0.1.7-javadoc.jar",
          "url": "dragnsounds-forge-1.19.2-0.1.7-javadoc.jar",
          "size": 74691,
          "sha512": "08b4682ff3394e8e4b5589adbf2475d0d30fdb01c320e8fb8cd5e0a492e76cd3ee616a04217edd636bd6a7f2ccc1b916271d48d80a38ac66c6187d5a2cfd24d9",
          "sha256": "634f3dd11e96d3c017137a67f7c363c22071ab5359090201496aa8bd08e24991",
          "sha1": "7755e5915a4edf77376033b5a9230cd1e4944a90",
          "md5": "e0616773655e1dbebbeb93d02f3af5b9"
        }
      ]
    }
  ]
}
