{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.4-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19.jar",
          "size": 1292720,
          "sha512": "93820e48b0c92425572220c2dfd45292c5f9338e13991fe7f4c0395ddf9aa9713cb81975bdb58bb70437a1b7bd24f80effbe3682ad9963dc305174614a3893ad",
          "sha256": "5a5f0466a4fcba4b63deacced9fd2d6939a73c384b250f7d1663b3ee1d3cd2ff",
          "sha1": "9e755e474459d054d9f6bff773884ea58e9513b2",
          "md5": "a3820d227f90d77cd7aa9bdaa9c4b025"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "11.1.17"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19.jar",
          "size": 1292720,
          "sha512": "93820e48b0c92425572220c2dfd45292c5f9338e13991fe7f4c0395ddf9aa9713cb81975bdb58bb70437a1b7bd24f80effbe3682ad9963dc305174614a3893ad",
          "sha256": "5a5f0466a4fcba4b63deacced9fd2d6939a73c384b250f7d1663b3ee1d3cd2ff",
          "sha1": "9e755e474459d054d9f6bff773884ea58e9513b2",
          "md5": "a3820d227f90d77cd7aa9bdaa9c4b025"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19-sources.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19-sources.jar",
          "size": 298016,
          "sha512": "d86ef05d0d4a4d60bfc67104d1f0c7d022843923c7ab59b59894c91ad7f8b5b557c366e3b976eb39ba646e2c4f7b16c89182a545f57b18878f4bcefc673eb289",
          "sha256": "4c2770a0076f5a31909b4f29c5abe2253182de22c43a949b409d812d641e48e1",
          "sha1": "303cea07357c4d91c7e5e2c81828a2a38b00b0d3",
          "md5": "1cd84ebcc6b8511d829e723f0bfa838a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19-javadoc.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19-javadoc.jar",
          "size": 86098,
          "sha512": "11425cbf10ef92eda1e51b3c2ca596f09081fb2d20766ed83558cb9c4e09834d3949b90d3e1b67b625e04fb40b53f2e3af825befa3564c4737e2a6ce5bdf5df5",
          "sha256": "8e3b423022332f9884c7f58cc8ad6446438ebe5c1df469751c84efeab6c62033",
          "sha1": "13392560aaea895f1fe0c0c8b0b4c5febb372705",
          "md5": "abe069fa8218f3c2f653a2191df38a69"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19-dev-shadow.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19-dev-shadow.jar",
          "size": 754186,
          "sha512": "da2632f140b415be73700314c98ddc8df6d7ef310191eacdc5138cfe7edd6b51a256f5066ae3cde3e75258abc75475846fc2f0161a0d860f27863b27c78e44ab",
          "sha256": "8a243e6e6df93b42ba50abb5c705462f60de3269303b6413d7dd2cc7e92406a3",
          "sha1": "ae6f6bb0b6f9c85b9b0700dd4d8ef60ae83457dd",
          "md5": "05d1a7166e38620e905e71d1f7ba8341"
        }
      ]
    }
  ]
}
