{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.4-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19.jar",
          "size": 1294507,
          "sha512": "3c04e6a038885a68dd0d5e04816d841edfb12dd8c151f01257cdbd8a9cb976da74bc9effbac8411e6c396ebd97d98c593393b34c856248d0dc774a839275863b",
          "sha256": "0d6f77c4c6f07e6b06a271868b9a101fa08f1ce0987372b31e9f857b3959bbb2",
          "sha1": "a030379aeb2397e25217e67970c2dd358f7ad290",
          "md5": "268021c6999ff0d5cbca9ecdc9f95456"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "11.1.17"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19.jar",
          "size": 1294507,
          "sha512": "3c04e6a038885a68dd0d5e04816d841edfb12dd8c151f01257cdbd8a9cb976da74bc9effbac8411e6c396ebd97d98c593393b34c856248d0dc774a839275863b",
          "sha256": "0d6f77c4c6f07e6b06a271868b9a101fa08f1ce0987372b31e9f857b3959bbb2",
          "sha1": "a030379aeb2397e25217e67970c2dd358f7ad290",
          "md5": "268021c6999ff0d5cbca9ecdc9f95456"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19-sources.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19-sources.jar",
          "size": 298016,
          "sha512": "e042e7262c1e9f361d799db7936324492e70c8c29f2578780f4c00294fe22d37de11b46e632d294bec71e216e729304ad59bbf4e307e713e764d1d177cce3b80",
          "sha256": "bdcfa6b338436f50a77f51f37db008df0373f8325110f760f2ab89b4384d94a3",
          "sha1": "9405ce7f9f9d36e55830a31c8782275c7bf07bf3",
          "md5": "dfa1db179af29394cb9f4551635a2b59"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19-javadoc.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19-javadoc.jar",
          "size": 74786,
          "sha512": "182e37f19cfa004b6c6bb2424db579ae6260f67656913a038588bfcbe04528ec69015c43d33e492273c9f8315b26267ae94cdf12715d977e54d3da2b3200796a",
          "sha256": "46d9c51eaf98ab52357a53ebba2026656554ec3893383e5402e3ce8c97ad24c7",
          "sha1": "682b30a517c75e6404bcf491a18163ef9c6d8d26",
          "md5": "d2057fbe516bb7ee52216f319f91489f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.4-2.2.19-dev-shadow.jar",
          "url": "dragonlib-forge-1.20.4-2.2.19-dev-shadow.jar",
          "size": 755379,
          "sha512": "fbc2fb548fb04324bc2c815a9f5ba7030dd2428c199e654be883d886ce364bef1a2ed0ea690d72426407e528e49f6dadeae2e7a42603ff8599f415ca81cfb84d",
          "sha256": "5f247bd17b55005b86acbbbcd83a2acd82186f4b2e643802669c328b9d6abb8e",
          "sha1": "267b5914dbdbc774f573970a2f35909d254dca3b",
          "md5": "3bf14617b840417ba621f97e150f17c2"
        }
      ]
    }
  ]
}
