{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.18.2-0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.8.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.8.jar",
          "size": 1612242,
          "sha512": "c6a95df9ef0e3b3e02b2544285ae7a43522c2bb47c3880e254dffe97a38bb75508f693795521fc8682b3812baa70f1062b1320eb4a942b674951283cb7a4012f",
          "sha256": "7731bfbf2770a4c474e20c99f3e3baeb602f83b188ccacc318396f7b1e50361f",
          "sha1": "b5a98dc081a6e5b3aae7b99552f51d07e6db6a28",
          "md5": "5559d48c10ca013bc32906f9edd0b030"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.18.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.18.2-2.1.12"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.8.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.8.jar",
          "size": 1612242,
          "sha512": "c6a95df9ef0e3b3e02b2544285ae7a43522c2bb47c3880e254dffe97a38bb75508f693795521fc8682b3812baa70f1062b1320eb4a942b674951283cb7a4012f",
          "sha256": "7731bfbf2770a4c474e20c99f3e3baeb602f83b188ccacc318396f7b1e50361f",
          "sha1": "b5a98dc081a6e5b3aae7b99552f51d07e6db6a28",
          "md5": "5559d48c10ca013bc32906f9edd0b030"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.8-sources.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.8-sources.jar",
          "size": 75384,
          "sha512": "594962e85d55539b896c2a83aafd03d7f5e07f5077b8390549d0b2627a43a43a7de5323804768fcaff79edc0648a1be263d6b53e5ae834d63c2406bc244e222a",
          "sha256": "afd6182d1560017336a6285e71575071c02ec4c173905141553eeec54f780c60",
          "sha1": "0deaa5f3335b902a3cb7fbea00d2cbcd46cc866c",
          "md5": "5d56d54c6d39b6d5fc77de662d594627"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.8-javadoc.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.8-javadoc.jar",
          "size": 75314,
          "sha512": "b5e8f84f1a4709e7abe2f92589a9e2db451f2b07d5412a7e4e777262638d22821cdfd4d1f553f573459996fe7a9b793533b66db016aa48d79b5d797812799ffd",
          "sha256": "83875efb422e0ca5d10feff9499cc4adef7137e4c5b3e3bc6af17b58a1fab9ff",
          "sha1": "e6f1517ac79d4ccd6f1fa6620fd6f96ec06c26a0",
          "md5": "afff9b8956a7d52732c4cfe8812fbdc4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.8-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.8-dev-shadow.jar",
          "size": 331987,
          "sha512": "39d2fe612b7ebb62a689abea46f1d1ce2cc325740bb27efee156a5e054eb3c5e0f53fd1dbc386667c51a6cd44fed03063b634bfd98987d6c304a9a281a537169",
          "sha256": "b8cfcc0a4732b92fc7afd29589f2d44fe786a8fd462462342ebf05b6bca6f07c",
          "sha1": "931b5407dfee1107b318d87d281fc3ef746c8da5",
          "md5": "06cdf78b2cb4a6b5aeebb3fa0195567b"
        }
      ]
    }
  ]
}
