{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.18.2-0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.1.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.1.jar",
          "size": 2476292,
          "sha512": "b392ed9ad3bc1c5497951182f89952118ca681f533eba0c7d1ca91b2d283a6ac9f392ec8c1b46c3c3456da3f31d6619ce3a5fe05ad05fbee1239fbbbfa3e53a7",
          "sha256": "ce17f67b75cd4aac930903ddb9927d72a1df1defca1799aacb1d3c9e82da2821",
          "sha1": "67654a8e3945d0d03a2c5fb95ce6c97243dd9097",
          "md5": "d29606f43da4f438b7d8a3f25e0ec4ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.18.2"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.18.2-2.1.8"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.1.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.1.jar",
          "size": 2476292,
          "sha512": "b392ed9ad3bc1c5497951182f89952118ca681f533eba0c7d1ca91b2d283a6ac9f392ec8c1b46c3c3456da3f31d6619ce3a5fe05ad05fbee1239fbbbfa3e53a7",
          "sha256": "ce17f67b75cd4aac930903ddb9927d72a1df1defca1799aacb1d3c9e82da2821",
          "sha1": "67654a8e3945d0d03a2c5fb95ce6c97243dd9097",
          "md5": "d29606f43da4f438b7d8a3f25e0ec4ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.1-sources.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.1-sources.jar",
          "size": 75384,
          "sha512": "84f5a6b652798ec18aac32cf75caa5ea0cc88941a7394b9734088aafdc834c4333149429c8fc0349f9eaaf363f12a9af8538ea63694974c2fe3277235e6dd265",
          "sha256": "ea2e72df8c4f15e4ce0e71c199b814b6453faf92ba45966531abf65b15a0ce1d",
          "sha1": "6083a560ecdf4f6e0320fb0243c444f003a35ba7",
          "md5": "9e9727e5c4c96e2b043505d8a794c741"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.1-javadoc.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.1-javadoc.jar",
          "size": 75311,
          "sha512": "a507973bce17359d5f45a66a88c1cae4aab947187dcd33bbd2bac884da4ee9561ff1b0d2b5a05688db500113fe2be04ddd5973717dfcd47e18551e249be96f7a",
          "sha256": "6c4faaf812846e2845ac9abe6c4ef26c0e2326ab5a746e7e6b05f4220432d549",
          "sha1": "02c2af9eadc2fb0e69eab1b8badcef7fdabc460b",
          "md5": "01b749a2f8479fe658768eac42af2274"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.1-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.1-dev-shadow.jar",
          "size": 333383,
          "sha512": "617ff8fd2ff52e505c4289f76ee2383f5d0bf471823eadbacd12ad2df6ef7cd79655f54b55bdccc8811fd3eed6fec20ce8b3edb2f418866b4c36875c3dc97987",
          "sha256": "3af58154d6535285b26228cc99c9f69d9595f40238bd97dd75cd6edc9f75b9cd",
          "sha1": "c63e791ad419537ea87a6ce6271983682d0ca530",
          "md5": "646f7a1d265c0df2cbe2023805c893d1"
        }
      ]
    }
  ]
}
