{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-forge",
    "version": "1.20.1-0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.20.1-0.1.8.jar",
          "url": "dragnsounds-forge-1.20.1-0.1.8.jar",
          "size": 1642534,
          "sha512": "d55b48ed6af3a9a278bc96e28a2a807775cdb4546bfd7a7d0e86b5b300df1702491b093fa4d17ad632ea6fc4bb41f22e34593b794a446fb81a3f212cfce4212a",
          "sha256": "8df2bd9db867b493d394fbae485c0f4f82d0aa33f973c7b3737259682a9a35b6",
          "sha1": "751faf75f16e5cd52f414a69001fb384d48d2392",
          "md5": "7929fac378d65f0f2c4ddad0bc73d0b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.20.1-2.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-forge-1.20.1-0.1.8.jar",
          "url": "dragnsounds-forge-1.20.1-0.1.8.jar",
          "size": 1642534,
          "sha512": "d55b48ed6af3a9a278bc96e28a2a807775cdb4546bfd7a7d0e86b5b300df1702491b093fa4d17ad632ea6fc4bb41f22e34593b794a446fb81a3f212cfce4212a",
          "sha256": "8df2bd9db867b493d394fbae485c0f4f82d0aa33f973c7b3737259682a9a35b6",
          "sha1": "751faf75f16e5cd52f414a69001fb384d48d2392",
          "md5": "7929fac378d65f0f2c4ddad0bc73d0b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.20.1-0.1.8-sources.jar",
          "url": "dragnsounds-forge-1.20.1-0.1.8-sources.jar",
          "size": 332254,
          "sha512": "8874b85444a53a148c692a4840a4a9a541936d0c6952f4d3bdbee4dfe4517deea6c0d8efb60c03b95c53581bddf88b8dac51328b3ef0f175b45a19437502322f",
          "sha256": "f9dcf0b2b5ebbd012a10bf4c337b214da3255eeb249f6fb5e7f5136ced2d9c76",
          "sha1": "630cfffeeba9baa543e80cf5675e3c98e30d0131",
          "md5": "d5f31a240ec657840b2e34e7495a6295"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.20.1-0.1.8-javadoc.jar",
          "url": "dragnsounds-forge-1.20.1-0.1.8-javadoc.jar",
          "size": 74692,
          "sha512": "85f584fa61c9434ba737acdcaec6a9b4f42c97a68638f3e53ec626aac6d4448f8bf3a4df3703183a0f5a902621d54268dca005ef253e31aedc29ca439c734fbd",
          "sha256": "e0b43de51415cb085ced7fce97d7c58a6f154ed3502d02a4019d1075a58221e0",
          "sha1": "e50717c283683bfb766d1bc337ea9024652e1122",
          "md5": "3cb3f1a9a7afdc6f5d70fc7d623f3255"
        }
      ]
    }
  ]
}
