{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.19.2-2.2.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.18.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.18.jar",
          "size": 1441187,
          "sha512": "7d05f36b4aeb4ebc01225b5ccb5c40e19be35b47d43cd9adcb757cb6fef2c9fbff9f0f43aaebd2f396ce9bd44767ca5964fb21403e94d9f289effe90f9153355",
          "sha256": "612ebfb8c46dfa515b45153e13fc24add0e8a5a2f0a97ce59ae06242f8982075",
          "sha1": "45550bd0243523e76fa220546577c2164beea21a",
          "md5": "5289e26a9d6385a9bc56d735232a8977"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.5.85"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.18.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.18.jar",
          "size": 1441187,
          "sha512": "7d05f36b4aeb4ebc01225b5ccb5c40e19be35b47d43cd9adcb757cb6fef2c9fbff9f0f43aaebd2f396ce9bd44767ca5964fb21403e94d9f289effe90f9153355",
          "sha256": "612ebfb8c46dfa515b45153e13fc24add0e8a5a2f0a97ce59ae06242f8982075",
          "sha1": "45550bd0243523e76fa220546577c2164beea21a",
          "md5": "5289e26a9d6385a9bc56d735232a8977"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.18-sources.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.18-sources.jar",
          "size": 340333,
          "sha512": "f443e506c2264b3a51557a752dee4c28fbeba41a4a2eb44dc76daf1bd7cacbe6471e495abcdb9b03cad4d7f3fffb8638b4f00180a152bd984c4f6b313ad32915",
          "sha256": "617bc3621f135240787b75bcf7729181e1f237183ddd93e004729c562bd9ec0c",
          "sha1": "92226ee230cd9275d1209bd93e76ca88fb58b0fc",
          "md5": "fe3a9150bcd3b19c3532176fd9385de5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.18-javadoc.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.18-javadoc.jar",
          "size": 75552,
          "sha512": "67052c246b6d21ce738ce2351395c8fbdb49712d22c1f54a7b0cae999782fcaac59a04fa4fd4340985db2d1d6df0b6a601cf99a82e5e5dadc60bbc0137ce20c1",
          "sha256": "229dc48dcfcbb869b2e946ca4da1e59ff8bbedde374030356d055b1ebdf72c23",
          "sha1": "a636cb108145acf9932ca51d918a6499b8c2a63c",
          "md5": "636611aff026071aff9637ac0b4c70af"
        }
      ]
    }
  ]
}
