{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.19.2-0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.9.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.9.jar",
          "size": 1699487,
          "sha512": "1761e204095a6f5a73b1cfa8dd35e497c6f67c2c3458c9379f2be2086d496090234f333a3ebf129f6062f60853ad21f2a0c78b0ec5230a91a9da1cb672568d45",
          "sha256": "53252883cb65237c3ab3a7cd1b9d24d75075a7aa01ac0e519910e5502725e99e",
          "sha1": "03cb89b4236cdc012aa71245e9249403a4b6d4dc",
          "md5": "73023b2d97f91c6fec0be34d6ac8350e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.19.2-2.1.13"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.9.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.9.jar",
          "size": 1699487,
          "sha512": "1761e204095a6f5a73b1cfa8dd35e497c6f67c2c3458c9379f2be2086d496090234f333a3ebf129f6062f60853ad21f2a0c78b0ec5230a91a9da1cb672568d45",
          "sha256": "53252883cb65237c3ab3a7cd1b9d24d75075a7aa01ac0e519910e5502725e99e",
          "sha1": "03cb89b4236cdc012aa71245e9249403a4b6d4dc",
          "md5": "73023b2d97f91c6fec0be34d6ac8350e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.9-sources.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.9-sources.jar",
          "size": 75383,
          "sha512": "4ef947d0555c698e805cad5bd4e88d2e056b9ab019e3d69caad41fefaa464f6b8766646bd2d1656f39c766abe6c33f71e3d93c0d49f8382cb923317c98363e3b",
          "sha256": "93aef7093c386c78c34eeea5807fccc3225f0f2241fcdd9fe3bd51cc7613d0ed",
          "sha1": "8d91bb59cb30bec289d038ec984d35c85f5721a4",
          "md5": "3ef0d8506f2f9ff0d0920f6f5b4e275b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.9-javadoc.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.9-javadoc.jar",
          "size": 75318,
          "sha512": "051c8024fdd208ec0268512a67147416301cf1244e6c1efd86d31a0ac6fe9361f01e06fb533474556d0bda641714b4e767a0b532578fc668062410cba48c2e78",
          "sha256": "db285dfb1d63720c12259871022a995154ab276f2729ff7db86aaebf737cfb0d",
          "sha1": "1178408c8d1fcae8510dfe6decad8cacda9abe4d",
          "md5": "4e115cc34de51aa9e88f1bd902131254"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.9-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.9-dev-shadow.jar",
          "size": 334080,
          "sha512": "85a0f8c13c064fa65c73be855ff464909e17477fa648d73427a92ccf86a6c0bbff645fb4ca78e814ee85588e7730b1ba7e92052d26cb707d2f53584f741d61d9",
          "sha256": "0949967061a352142c2ad17bb5e9c0eedfa337170a4c61411be754f3cda5f6da",
          "sha1": "b6196346ef1e498e85737082337a63998e24ece6",
          "md5": "8d7d3bac931750d1cf964de101be70df"
        }
      ]
    }
  ]
}
