{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.1.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.1.jar",
          "size": 2009834,
          "sha512": "e947619cfaa6fb048cf0d5f091ce89cd8aafcccf7985e5801c559d535d1720404cf2d236cb82bf3fa2eb45662d8fd68d4edcf0c72ec03015b79ab5f5081d68f6",
          "sha256": "c3bdc0e334acb242f0bc5d969a5fbd4ca544fea1197cfc76306d00df944663c8",
          "sha1": "52e61576aa4a1d567d23c9222beb0b783164e671",
          "md5": "72ef9fb63d31663ff16b67dafebfe2fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.1.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.1.jar",
          "size": 2009834,
          "sha512": "e947619cfaa6fb048cf0d5f091ce89cd8aafcccf7985e5801c559d535d1720404cf2d236cb82bf3fa2eb45662d8fd68d4edcf0c72ec03015b79ab5f5081d68f6",
          "sha256": "c3bdc0e334acb242f0bc5d969a5fbd4ca544fea1197cfc76306d00df944663c8",
          "sha1": "52e61576aa4a1d567d23c9222beb0b783164e671",
          "md5": "72ef9fb63d31663ff16b67dafebfe2fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.1-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.1-sources.jar",
          "size": 581267,
          "sha512": "6d51502b7a18a6b2ca0daac397b327ad15a45a2fba254aa9be1fd005c3f428932b43e1bf03ba2701f074a3e8be9d855d0f5a53813f066ce38295294440d15244",
          "sha256": "1c03fc9aeebf74fcb0c037659ce5a2fa07e575f0785c40a44ff9daeca2de00a8",
          "sha1": "a365ff1dbaebe85db100ab3444062ba574714692",
          "md5": "7cbe958e7cff4ce308c8c3f4d1ae7c87"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.1-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.1-javadoc.jar",
          "size": 259379,
          "sha512": "34a036bb014c752116dca1eed59a2c6b2df4a686870713f91f031775d5cfd33dc938c5b09f6cb9b99a79a43e68cad30fc7ad48002bdbd0c408e2621069166938",
          "sha256": "68c5264db9bf726a16e2e7e2d3513f8c8b5988082ae5c1be9573822f685f01e2",
          "sha1": "fc7985c2e14bbca8d5f1d553f2b19deabca679b2",
          "md5": "71d27c4e3f70f451049c1d7d69bf7f49"
        }
      ]
    }
  ]
}
