{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.9.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.9.jar",
          "size": 2089558,
          "sha512": "a1dfa17d1b7c60120c00819fb79b255720d8594466e2d764874f7ed5a5a2be0aee248e4a8d30d381a839365b1f11e047e1caff53dbe35e9a0650b994f8ec376d",
          "sha256": "6722b666d1c443ba72e3b4214f3e84df3802aa2251fa6b06f74c4c56c2c56b10",
          "sha1": "43fb6c42bce40ab4c69ab1dc6cf88402ec85bd2b",
          "md5": "ed69a3196a0f21ef154f290de41c0db3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.9.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.9.jar",
          "size": 2089558,
          "sha512": "a1dfa17d1b7c60120c00819fb79b255720d8594466e2d764874f7ed5a5a2be0aee248e4a8d30d381a839365b1f11e047e1caff53dbe35e9a0650b994f8ec376d",
          "sha256": "6722b666d1c443ba72e3b4214f3e84df3802aa2251fa6b06f74c4c56c2c56b10",
          "sha1": "43fb6c42bce40ab4c69ab1dc6cf88402ec85bd2b",
          "md5": "ed69a3196a0f21ef154f290de41c0db3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.9-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.9-sources.jar",
          "size": 608196,
          "sha512": "c8b0a4558458f5041915162affd8b4e502e0480749b28138f5a9b61582366b4226a8dc84fe24ae2321ccd046304e259445387bc54616dc0fd2bc1376ad6ff113",
          "sha256": "e77908b87e5251a576a45ff595f2c065f10cb02b4586a77bba0a5a3bd16b7ea7",
          "sha1": "b3382b7ec90fffc34da903b88d1f07a7f5d5bd2f",
          "md5": "ba37b465f9c663414a08975f8f8fa1ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.9-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.9-javadoc.jar",
          "size": 262222,
          "sha512": "fe03e2f24ae46d6f428f2596a4c8f660872af37cef6a56b22d97873102a243e9c23678d905a01667afdbf2ecb4905a8a5d18412853dbd03d180eb8b1e3b65347",
          "sha256": "f402b4ed504de2e993dec58073bac65fd03c13956debe5e7242b26d1653425e9",
          "sha1": "bf52bec9d8d60d99d942761daa4e598ac5d50577",
          "md5": "14b0ecad4bd3c2841d7bdae14b1095a8"
        }
      ]
    }
  ]
}
