{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.4-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19.jar",
          "size": 1473051,
          "sha512": "a29e0b422373906e8aa634ca246a9d08822474157385c5f82ba61673ce2ac0c3f9aaaeff921ad25648cc30055fa138312fbbf4762d79556b13ca83c5d62a84b9",
          "sha256": "f698672cfb311424687a7dab8b7f4205f4adf38faa8adad9f85cd99fc06682c8",
          "sha1": "1c907f053bb40a167a7a9d1498fe85b258c81e49",
          "md5": "93cfc1103919d74c2a13e6e9703e700e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.2+1.20.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.1.17"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19.jar",
          "size": 1473051,
          "sha512": "a29e0b422373906e8aa634ca246a9d08822474157385c5f82ba61673ce2ac0c3f9aaaeff921ad25648cc30055fa138312fbbf4762d79556b13ca83c5d62a84b9",
          "sha256": "f698672cfb311424687a7dab8b7f4205f4adf38faa8adad9f85cd99fc06682c8",
          "sha1": "1c907f053bb40a167a7a9d1498fe85b258c81e49",
          "md5": "93cfc1103919d74c2a13e6e9703e700e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19-sources.jar",
          "size": 80462,
          "sha512": "c909a7bafa8c5c7178fad017c9345ec82a384be3b548d9a86e1bb557fab475b65fcce64b71b8a86208fd7b640636f91255e2a06d8ec97ac566714d350493d11e",
          "sha256": "d4f3b156dc63e211694514a4134d3797b3720938efc95ad65f63d50772cc9408",
          "sha1": "cf37e3de87ea0b86da09e95726348b695f8a791d",
          "md5": "3f449a9b7647030309fcf9d4dc9a3c5f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19-javadoc.jar",
          "size": 86659,
          "sha512": "8fc2b11634d56f9415254d64acc33e3bec555c371330efcbd15914dcf3ef313ac1e3a16eb30c18b7ef0e934c85a1baf150d7b40a3988b480de324fa261b73f4b",
          "sha256": "84d64cbae109674448ccfe2c3c9d51b9f852c9f93e4e0a7425f67e22d9b3d6db",
          "sha1": "b3bb184a7415243df5946fdc8e57e8224bd6d984",
          "md5": "4b6a77e45f50a03a07d3743cf23c1cab"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19-dev-shadow.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19-dev-shadow.jar",
          "size": 536522,
          "sha512": "6916b710aa27b3faae351068173afef633f38ab5d60329496ec87154f3d904cad68fa92861683f7ae3e3f21159ec046918df9bd9eeab1cab40ac534c75415045",
          "sha256": "cb28e6e2f4b4b3cbe899d500bba2e8fc331c63779161a080ae7549830854afc5",
          "sha1": "e71eeda8a4355a141c64e327fa58245c27170e01",
          "md5": "49e31ffd076f8414c0cbf93e9f3ebf29"
        }
      ]
    }
  ]
}
