{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.4-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19.jar",
          "size": 1474868,
          "sha512": "45f56efc866771e8d405a4306c37e6e51cc57714c36288fd57e64edd08e8279b668ae8a948fab7aa53e8d9825fcd490b9efb3ec20294b7eca44ec744f5f2a42e",
          "sha256": "b3444bd1aae4c9cf4dc97e7a6481b3004b15d0c5c8448b56f4aa233ab2938f89",
          "sha1": "44d256059da9dcd390afd6be86f0bec21e9c088c",
          "md5": "4224f35de4e57a91932e805a26990e29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.2+1.20.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.1.17"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19.jar",
          "size": 1474868,
          "sha512": "45f56efc866771e8d405a4306c37e6e51cc57714c36288fd57e64edd08e8279b668ae8a948fab7aa53e8d9825fcd490b9efb3ec20294b7eca44ec744f5f2a42e",
          "sha256": "b3444bd1aae4c9cf4dc97e7a6481b3004b15d0c5c8448b56f4aa233ab2938f89",
          "sha1": "44d256059da9dcd390afd6be86f0bec21e9c088c",
          "md5": "4224f35de4e57a91932e805a26990e29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19-sources.jar",
          "size": 80462,
          "sha512": "8961219486d50b98a6e39015845be94b25b65b2e8bbe1914065465855789fe95f1686aa9164491c1dca0092496016e0f2140d04810263f14e2393815dba1c9a9",
          "sha256": "36e6e728493adc957a5bfd1f7856549f4c53762b52d891e480eda8fca9899efb",
          "sha1": "a46a6737acc008502033d944349b448f661dad9e",
          "md5": "387b00936bd81830ca891352fea30c97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19-javadoc.jar",
          "size": 75403,
          "sha512": "3be4de30c5cf149e3c549306b36e4dcd92631405c25d140af9ec0481809fcfeaf6bf4ca6f316efb10182366cf334893d1c1eb091eef9c0a92b2c03893689c355",
          "sha256": "d8b92c23807e4588e7bc26ab289d837d2e8b2e94f30636f9eea4406535df1f3c",
          "sha1": "d6eaf4ef22b80f1ab81f18cf8444d9782db54b1f",
          "md5": "67eae76d7ff326dcc725dd2c01222d50"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.19-dev-shadow.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.19-dev-shadow.jar",
          "size": 537728,
          "sha512": "dd2e7b0fc1d0f672e012af493eb5f1138f9285f764e27bab3090f781423e5e34168a85892937777121efd60b42332b860b5a80bbf9e3c2239055ff561155d674",
          "sha256": "0aafcea6e6f41ffee44ce22146fd31bf0ef3ee6ff521bda7809ef36baa68a1f4",
          "sha1": "ba2b40057f418bfb5d99ab8ae74651b45a5c3b81",
          "md5": "8764d70d409bfbf6631b949bb9a872d7"
        }
      ]
    }
  ]
}
