{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-forge",
    "version": "1.18.2-0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.1.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.1.jar",
          "size": 2266964,
          "sha512": "db8d74e78c4b222eb952d0f13168c07136745575ccb77c36742c525ba02ca605cdcf16d99fb2a1f2a9f809385c8c962085aa7a81a636219de8928c7da4d31627",
          "sha256": "75708981c556b01ca05b06f6af3a732882381946be4cbd936ec1762021013df6",
          "sha1": "546dd6bd1d0a75e3fcddd04b9f4653043ac0301c",
          "md5": "8b99e064cd7ab2cb9c7266c84d08d91d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.18.2-2.1.8"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.1.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.1.jar",
          "size": 2266964,
          "sha512": "db8d74e78c4b222eb952d0f13168c07136745575ccb77c36742c525ba02ca605cdcf16d99fb2a1f2a9f809385c8c962085aa7a81a636219de8928c7da4d31627",
          "sha256": "75708981c556b01ca05b06f6af3a732882381946be4cbd936ec1762021013df6",
          "sha1": "546dd6bd1d0a75e3fcddd04b9f4653043ac0301c",
          "md5": "8b99e064cd7ab2cb9c7266c84d08d91d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.1-sources.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.1-sources.jar",
          "size": 332001,
          "sha512": "575aca8c1715bc1f7f1d5af3344352b6d481ed3ad3772f2c25398044450b2d98a2a56f8b79f8eea5aed39876413b85367c76e75254148a5ecfec9de19de9d476",
          "sha256": "84c81c1a932fa2e0268f0aff3eb3e84990af491ce6db52057d88737c6557ad80",
          "sha1": "1ea501406a37b50b9ab56254e7da0645e14e9e62",
          "md5": "07d4373b7c67fce2fd4ac65c67bd9985"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.1-javadoc.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.1-javadoc.jar",
          "size": 74687,
          "sha512": "debd0ea49aaecd812f67f883e170e8651863ea7afff79e5ff200d90fa35dce31c63c7e5a22f2b0e03fb1ff47f5b6891dcae7b647ce704277fc5390bd9d61901a",
          "sha256": "6ea19fdb1ca2db66083a3f22940abe40a135e706ce86966a124b396e2cb60c5d",
          "sha1": "8a3dcfbe23212297e65964b8ef54e848602d1e5c",
          "md5": "bcecd0fc8be00e6989b159220858766f"
        }
      ]
    }
  ]
}
