{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.20.1-0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.7.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.7.jar",
          "size": 1649795,
          "sha512": "8304ac253a64c196680113fa8f9b1fcc3bf4313ba6fd874a96bf345dffda8be47960675e4b5629137ad9ceabbf1ec317c4db8227aec135d2cd105546a5f9abe9",
          "sha256": "04f9cc2e5085ee6f40aa1d9cc703c0b6e1016cffc8e3af11143b95b43ab37bb5",
          "sha1": "7d7a6cbd37eba3994a722b033ccdfd51283362d2",
          "md5": "f91aca9b8fcc09d5657dbdcdb370af65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.20.1-2.1.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.7.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.7.jar",
          "size": 1649795,
          "sha512": "8304ac253a64c196680113fa8f9b1fcc3bf4313ba6fd874a96bf345dffda8be47960675e4b5629137ad9ceabbf1ec317c4db8227aec135d2cd105546a5f9abe9",
          "sha256": "04f9cc2e5085ee6f40aa1d9cc703c0b6e1016cffc8e3af11143b95b43ab37bb5",
          "sha1": "7d7a6cbd37eba3994a722b033ccdfd51283362d2",
          "md5": "f91aca9b8fcc09d5657dbdcdb370af65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.7-sources.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.7-sources.jar",
          "size": 75400,
          "sha512": "1ae044602adb32329a36cbf6de3bef85497c29950b2be145079bb6f111bc536706929c8441cbd2cc166280f679d327494638056f2b290b5b9144034ef0d5bfa9",
          "sha256": "cf1e115a07d034ce4d6f0698ca7dfadbc971353db509c30c778786897a8cf520",
          "sha1": "4b7f4eb334a6ad0ce137e5ab5bca5c9b46eab316",
          "md5": "fa35fb0e7b01decd267729d4251b90f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.7-javadoc.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.7-javadoc.jar",
          "size": 75315,
          "sha512": "eff354dbe93e5f73533a58e091be6d8ec1757df0fc12946c06fb4bb8152ef31584a5b0434775e71877a321e0cccd8103e3a5261ed02f4253cbb9a808d9b72195",
          "sha256": "a5eea4f521a8555ff5e49b7d79ee3226334bc933846318722d045062c2b01d42",
          "sha1": "758bc417f149c0ad6badcc12ff6e1e1c12d41c72",
          "md5": "b771b7d6fb5a22e253f7636758ad980f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.7-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.7-dev-shadow.jar",
          "size": 334243,
          "sha512": "584d388faf06fa0542560f891e3f48ddedf2b21b33ede8c30eaf7142353b4df8cf343accfc1faae0fb7a12cdf44dca1821df70494bff3d794c593a6f388b9c39",
          "sha256": "62acf893d74666428c1adc2b259f972eb114e00a8c1e476f26479992e790a419",
          "sha1": "4d5be1290436c63f7293f7f17f1a55c114f53962",
          "md5": "722a96b485e67194912a25cd190b643e"
        }
      ]
    }
  ]
}
