{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-beta-3.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.8.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.8.jar",
          "size": 1870517,
          "sha512": "a11b8fdc8eec67e2e3a88559ba78599df52b1cc324bba4171d62f5f036b6f0cf0a67de1d921dcb99712a07e1718f075a7078a44b137dee818cc7ad34601308dd",
          "sha256": "bb4ff64f030ff2ef71bda0f4d034c13a3e1beac74cdce647bd7565f50456efee",
          "sha1": "1cce5f12930e9612c4c6307b91bcf7f50a47f609",
          "md5": "67fca9f23f413f5821cd3a2fde2d9f01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "curse.maven",
          "module": "time-control-303570",
          "version": {
            "requires": "5095704"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180900"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.8.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.8.jar",
          "size": 1870517,
          "sha512": "a11b8fdc8eec67e2e3a88559ba78599df52b1cc324bba4171d62f5f036b6f0cf0a67de1d921dcb99712a07e1718f075a7078a44b137dee818cc7ad34601308dd",
          "sha256": "bb4ff64f030ff2ef71bda0f4d034c13a3e1beac74cdce647bd7565f50456efee",
          "sha1": "1cce5f12930e9612c4c6307b91bcf7f50a47f609",
          "md5": "67fca9f23f413f5821cd3a2fde2d9f01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.8-sources.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.8-sources.jar",
          "size": 792535,
          "sha512": "c3b1b32b42dcf53799dfa930bcea0b74c9935c431e00b9fc15752eaa7ce3afe48a724b66c1b922f0eac59792196ed2127b72264f7880ede02600c044b752694f",
          "sha256": "afee5137a51a3d6fad984203b3bf1e1c8fe51c8cb8b7e445e65a96a3e0b2d12a",
          "sha1": "4f302ab42044d2196d739fd6e25d88717d68f5ba",
          "md5": "70882fd0ca8fd53ee266ef57e7d28927"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.8-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.8-javadoc.jar",
          "size": 148217,
          "sha512": "b7fb5bc8220ae192a2f3ced3f4c07207a209c2e1e149d91d182f7a65f36c298822650c05e4d5340892b5a6f2d04dd5b185f8ac4e745110415fc729a920c188d7",
          "sha256": "00d9aaede0305a2669837688b4958db91432d225e93321677faeb0a437f4ac5e",
          "sha1": "b0af8cf8f82a353bd410caaa10d01651c729e8da",
          "md5": "4293c48a1dea2d7d79fe74aba02c02ac"
        }
      ]
    }
  ]
}
