{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.18.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "size": 1367746,
          "sha512": "8759876f9efb475773c6e90974cbc274296891fb13b865737f07f6774d108cd5862dadd27381c39dbe5409e1c135071b191752615149a45d36b9dc5863d587d0",
          "sha256": "e3f6a7440b5335e9334357e7c0b8605854b34dbf2a071b8fe255557eee4e0331",
          "sha1": "3ddb9e05acad5805f28467476b9603a6dd4b6267",
          "md5": "2d31fe3aae3f65a147741087706db521"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.18.2"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "4.12.94"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "size": 1367746,
          "sha512": "8759876f9efb475773c6e90974cbc274296891fb13b865737f07f6774d108cd5862dadd27381c39dbe5409e1c135071b191752615149a45d36b9dc5863d587d0",
          "sha256": "e3f6a7440b5335e9334357e7c0b8605854b34dbf2a071b8fe255557eee4e0331",
          "sha1": "3ddb9e05acad5805f28467476b9603a6dd4b6267",
          "md5": "2d31fe3aae3f65a147741087706db521"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19-sources.jar",
          "size": 346416,
          "sha512": "4e1fbadf2a983bd87cb07a363fbf6358ff863b74af90c931f7769dabb0cd992bb580998d86526ea932ef6d37270f56bd8f859edb244336170fb64edb823dc5ac",
          "sha256": "697768930141951b379c1f92e8686a7b9ea52495455db4f8af97b4b694089e93",
          "sha1": "ea973c603d24a6bac18a04f1c01a1a65ed657a9a",
          "md5": "890f4630202a3b6370b150a5e24e1181"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19-javadoc.jar",
          "size": 86649,
          "sha512": "7e37f543da55ccd0f5f79374d1f943cc728da605c2cdc71c25cd2b6e44187c74ddb66c80e277c5ab60dae4122e253e3043177024b18742061edfcce44ec34f49",
          "sha256": "f7c996cfdbc052873b52016a8757a4af2f9fafc6ed140445d00c3c15c5ec4943",
          "sha1": "09a57970ecc97a6557f0f5f62632004208f347d9",
          "md5": "ccba6873eaf7a99b280f477a5b274bae"
        }
      ]
    }
  ]
}
