{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.18.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "size": 1369426,
          "sha512": "5b73abceb48099a256789c3268e070b6f3f83d889f051a607a65cb65b3ca429f8a6cb5580890f802e215ef277c5d91e74099678cfc1846bcbcf4819e59939008",
          "sha256": "71e92cb072d99e999ec39832557f95c499edabff18043c19d15461c497922936",
          "sha1": "e015fd99b7a5874280f700b7a1e166ee2d712842",
          "md5": "c235cd11260ed9e67c4a22f4d7dcfbfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.18.2"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "4.12.94"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "size": 1369426,
          "sha512": "5b73abceb48099a256789c3268e070b6f3f83d889f051a607a65cb65b3ca429f8a6cb5580890f802e215ef277c5d91e74099678cfc1846bcbcf4819e59939008",
          "sha256": "71e92cb072d99e999ec39832557f95c499edabff18043c19d15461c497922936",
          "sha1": "e015fd99b7a5874280f700b7a1e166ee2d712842",
          "md5": "c235cd11260ed9e67c4a22f4d7dcfbfe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19-sources.jar",
          "size": 346471,
          "sha512": "6471cf91a3188a71ca433090382d68645e74842b54be0282b7408d3b6d27d4d1c5dba58019de8dcc6a9d8459cf00690755dfa5a03315259fad2e559e374bf3e1",
          "sha256": "05dc8b58fe423f6243c98555b99080647de863d2c6d72486a039d197efc8418c",
          "sha1": "b2fca3c9212a8c569d276bebe4ecb4e4bc18a630",
          "md5": "a5c80d6f5473492d1c2e23093eb78637"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19-javadoc.jar",
          "size": 75396,
          "sha512": "c884c340f1527f4f459177f8ac1ab6fd7eed6389caa1fb5666e1255cc04f65a103fc4377fd65d66f16b2a015cec05824fa7c5b2dfdb5412e86662cd2bee18968",
          "sha256": "c75cc43b483d66fc294f9c4a3197e8ea9db454e00f22251594423bface781855",
          "sha1": "86cb758c5e4fe9e54a4249fae12c49d19bafc46a",
          "md5": "65a728f3fd8f6df53cc45eb278f81122"
        }
      ]
    }
  ]
}
