{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.18.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "size": 1356895,
          "sha512": "dba6ec6215d48cb7fe126b1fff7f324b94ffd38db619f9af5e4e19bc79c0b54a0cc04ccef43f013211a06cceb9953007c6c0441a039b5711c051ac895e47ff0e",
          "sha256": "e6948a39f2c25ab84811160dd005c45f7043b3eec80d6ac11387e335635646cb",
          "sha1": "ebe89681abb20a3c2ee82c9648e9a62578540bee",
          "md5": "88a1a29e9231d5492846217307094b0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.18.2"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "4.12.94"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19.jar",
          "size": 1356895,
          "sha512": "dba6ec6215d48cb7fe126b1fff7f324b94ffd38db619f9af5e4e19bc79c0b54a0cc04ccef43f013211a06cceb9953007c6c0441a039b5711c051ac895e47ff0e",
          "sha256": "e6948a39f2c25ab84811160dd005c45f7043b3eec80d6ac11387e335635646cb",
          "sha1": "ebe89681abb20a3c2ee82c9648e9a62578540bee",
          "md5": "88a1a29e9231d5492846217307094b0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19-sources.jar",
          "size": 341084,
          "sha512": "8ec037914c7d159183e28287f535bd01036a5461fb179154d13f7c6026c6a02097ed953669eae0338751eff5f765ab90c1c02a8f008dace169aad3bdff0fb7ea",
          "sha256": "b96448b3f187fab4b687fd44a45dad1a97da1f8301b9093a4a60bac958862057",
          "sha1": "a584305f75f1c92db01ad2a372dcc43a9176738f",
          "md5": "81f17135cc8e4380b9496fb05f1e9e5a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.18.2-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.18.2-2.2.19-javadoc.jar",
          "size": 86649,
          "sha512": "7e37f543da55ccd0f5f79374d1f943cc728da605c2cdc71c25cd2b6e44187c74ddb66c80e277c5ab60dae4122e253e3043177024b18742061edfcce44ec34f49",
          "sha256": "f7c996cfdbc052873b52016a8757a4af2f9fafc6ed140445d00c3c15c5ec4943",
          "sha1": "09a57970ecc97a6557f0f5f62632004208f347d9",
          "md5": "ccba6873eaf7a99b280f477a5b274bae"
        }
      ]
    }
  ]
}
