{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.19.jar",
          "url": "dragonlib-forge-1.20.1-2.2.19.jar",
          "size": 1272969,
          "sha512": "5c67064f2afcc706c452b8144df2696945668cf445838c82dc911ff0f3ecff75f93e623845f725cd4865deab1c49a5bfe406b6e0a896b05be4caac55c2051f92",
          "sha256": "a05c14708f7777114886a3e6867fb683b58c3fa635ae8c55e0da0badf45b3a04",
          "sha1": "006a89363e1195c13c38be83e11ad087ea4586b5",
          "md5": "7c50b7c44f8d133833bf66c97e66fb61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.19.jar",
          "url": "dragonlib-forge-1.20.1-2.2.19.jar",
          "size": 1272969,
          "sha512": "5c67064f2afcc706c452b8144df2696945668cf445838c82dc911ff0f3ecff75f93e623845f725cd4865deab1c49a5bfe406b6e0a896b05be4caac55c2051f92",
          "sha256": "a05c14708f7777114886a3e6867fb683b58c3fa635ae8c55e0da0badf45b3a04",
          "sha1": "006a89363e1195c13c38be83e11ad087ea4586b5",
          "md5": "7c50b7c44f8d133833bf66c97e66fb61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.19-sources.jar",
          "url": "dragonlib-forge-1.20.1-2.2.19-sources.jar",
          "size": 570114,
          "sha512": "aa0964bf28cb8469fbdfccd43f0307d3789a53f9a8413f0208180d0c1f6a7970cb1199d31bb0653187093eb77604e251d94f2c667d7bb8a678cd0e1359362ecc",
          "sha256": "5372b450e0b10420f13a442d979e769a430c2e769bed908c39c801fd02ad3dea",
          "sha1": "9756fc09ac86bea16ed9ca915768c77c17bdff1f",
          "md5": "3d125690fb6add04be0c7e63e5f9e876"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.19-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-2.2.19-javadoc.jar",
          "size": 74781,
          "sha512": "77a757e48cfb168a5c8dbfc8161f529d98ea1f2b0ca42b7f73d36364bfdd4c1fac3e4072e5a77755fdf961dd4419f498635651868958f6e0b9622ffabea9152e",
          "sha256": "2a30b89d6795e2d6f621a4f1ef58f4e0058f857d815a1914bd5d384f79ffc156",
          "sha1": "2ac5e4f8994698d801094c1db35b64c44d16b091",
          "md5": "f8ca743f2ea5e0b23acee6631757b341"
        }
      ]
    }
  ]
}
