{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.19.jar",
          "url": "dragonlib-forge-1.20.1-2.2.19.jar",
          "size": 1271192,
          "sha512": "c0ee0025b730555f851704557869f9ffed8350ac41517385ed30a95508894160a327fb48ca10485bfd8101d131c36e2f70c62a015359cee306ecd5f6188974a9",
          "sha256": "d71fa4a15269135c2f264df21e6e0ed571ded52ac72a8e029d50af0742cc465d",
          "sha1": "46de29b705c1ecd232d72077f4b7c1820a9da825",
          "md5": "562279d23ccfeaa2672e844773b053a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.19.jar",
          "url": "dragonlib-forge-1.20.1-2.2.19.jar",
          "size": 1271192,
          "sha512": "c0ee0025b730555f851704557869f9ffed8350ac41517385ed30a95508894160a327fb48ca10485bfd8101d131c36e2f70c62a015359cee306ecd5f6188974a9",
          "sha256": "d71fa4a15269135c2f264df21e6e0ed571ded52ac72a8e029d50af0742cc465d",
          "sha1": "46de29b705c1ecd232d72077f4b7c1820a9da825",
          "md5": "562279d23ccfeaa2672e844773b053a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.19-sources.jar",
          "url": "dragonlib-forge-1.20.1-2.2.19-sources.jar",
          "size": 570009,
          "sha512": "64878aae629c8ad20a6c14298d248b3235c42880d6df3486b553be53c594a7c15fd19bc80cadf0295d6fe933b955f9a4fad754762cb443a23c2c7d9f9c1aaf41",
          "sha256": "03c7d4a59f6f37e59f14588b194ffed38d064bc71262ced33b09d36d9094c0f5",
          "sha1": "92ad1b7b97fa20cda8a99d8e3ce18730e1c10139",
          "md5": "5108b0d1535fe70cf9afee2036f243c5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.19-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-2.2.19-javadoc.jar",
          "size": 86093,
          "sha512": "c239c78b4d057849c441c0558fe97b124e971023739a8c7f8a656fccc8a8904622ddbcc8b8f01c1ff721cf0682f8e07a8e31b43a711b2f47fb65f364d193d4c1",
          "sha256": "0f36c540618baa2a0ed37c7c860a433abf3da26b765484f427406fd1e56c34cd",
          "sha1": "e3afa229817a9797824409c9c20add8ac56b12cc",
          "md5": "07067e87ba8b35f6c9199dd51c1621bf"
        }
      ]
    }
  ]
}
