{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-forge",
    "version": "1.18.2-0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.8.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.8.jar",
          "size": 1621648,
          "sha512": "7acddeabf9eaae4f7b4854fc2c67bd5950d2696507d033f897c92ebd65e932844d272cc9d2f12b799ac7a669ef54b2098a3041a7d952248dc97a62efdf57cae5",
          "sha256": "85a20e32e563d37273eb71553a827b3e631fcf2b87fd6c1872d792c2108a28fd",
          "sha1": "5eaa94327e597427155580bf90a9413df696ce3b",
          "md5": "a6496506fd761e6e0800a3bba3f7734d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.18.2-2.1.12"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.8.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.8.jar",
          "size": 1621648,
          "sha512": "7acddeabf9eaae4f7b4854fc2c67bd5950d2696507d033f897c92ebd65e932844d272cc9d2f12b799ac7a669ef54b2098a3041a7d952248dc97a62efdf57cae5",
          "sha256": "85a20e32e563d37273eb71553a827b3e631fcf2b87fd6c1872d792c2108a28fd",
          "sha1": "5eaa94327e597427155580bf90a9413df696ce3b",
          "md5": "a6496506fd761e6e0800a3bba3f7734d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.8-sources.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.8-sources.jar",
          "size": 331300,
          "sha512": "b418c9f7e3c889d9d9f49a8f959a4a8816bb23303f140794494577bdc2dc0437e3ba10b069d46c9f670c46f0419f1ef0cb9db5455b9e9753a13ef58a2786b030",
          "sha256": "1f02fc3a8a1af257ffee160846c48d165dd82054200bab3eae5e6f640afad498",
          "sha1": "3a97fea67113ac03441e547a90311efe6265dfa8",
          "md5": "48db3d45c81d23ae0e555909985b17b2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.8-javadoc.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.8-javadoc.jar",
          "size": 74692,
          "sha512": "1abb168967c161783ccdb864c6d560aef690866a15103cca7fecd6894da4e4ac16e45a0a4b65e94870fadeedda4aa45c2e7b091c94bb0e7a7f820ea2443314c3",
          "sha256": "ff08d0f16049889184b764d48be8ae70c0a801de14c28ad540e9ecfb56be4170",
          "sha1": "9399bcb419ff4255c4925640d41b6b15d2508bee",
          "md5": "d2b112d50792cb53ebea8b5ecb1e226b"
        }
      ]
    }
  ]
}
