{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-2.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.14.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.14.jar",
          "size": 1337257,
          "sha512": "d3343116c0718e1ba6a26a6d970e9b77fee3ea762246bc52d146baede20871613065f12b4ed5f8aaabe00a2cac4d7b3ab9355410395d8f88d2c3fc371cad819c",
          "sha256": "0aedd810d25d5973774527ca1866b10dcc62126f001291c129f1bf2b1dce97ec",
          "sha1": "5b3925b3102b4e380657b08fa396bef5ebd0d0b4",
          "md5": "131617705edfc2d4dd41221ca1647e0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.14.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.14.jar",
          "size": 1337257,
          "sha512": "d3343116c0718e1ba6a26a6d970e9b77fee3ea762246bc52d146baede20871613065f12b4ed5f8aaabe00a2cac4d7b3ab9355410395d8f88d2c3fc371cad819c",
          "sha256": "0aedd810d25d5973774527ca1866b10dcc62126f001291c129f1bf2b1dce97ec",
          "sha1": "5b3925b3102b4e380657b08fa396bef5ebd0d0b4",
          "md5": "131617705edfc2d4dd41221ca1647e0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.14-sources.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.14-sources.jar",
          "size": 319507,
          "sha512": "36955c90056f7cc021646745182c2d3b716090d72fb71e400b8a686f3baf4dbb03ed0b237d8bc0c89b49cad3094047f0b910c08c0b8ca98ae70c1fa58b4e377c",
          "sha256": "4fc7c7ef5d0ddf3167d791329377921e069eeccab45c9f250fbb31df1bd865bc",
          "sha1": "4c089f6c771a538324cc392e34f1de76fdf06006",
          "md5": "178b8c4e42993ab3efb71efc40700af5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.14-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.14-javadoc.jar",
          "size": 75559,
          "sha512": "14ef3944585176688e3a3774833bb519ffa26f21a958f2f2b265d0dc9807a220c19d91418352cb3750ad420959bdb8e9ccc7cfefb3f33f04eaf16a06271205fc",
          "sha256": "39b9a6d14601ad4fb8a6b1c7f364bf10e858029163709f9ab93710c2aff19faf",
          "sha1": "8196c8fb54f8b5583049dc677d88e01cc5a98591",
          "md5": "04de280284e5083ec2b76ff9ee219660"
        }
      ]
    }
  ]
}
