{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-2.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.14.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.14.jar",
          "size": 1337266,
          "sha512": "d2c9ed6d55865eff8ecd511785893d64de39e557fc26454426e711060c781208b54abbbe29f190844e2603bf454a8630c6d06a3f3f3d889687eb93c5a811d885",
          "sha256": "f3eb7fa6fa9466686f9b30e790edf7d658493bd42690e41b578833a630dcebae",
          "sha1": "82d3c428e8ee1f6298e12db4f049bc9b4ebf17c3",
          "md5": "20272e2e57a8b1b5919d9022b8dcebf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.14.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.14.jar",
          "size": 1337266,
          "sha512": "d2c9ed6d55865eff8ecd511785893d64de39e557fc26454426e711060c781208b54abbbe29f190844e2603bf454a8630c6d06a3f3f3d889687eb93c5a811d885",
          "sha256": "f3eb7fa6fa9466686f9b30e790edf7d658493bd42690e41b578833a630dcebae",
          "sha1": "82d3c428e8ee1f6298e12db4f049bc9b4ebf17c3",
          "md5": "20272e2e57a8b1b5919d9022b8dcebf3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.14-sources.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.14-sources.jar",
          "size": 319503,
          "sha512": "b913171df04b1b74fb49c10f16a2a16a823e8ee8efb9e0f41f22c29944fb39c46383f3b44e35745b3dd2723b195e76ddbc0842184faaaa78b5a9a67c175fdf94",
          "sha256": "21885711b3618407da03187dabb7c6db9cd34825fd81769637ace8acc637c1f8",
          "sha1": "9190ec80f0b511e98ec73b0f5555c136da615d7a",
          "md5": "39f36072ed92713a8f0479023c091f1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.14-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.14-javadoc.jar",
          "size": 75559,
          "sha512": "14ef3944585176688e3a3774833bb519ffa26f21a958f2f2b265d0dc9807a220c19d91418352cb3750ad420959bdb8e9ccc7cfefb3f33f04eaf16a06271205fc",
          "sha256": "39b9a6d14601ad4fb8a6b1c7f364bf10e858029163709f9ab93710c2aff19faf",
          "sha1": "8196c8fb54f8b5583049dc677d88e01cc5a98591",
          "md5": "04de280284e5083ec2b76ff9ee219660"
        }
      ]
    }
  ]
}
