{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.4-2.2.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.20.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.20.jar",
          "size": 1481634,
          "sha512": "4c01957fa186a6aa866baced465be9df22086e3e2c9e6e3df944ff17629c6f3caf4632394a0f666b238b50d6a737cc98b3b4482698a17330724ba701330e7ec1",
          "sha256": "8eaa658f169638ae67668800315c87650612e6f1cd9b7185190f325983794533",
          "sha1": "a0d2a92309fde9505fe65bd3fff53223b0e78fc4",
          "md5": "eb66add87180da597bd896ebf01bf94c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.2+1.20.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.1.17"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.20.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.20.jar",
          "size": 1481634,
          "sha512": "4c01957fa186a6aa866baced465be9df22086e3e2c9e6e3df944ff17629c6f3caf4632394a0f666b238b50d6a737cc98b3b4482698a17330724ba701330e7ec1",
          "sha256": "8eaa658f169638ae67668800315c87650612e6f1cd9b7185190f325983794533",
          "sha1": "a0d2a92309fde9505fe65bd3fff53223b0e78fc4",
          "md5": "eb66add87180da597bd896ebf01bf94c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.20-sources.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.20-sources.jar",
          "size": 80462,
          "sha512": "2ba50ebbbdeeae77f7ce1b545ac50ab38bcb02acb205f5c36b203d79f167e1cbba75576698723713884e885a9216fc95cb791e7dbffc0e6551fdc3230d8bc864",
          "sha256": "fa9b02ff4488b732be8acf01025240546e2474022d69350f1ae1f42ae59085da",
          "sha1": "3f877df7ca6eca286498a70d0c517da4a2988f93",
          "md5": "2ee09e7e698f22916951dc81d59a8858"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.20-javadoc.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.20-javadoc.jar",
          "size": 86646,
          "sha512": "7584e75ac04493775e809c26692af8761480e9906e187229eb89c8aa4c1d790cb93094e02691fce2a327ce6019b0fe0808373f1a805216cc61fba94b7cc6bf83",
          "sha256": "ac31b4461da51e9212458b300698b9821a4747931dc3847a6141c256331b9a3c",
          "sha1": "6894c02a94f57dcdc633c8bd03b18e8dc6f50e14",
          "md5": "016f5adaa7329aad4e6ba506f16be47b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.4-2.2.20-dev-shadow.jar",
          "url": "dragonlib-fabric-1.20.4-2.2.20-dev-shadow.jar",
          "size": 544956,
          "sha512": "c4f89ec996ffa7149bafc46d35a442f683d34776ce9e721e81a1eca0a2d8f4b61f75c0fdafa0e779503c4fa170aa57e66530556a75a0974d385d647e9bbb5159",
          "sha256": "948cd2ba18fb738e3bdc946f6ce2ce5ed4194532b94be5a23021d8102d4e6d78",
          "sha1": "91a88e556d4e6f0598ad40870f0d7bb9a48951d0",
          "md5": "2624b1b8ad788722ffff6a6765ea6508"
        }
      ]
    }
  ]
}
