{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "size": 1405305,
          "sha512": "a3e8b9a85162e2f09fa03ef11e79606e7d956cb20cab37026eacb9786a2c13d778d2975d1c940ad6ccb36b047399888b7844f63dec141ddb4639bade74973a0d",
          "sha256": "51da3343c7196a96098bdc81192509e5d8bf3fae9e4918fe212defa5435bd335",
          "sha1": "fd6a54694b4602a3c0569f616d860c8353b928d2",
          "md5": "9b5bcd8b17e4937f38faa0b995aa9154"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "size": 1405305,
          "sha512": "a3e8b9a85162e2f09fa03ef11e79606e7d956cb20cab37026eacb9786a2c13d778d2975d1c940ad6ccb36b047399888b7844f63dec141ddb4639bade74973a0d",
          "sha256": "51da3343c7196a96098bdc81192509e5d8bf3fae9e4918fe212defa5435bd335",
          "sha1": "fd6a54694b4602a3c0569f616d860c8353b928d2",
          "md5": "9b5bcd8b17e4937f38faa0b995aa9154"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19-sources.jar",
          "size": 349609,
          "sha512": "10f116bb3e3cb5ddc726466033b347daa054218bea34a6d0ccc167a60a9f1f7b8f6632cecb2c6c285eef039dc14d8c6e6aaac90cc1cc961646f53c7b6b6fbab1",
          "sha256": "80b9fa4ba3ee81abb25978f5b0d20392f3e1ef8185ca1c8a8d07f9820e794fc6",
          "sha1": "0fad1b4b9735a7651c84a10afea26ff542e7efad",
          "md5": "6ede86214cc62ca3cd2083f9d0aa155a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19-javadoc.jar",
          "size": 86649,
          "sha512": "a494acccfa38c0313036e7ea1d8710b9d9d09964341692639c21bbdc217f7ae8ca21ce2732141f75b78bda83c4beb6f8622954e997e2b6e9e32b4adbcb15a068",
          "sha256": "7cc0995e73296ffea408223fba56b75ec020b0c07fd32af31653c6b179046833",
          "sha1": "be9b96a517ea6deaa1b2d4c700dff1560998a26c",
          "md5": "b404811b6b1120625e9f0f3b3a561238"
        }
      ]
    }
  ]
}
