{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "size": 1407130,
          "sha512": "8cb624e0f9e45a89de99991bcfd6563b0b7c1912edc2905d98577ae8aa5980dcb4b5eb38eec92ba5546e1f6c1770f3c50f7635314818b52901695fbd1b1f2b1b",
          "sha256": "07a9d3b45863c0578bc2466a682853711cdb50b9ffe1acf8b3b0a2550537ba59",
          "sha1": "8a4d4a32b61a06c5f0f0ff69010f7f364014ae04",
          "md5": "ca682ac9ac734db462f19791f1400cb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "size": 1407130,
          "sha512": "8cb624e0f9e45a89de99991bcfd6563b0b7c1912edc2905d98577ae8aa5980dcb4b5eb38eec92ba5546e1f6c1770f3c50f7635314818b52901695fbd1b1f2b1b",
          "sha256": "07a9d3b45863c0578bc2466a682853711cdb50b9ffe1acf8b3b0a2550537ba59",
          "sha1": "8a4d4a32b61a06c5f0f0ff69010f7f364014ae04",
          "md5": "ca682ac9ac734db462f19791f1400cb0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19-sources.jar",
          "size": 349732,
          "sha512": "f987c4d7896f8cdae772a7e1afc86b8ee225ad7e974f33f959fdcbfbcd6079192d3f0e636a0c7415f3ebadb09d4a972e3008f8d0ca378056a55e2b00a586aa6a",
          "sha256": "1c5eb423d78d72195657dd567f1c1f88e621a06b68b2d241ff21755d22e6ef4e",
          "sha1": "e3ac8b13b2c8141832ad269f904414b4dba47a55",
          "md5": "cc58d61ba525daaeedf90847c894b1fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19-javadoc.jar",
          "size": 75396,
          "sha512": "e46ccfc1ce9d0cf67cf10d8a502b39d8693e9d4af759a568099648ff8a65bc6fcee6d05558cefeacb00fe4f512683d54edda1ede5d6f4d4a30761e26585b90a3",
          "sha256": "3c196e40e8e2f81bfad76093aabd36f8e61bea3a47d99d907f483934dbaa22c4",
          "sha1": "2f4cbd8f03d32aaf10ccd281d091df6fc29891a8",
          "md5": "3d976951fbb2d7f2467e19dbdb4e667b"
        }
      ]
    }
  ]
}
