{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "size": 1394298,
          "sha512": "18d01cbc87e8a5efdca37e2dd73ecf60e43decc6fe79a1c1f16903f17b7c303df41e6d2c8de63f1a01be6ee3137082d556a62369428e99f642341d785e947ed6",
          "sha256": "fab36e5194e97e389643d5b90a8bb21251b6fc3c494c9458497f63f95bbe474c",
          "sha1": "c4f67c39a41bfc263da9c4fdee7515b96e11e4df",
          "md5": "40d7e4f7990367df2cf3f6aa53923508"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19.jar",
          "size": 1394298,
          "sha512": "18d01cbc87e8a5efdca37e2dd73ecf60e43decc6fe79a1c1f16903f17b7c303df41e6d2c8de63f1a01be6ee3137082d556a62369428e99f642341d785e947ed6",
          "sha256": "fab36e5194e97e389643d5b90a8bb21251b6fc3c494c9458497f63f95bbe474c",
          "sha1": "c4f67c39a41bfc263da9c4fdee7515b96e11e4df",
          "md5": "40d7e4f7990367df2cf3f6aa53923508"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19-sources.jar",
          "size": 344163,
          "sha512": "c0f125c6cf74b3b397319666e3f0efb041e168c67544c712c08c2d659ec20f981490846d5ebe6ae2d65468edf5d653606d5ee35c90aed6933afd56344146d3ba",
          "sha256": "eb567fb2b3c40eb066602665039e37969b9b478c3f067600f4f62c07168953e5",
          "sha1": "adf046cecb329e30fe99926e06800afb7641041c",
          "md5": "184f8d698b881a98f8d461f4a91d08cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.19-javadoc.jar",
          "size": 86649,
          "sha512": "905419d00eae57f52d3c4e448e97552463d93b3c2ffb70a507edeca68f3a94b955ec4c4f6f04b332ca883561389d6f417dcd97909b0bc30a94f2a982a5a69d17",
          "sha256": "ffe1b7744c364a40f2d8ef8fe94b008780325ad977f7a0deac0f6643b4bf7003",
          "sha1": "2b3803caf58996976b3a8ebe3a32afed976b7f65",
          "md5": "4d02ea0778ff6dda12d73a8f9b9fa4ab"
        }
      ]
    }
  ]
}
