{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.20.1-0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.6.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.6.jar",
          "size": 1649779,
          "sha512": "486c350550590c625554a0dc5e3e91e89d22b61501fa9e8011ee5ea428c7a55c0e04949767344ad1f3c9abdfa4ed9aaff22b859b7a8360fb1c6238df6c3d810d",
          "sha256": "01396baf9486fbc372abc70b4f5ad1175fd80c32e45fe45e23e2079c9221ac99",
          "sha1": "63278effe3461cf08ee6ec8d2aab806f8d7791b8",
          "md5": "5b6f9087216f629d58235c70b3a2d27a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.20.1-2.1.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.6.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.6.jar",
          "size": 1649779,
          "sha512": "486c350550590c625554a0dc5e3e91e89d22b61501fa9e8011ee5ea428c7a55c0e04949767344ad1f3c9abdfa4ed9aaff22b859b7a8360fb1c6238df6c3d810d",
          "sha256": "01396baf9486fbc372abc70b4f5ad1175fd80c32e45fe45e23e2079c9221ac99",
          "sha1": "63278effe3461cf08ee6ec8d2aab806f8d7791b8",
          "md5": "5b6f9087216f629d58235c70b3a2d27a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.6-sources.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.6-sources.jar",
          "size": 75400,
          "sha512": "b8b64e754131a3e4aeabb220672bf89fd1cbea1c4de641e1042ad7f739fb5e173cb2d4db9f3b22dc7f879cfdf03a84d985fc9c9a7b8ee372bd9adb7326d49d88",
          "sha256": "e44d33a8adbea674f088ca34027ce83b447815315af2ecb939246198b15fa73a",
          "sha1": "2d346a8f2c0161fc53f68b26ea72f9e582aed191",
          "md5": "1cd022e802870c9762d68cf861bd8fa7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.6-javadoc.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.6-javadoc.jar",
          "size": 75315,
          "sha512": "84507d10b292a616e87c2785bb1788efdddae9d40e60cd43186da02ed6100848f747af7c9945a0f79f5ffaa4257e26d40e93299e6b6882a46be9b1e093955923",
          "sha256": "f485a40565a359eebbdaa125bdf901b8e8b1961a53c36eef3e7e5eecf21c458f",
          "sha1": "ea0d8905cc3fab581ab74c12ac67924e8bf95b8c",
          "md5": "c75939229e2421f875bee0019fc62c1c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.6-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.6-dev-shadow.jar",
          "size": 334237,
          "sha512": "b557a79edfe494a0c56664b547a26ee7bc8aff0c4299a20e0fbc7572ba374b10ae2f8b1d76bb474d03e993ed722532e0fcb01d6e7f85e86babcfd1ebdd3b2b3e",
          "sha256": "5f55f5b01a7f0dc85f1ec917e096c186681be5e2f31bc5b0e31d901ce72e9181",
          "sha1": "0d374a642f9924233b166f88a5a1f11496a9e088",
          "md5": "62a0dd18796d202b852d5e26ba5dca8a"
        }
      ]
    }
  ]
}
