{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.0.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.0.jar",
          "size": 2008406,
          "sha512": "e171250a015b90f71adc47d76aca818f77742f2f1b979e8ea576f6c88fdb2ad14cdb4aa6f42203dc09846bde0d8971b693513f0375f6151a0599611798bb15fd",
          "sha256": "230a526354e2d4f40566e8279cd68aae5bddc0bdf8c2d66a8dc7e8c9217731e2",
          "sha1": "eaeec88fe2e3c8746d6e0899a77d2829a48d3409",
          "md5": "a1048b2bb3036308155097238a18b1ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.0.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.0.jar",
          "size": 2008406,
          "sha512": "e171250a015b90f71adc47d76aca818f77742f2f1b979e8ea576f6c88fdb2ad14cdb4aa6f42203dc09846bde0d8971b693513f0375f6151a0599611798bb15fd",
          "sha256": "230a526354e2d4f40566e8279cd68aae5bddc0bdf8c2d66a8dc7e8c9217731e2",
          "sha1": "eaeec88fe2e3c8746d6e0899a77d2829a48d3409",
          "md5": "a1048b2bb3036308155097238a18b1ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.0-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.0-sources.jar",
          "size": 581080,
          "sha512": "1920b31678df350e05c6ee66e5e4a8b3ee7c539eb8916f0c0c3195c8f939351659bed79d7747a926682537c309871eb2eec9dafec28a52822df3b2bc0ac38796",
          "sha256": "a48401557bab8de360ee5165f98ed5d90109e8a36541109f4babec29f5bb00d2",
          "sha1": "b046972f5780cec337e543f7c0aa289ff4ed5224",
          "md5": "8928f5aeaf17cf2f9e0ebf2e4a2f7dfe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.0-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.0-javadoc.jar",
          "size": 259487,
          "sha512": "393f30070cc751acbb48ede3a2d74e7cbc5e963dccaf8bde20de04beaa23a44d2958e26e536040da5a6d6057ef9325e1426a4215ae4aa709db0afae03bf9a2c4",
          "sha256": "c9b5d164af0ffc396ceb204b788b983eedb3fe443f393378d5ca97ad9c48dfe8",
          "sha1": "aa328f6d615b122058c1d697e8537f2e639e9d0f",
          "md5": "8659dba10abd6b98578f75060e9f8be4"
        }
      ]
    }
  ]
}
