{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.18.2-0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.0.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.0.jar",
          "size": 2476368,
          "sha512": "10cc23753bc89ea6f653fa16633cc7aae0bee5fcbfb1036892e9c5ab8b4f97062b35e9539afd7ec4c4d59bb3b2e212300fa841095ce173ef8a4404041ca1705b",
          "sha256": "94a77620e4c9a7f674fa85723b7604c03634cd264030280dc6d41802b4c4d70a",
          "sha1": "d3881d1e871fa5117c8369600189e803c3472642",
          "md5": "11816f7cbf3f8460213e23ed826af0cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.18.2"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.18.2-2.1.8"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.0.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.0.jar",
          "size": 2476368,
          "sha512": "10cc23753bc89ea6f653fa16633cc7aae0bee5fcbfb1036892e9c5ab8b4f97062b35e9539afd7ec4c4d59bb3b2e212300fa841095ce173ef8a4404041ca1705b",
          "sha256": "94a77620e4c9a7f674fa85723b7604c03634cd264030280dc6d41802b4c4d70a",
          "sha1": "d3881d1e871fa5117c8369600189e803c3472642",
          "md5": "11816f7cbf3f8460213e23ed826af0cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.0-sources.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.0-sources.jar",
          "size": 75390,
          "sha512": "adbe2d52b54f9de72d36b21edc813e6412bb6476871389d6cdefa75c08812a53dc03cd308c6f56d412ffe75e691d9aaf99caf3a43da9b11a6261cf163fb71107",
          "sha256": "9f4095806e795d4567cad8e37feb3f74e7e2d64c94d0a58ff4c76f68ab917cd0",
          "sha1": "e5135805d2cb9a2a5bc0d9e0f97dfbcf7ad10c4e",
          "md5": "2809859a0b3f657919f39218ff524b8e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.0-javadoc.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.0-javadoc.jar",
          "size": 75313,
          "sha512": "a943cf6198b078ca098a36e8c78cd7632c8c000faaf2f80f970fd7811a83e381a537ba1d8d9da2bdf0cb1b41ddcd33a529f815f2885ed12f35441f6e71e8d287",
          "sha256": "466d248f31b0c2e7cf4ff0c8810ab7d6cf8fe4a2bdef4d9bd1a5cafe3db4837f",
          "sha1": "09f6b13ee84666ed7e1fc0be52dbd9d7bd1e1e47",
          "md5": "a42b78dafd2d61c4ed9393dc6af4b494"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.0-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.0-dev-shadow.jar",
          "size": 333443,
          "sha512": "57520a80b9cb10fcd79b39712a2bb94f13e0c44bcfecaf9d942390a095e70f14f5812bf708bfb51284ff13778334077137feb2c1f4f52b3205bfb2147f1789aa",
          "sha256": "28e9f9900dd1c59c3707fc20b0a9a26404595a480781a2ca21fc4e0e1b821578",
          "sha1": "3c3c67a3adce19970e9d14983159892a51a68008",
          "md5": "450423a0598658d01e4922630e339085"
        }
      ]
    }
  ]
}
