{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.3.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.3.jar",
          "size": 2016172,
          "sha512": "76c4f2d4c70981afd1cdf5de04e7a2b46704df7dc614f5401bdd446208b889d9ae4e62e46a80d0ac67aba00a4691f48a952a83f39af613c5359a72f9b78c87ef",
          "sha256": "01aafc080ee4a2fcb60c606924e546d127aab9b7f8b04ce9ba05cdabe005adfe",
          "sha1": "4947c2fd76b0dc22f127087607e7f9512bc39de8",
          "md5": "7ef9a20a80e063454ce5cd0b8d3153ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.3.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.3.jar",
          "size": 2016172,
          "sha512": "76c4f2d4c70981afd1cdf5de04e7a2b46704df7dc614f5401bdd446208b889d9ae4e62e46a80d0ac67aba00a4691f48a952a83f39af613c5359a72f9b78c87ef",
          "sha256": "01aafc080ee4a2fcb60c606924e546d127aab9b7f8b04ce9ba05cdabe005adfe",
          "sha1": "4947c2fd76b0dc22f127087607e7f9512bc39de8",
          "md5": "7ef9a20a80e063454ce5cd0b8d3153ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.3-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.3-sources.jar",
          "size": 582652,
          "sha512": "725caad56cbf0f392b40b9d200eefd982f8849d7c16068ebd6e64c833959b0e4aa3b38b30978a2dfedabc5354192ae6183e8063637ae9f1f82bf42a0f3b23e5f",
          "sha256": "ac44481747836daf2c8f7de25adc0b8688fbc659ba2f266bc8b11959d149bd25",
          "sha1": "100cd9c8142e6e82ebe90ffba98c69ba26781efd",
          "md5": "eda2e1e119f578e1d0928bb02595294a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.3-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.3-javadoc.jar",
          "size": 259483,
          "sha512": "029358a109247f5a34d21e924f2d5d7a36257a4f8609f8c7b6974937f956a6342ed132a93ef1b460d8ade8b06f52f9d0a3aa5148265a77860fc1e2ac0e7e5606",
          "sha256": "8cc5d788deff47e0a46b5441ef93eacf0236f95524903d12606704c5dffb77b3",
          "sha1": "a5e12b28aa63421e3bfcb780b084d4364fa1e7cd",
          "md5": "bd14cd8c5f9fc5986d3b3af6bf6062e5"
        }
      ]
    }
  ]
}
