{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-2.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.12.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.12.jar",
          "size": 1337065,
          "sha512": "c7f896300de08ee943f08312e4c24d868c95773e558eb9101ea1c99faa380cd2d31878abced87f6767f650f89129c928566b732ff43cfb494b4a331f595e8e20",
          "sha256": "43b71bd8a872edc539414a93181e543940d55f13b347f9835581ca7741fbf8fe",
          "sha1": "aaf129c6a6abd5888010fc0c75c208742b7d482f",
          "md5": "c22e8c401ce2eb1fc8cca0181a94b380"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.12.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.12.jar",
          "size": 1337065,
          "sha512": "c7f896300de08ee943f08312e4c24d868c95773e558eb9101ea1c99faa380cd2d31878abced87f6767f650f89129c928566b732ff43cfb494b4a331f595e8e20",
          "sha256": "43b71bd8a872edc539414a93181e543940d55f13b347f9835581ca7741fbf8fe",
          "sha1": "aaf129c6a6abd5888010fc0c75c208742b7d482f",
          "md5": "c22e8c401ce2eb1fc8cca0181a94b380"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.12-sources.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.12-sources.jar",
          "size": 318543,
          "sha512": "41dc24b69d86d1950a796b3fb902b34b12e91a5b2ad61f2a410ecb20c887783f39064a318f5ec6055a2d17779eec6674ee883874a549bc464bc1e6bb86006f70",
          "sha256": "a71c8e0fa88da55732804b6ef74bfae7f1c9f0c0ec375e77f2b696d3de739ede",
          "sha1": "2cdde2fba8f08a4b264f7c4348cba876b08ba708",
          "md5": "8ce627a324646663e7dd9f506b640668"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.1.12-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-2.1.12-javadoc.jar",
          "size": 75466,
          "sha512": "b5b623b1b6a3c96bf0ce92061c070e1f1eae39f6bddc24b7f0de43affdbb293d589f9a5783696dd5e2aa4b3202a5835993d5d075dc289acbab459247658b17f5",
          "sha256": "b32e17bf3691a5e73452546404fa519776da359ee7149de952c53772dcfc1b57",
          "sha1": "531f2c5bb96402529aea10255e4318d25245d9ec",
          "md5": "72f61d8d8bbaf79b01eff0740c176102"
        }
      ]
    }
  ]
}
