{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.4.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.4.jar",
          "size": 2036123,
          "sha512": "a78f6246f24b0639e2f0e30a8f53093b31a156f069fb0dd114a4114aaa9b2f74b9a28a794a20b65f962aa8c60b185990d43a2fada3945c631358b3a4da3b3529",
          "sha256": "2dab7057a08b319659e628e5fb5eb9b35d0971befd23b0024d124262eb39acbe",
          "sha1": "d18184b95a18dc118dd88f992212dd5617d59577",
          "md5": "0c09fbb49c437cc0d2e9f7d52dfaeac5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.4.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.4.jar",
          "size": 2036123,
          "sha512": "a78f6246f24b0639e2f0e30a8f53093b31a156f069fb0dd114a4114aaa9b2f74b9a28a794a20b65f962aa8c60b185990d43a2fada3945c631358b3a4da3b3529",
          "sha256": "2dab7057a08b319659e628e5fb5eb9b35d0971befd23b0024d124262eb39acbe",
          "sha1": "d18184b95a18dc118dd88f992212dd5617d59577",
          "md5": "0c09fbb49c437cc0d2e9f7d52dfaeac5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.4-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.4-sources.jar",
          "size": 590000,
          "sha512": "8b0857d61fac0c1cda0142fde92b3ab6bdc14a61f0e002deec1ab116f0b9e53da3219b46a6d3b2d6b74dfd582d14efad658451ddafc4079814a3a84ec9ceaa76",
          "sha256": "bd70a78458f587000be44de54fbac49cdf294ee8348ca1a6bd3a374f591b6b0d",
          "sha1": "a694ac6bebcb1451c38aa13e1261bb69bf361a93",
          "md5": "2985c71bca7d1f46154a8750b94bc344"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.4-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.4-javadoc.jar",
          "size": 259552,
          "sha512": "c629443b77da8d369778a011c0478085a60a2079a94d00ecc3499552edac685a0fb4f49f7afb080ad7115dd084a03ae86f56e377e9d05c4368e90bd688551c48",
          "sha256": "d70cd6d351e103b884dc4f7d4e0a06d0075005a50491bfc63ee1c6051555ba12",
          "sha1": "7fda5f1fc2e952edde5ae6e8e9f16a6f41cc2f64",
          "md5": "3627922b130fa5f14e0094fd5a6fd5e0"
        }
      ]
    }
  ]
}
