{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.4.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.4.jar",
          "size": 2035661,
          "sha512": "1689dca82e156f817c8d301e50526ed652bcad37ca7f503b22d01e14374a19635c473bf606541db8c68d79f22b8a7bd3c59515acf675df19c8af720fda608770",
          "sha256": "fb1f1aa4be2a31bb01c24931e602477663a07715a76722985fa69cf24f73b985",
          "sha1": "bdcd981fe3b772f55f4d7367b585f4b5a8295bab",
          "md5": "25bb47c6859a8e25fb46c0aa2ce1b4b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.4.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.4.jar",
          "size": 2035661,
          "sha512": "1689dca82e156f817c8d301e50526ed652bcad37ca7f503b22d01e14374a19635c473bf606541db8c68d79f22b8a7bd3c59515acf675df19c8af720fda608770",
          "sha256": "fb1f1aa4be2a31bb01c24931e602477663a07715a76722985fa69cf24f73b985",
          "sha1": "bdcd981fe3b772f55f4d7367b585f4b5a8295bab",
          "md5": "25bb47c6859a8e25fb46c0aa2ce1b4b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.4-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.4-sources.jar",
          "size": 587526,
          "sha512": "7c979d267b904b2e53bab6a6fe70a1adf3351a37a589a1f1580e8f8581b2dbb68d9999c3d66445c291800825cd11451d6ed0e7fe5f5112ad64442699fa73eaee",
          "sha256": "c7ae40e3831a9af2842101052251fdf5bcdacfc85c19f66f584d7be330e5d497",
          "sha1": "7c8c4ef31073c79848c266263c6514f537e312dd",
          "md5": "0462355ff9a192116890d1f389a507da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.4-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.4-javadoc.jar",
          "size": 259552,
          "sha512": "c629443b77da8d369778a011c0478085a60a2079a94d00ecc3499552edac685a0fb4f49f7afb080ad7115dd084a03ae86f56e377e9d05c4368e90bd688551c48",
          "sha256": "d70cd6d351e103b884dc4f7d4e0a06d0075005a50491bfc63ee1c6051555ba12",
          "sha1": "7fda5f1fc2e952edde5ae6e8e9f16a6f41cc2f64",
          "md5": "3627922b130fa5f14e0094fd5a6fd5e0"
        }
      ]
    }
  ]
}
