{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-2.2.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.18.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.18.jar",
          "size": 1393456,
          "sha512": "36d10ca2af3178c17253570230f136dea05ddccac4195a6c4c5ae0843d3194d5e172929e68d9f3381c517ad44e8b81420f5714a59a91b94de430e40ad41135ea",
          "sha256": "906855dae58b12e21e14e9a39d2eb45903df5808db059982a386c69b1070b18e",
          "sha1": "f20bbe3c57718285fb989a6f10334bee4eaec3af",
          "md5": "26583224d5b687677a5a1807572a2697"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.18.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.18.jar",
          "size": 1393456,
          "sha512": "36d10ca2af3178c17253570230f136dea05ddccac4195a6c4c5ae0843d3194d5e172929e68d9f3381c517ad44e8b81420f5714a59a91b94de430e40ad41135ea",
          "sha256": "906855dae58b12e21e14e9a39d2eb45903df5808db059982a386c69b1070b18e",
          "sha1": "f20bbe3c57718285fb989a6f10334bee4eaec3af",
          "md5": "26583224d5b687677a5a1807572a2697"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.18-sources.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.18-sources.jar",
          "size": 343249,
          "sha512": "5d4241eb6af94faaec1b75678752401ce5c4ebf1f37df22079ef986e8a178d534c251e1c2e20023fa35fb625a52824c2e229bbb0e4744b814c10cc8da962c4ce",
          "sha256": "3fc82e07f0707c7e915f0e77df471ff2696483eb9a274ce77e8986c7018583f5",
          "sha1": "2f521c8b77887e9458f255bd889761923fac9e5d",
          "md5": "4d99aad9cec7c0743710dc3a2b12809c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.18-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.18-javadoc.jar",
          "size": 75550,
          "sha512": "6d2bf722afb51721fc77d9dfea704e514428bb3dc5d9f7be71c7d1ab96ac6f138403cb0824131c0c4a632517113ea5f8f2a5d207477f3f856f8b6f759f04f95f",
          "sha256": "e8a34eb1fddfc21b23d4c174c676511a471e0a3c7bda2181dec9588ea7ad9820",
          "sha1": "afadefad1ae277057ab99f449148aae381c9516d",
          "md5": "e62f5a67f85691ee630621e6f214b260"
        }
      ]
    }
  ]
}
