{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.18.2-0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.7.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.7.jar",
          "size": 1611582,
          "sha512": "6ba1a54869ee2e8947a1156cbfdf723f61d19a7b8d06dd0c787f953ee69c6679130ebd234438832be417739576fff18ce42a3a48829c1eeccad4304719b1a128",
          "sha256": "05c0496c72bf1015ed4814995e2ce45687b81fb5bad7f672b76acc63038d2c71",
          "sha1": "9ffabe215ee7297dd04f929e27d3bba80da37459",
          "md5": "cc73bbeec7469b45364196c30e713329"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.18.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.18.2-2.1.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.7.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.7.jar",
          "size": 1611582,
          "sha512": "6ba1a54869ee2e8947a1156cbfdf723f61d19a7b8d06dd0c787f953ee69c6679130ebd234438832be417739576fff18ce42a3a48829c1eeccad4304719b1a128",
          "sha256": "05c0496c72bf1015ed4814995e2ce45687b81fb5bad7f672b76acc63038d2c71",
          "sha1": "9ffabe215ee7297dd04f929e27d3bba80da37459",
          "md5": "cc73bbeec7469b45364196c30e713329"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.7-sources.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.7-sources.jar",
          "size": 75384,
          "sha512": "711cb4ac6bfe8e3d1ce5236177492024882873736b07ddc0386b5443f394eaa38d134ec7461e8ddaf5f866583bd099a36466053125eeaff5c073c77c16aeab4f",
          "sha256": "5a79054b3c50af232360351867bfad26e43a3d5532d391ec19ce9b30ce35706d",
          "sha1": "4371ded94aa9cf82096641a019c3e2714a93ddab",
          "md5": "e1d289d7a61edcead85cfbd090d22341"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.7-javadoc.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.7-javadoc.jar",
          "size": 75315,
          "sha512": "90e3945309fc6ef2d24ef83dedf084be9fbcfe3b595f8040f01c4b2afc927acf5e4354eae46fa77c146fc820afb2ad3d9d159e6b7142902eb1402f404cc829aa",
          "sha256": "ea4e782e58c0a796db3fec10fb94d255d530a17e3cad4579c209b1f610e46f50",
          "sha1": "8c515746b6b63a9834a5866d4ec5a642b160a14e",
          "md5": "1a124239ca0db79daa009a920ca245c4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.7-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.7-dev-shadow.jar",
          "size": 331743,
          "sha512": "52e6d8acc64e4b626f64f2fad1f7cdc27f5baf6dae8a8700f4e900f3bae1d2406a05f15dde4f7b265186683fc4f809fa909db55e217129f76904c8bd4ae6f239",
          "sha256": "964189916633854b46309f7ac0ce3e47df8a87afbe2c54605278843fb106953d",
          "sha1": "b9d35617dd7cdaf57558d532a533ec99f74e0ab5",
          "md5": "ae01a6e01edaf87e2a734c389cd1f343"
        }
      ]
    }
  ]
}
