{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.20.1-0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.9.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.9.jar",
          "size": 1651048,
          "sha512": "d76e392ae7c161ce021ae249bf92b20e5724e836799e751c49f99bb03b747e999eb552339bdf89e3475e68867f874e8f71d31e52a9f0a8fd06015acad8991a81",
          "sha256": "202e3db76b839b00868b39622b1bfd7ca92960b6f515b5cd2eec7efa618beee1",
          "sha1": "a16aea7347e54548d7e2ad6267775fd0b751d5cf",
          "md5": "eea374c6d4adf6f5614fb4b7b9a4f1e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.20.1-2.1.13"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.9.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.9.jar",
          "size": 1651048,
          "sha512": "d76e392ae7c161ce021ae249bf92b20e5724e836799e751c49f99bb03b747e999eb552339bdf89e3475e68867f874e8f71d31e52a9f0a8fd06015acad8991a81",
          "sha256": "202e3db76b839b00868b39622b1bfd7ca92960b6f515b5cd2eec7efa618beee1",
          "sha1": "a16aea7347e54548d7e2ad6267775fd0b751d5cf",
          "md5": "eea374c6d4adf6f5614fb4b7b9a4f1e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.9-sources.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.9-sources.jar",
          "size": 75400,
          "sha512": "32397087830268aab27fde2e9dd606314ef15883460a4e437d33231f984c4a76eeba292dd66cf6f8e868185a24d2442a6f1c3a5faa0932cf1be004193b58f3e0",
          "sha256": "5bdcb113d5fd1ea87de51c7d61bbe904dcd855da280bbb911b76e16a264490c0",
          "sha1": "d72069f57195dc8d6c27ee6adf02a78a48f1d1c0",
          "md5": "c15727762085db9626fae2f2a1d497e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.9-javadoc.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.9-javadoc.jar",
          "size": 75318,
          "sha512": "1905916d29578bee77f45c70f34ab8b68a1ba76bd848d5c90e0ed94f149a64a4ce026b70ba6703c3c908f5a644e5768e8a56cb6f5927132e6f28d5c200a3c92a",
          "sha256": "8af97bca0b86538e1052a0cf00257b48a71d3d1d742dc6b038d6ec0ececb9557",
          "sha1": "29b30ca80f3bd17cb48b1b588755661fd7396e99",
          "md5": "eb1b39c8614a6f4b869266c43e46a0a7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.9-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.9-dev-shadow.jar",
          "size": 334729,
          "sha512": "1fca9fcb48513f9100845853edbeecee3072de5989e04f5d18bc3a5fcae70767fcb11fef6eadaaf90ca642d69111bd95fa6684f44c5e4164d9ea797fe450ceb0",
          "sha256": "52a552ecc2cab249b97bbb34d66c546f99ba14d07716f05b505d351230d4e194",
          "sha1": "eb320da4890feb90f6f28e01bb52411a10cd3de9",
          "md5": "309a2a9adece791fd0436a5897828800"
        }
      ]
    }
  ]
}
