{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-beta-3.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.10.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.10.jar",
          "size": 1886429,
          "sha512": "11fbaee153a3780398475208aa4baa265289651fd11778cf90bcd49ba201ccca15f377d4ebef5d72d764dbaed446e21861067f8f4c1373bf2c0a24c81d47f5f3",
          "sha256": "c478eeabb6e1323534661398656ddd113184655d072b4ae30191489c0b1ba7f7",
          "sha1": "616415902ee90af7599cfcefa99126d71779352b",
          "md5": "f6e2d04b268e525b1719991b09fcdfcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "curse.maven",
          "module": "time-control-303570",
          "version": {
            "requires": "5095704"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180900"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.10.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.10.jar",
          "size": 1886429,
          "sha512": "11fbaee153a3780398475208aa4baa265289651fd11778cf90bcd49ba201ccca15f377d4ebef5d72d764dbaed446e21861067f8f4c1373bf2c0a24c81d47f5f3",
          "sha256": "c478eeabb6e1323534661398656ddd113184655d072b4ae30191489c0b1ba7f7",
          "sha1": "616415902ee90af7599cfcefa99126d71779352b",
          "md5": "f6e2d04b268e525b1719991b09fcdfcb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.10-sources.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.10-sources.jar",
          "size": 798254,
          "sha512": "b529b56934f1853b4722b9227da7f9a03167ab701132813c783f1cdfa6909feeb071515bb593ae1bb8c7491196851ec1e33b03d3e6135f0fde9c32304d7d9d9d",
          "sha256": "2d48c2409a87b566261661f2a8a64409340bd120a057a25b7d0e829120d7d011",
          "sha1": "684c1e6b41fca32a1369369bbf5a5e2009722ad4",
          "md5": "daf5fbfbeaf2267fad7e3e30248e09f3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.10-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.10-javadoc.jar",
          "size": 148206,
          "sha512": "ea188a0ae5393cbe017c711170a0c5938e9e60d92b468734e70ce1aa97ed11a172077f3ea138d0ccfef9281650d814b5dcf1581adfbfcfe0a8e42736b355ef10",
          "sha256": "66613e444937197953b1676aba448c3424babd95247fe958fb1bc6b0f51f4425",
          "sha1": "8ce0681f7513ffe5bdb2e0169abe84eca30fe143",
          "md5": "1f266574bdad29cb4b86634924f24d37"
        }
      ]
    }
  ]
}
