{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-beta-3.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.10.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.10.jar",
          "size": 1886518,
          "sha512": "388486548de040db7ed321027e8f808bbc6dce557fad4c8dff3becb69ec50e792aa33cd86bb5f31c35261b1d07fec731895dc3bfe3c7f6401c0abd487b55c702",
          "sha256": "378c8757069dc0d132ca4cb33b5c65f73e2e18312473364a627a75fa1bc2a72e",
          "sha1": "1ab56870ac1d298600eda1b83190f87adfac2fe6",
          "md5": "cae8addccb792b59b4588b4f70bb83a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "curse.maven",
          "module": "time-control-303570",
          "version": {
            "requires": "5095704"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180900"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.10.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.10.jar",
          "size": 1886518,
          "sha512": "388486548de040db7ed321027e8f808bbc6dce557fad4c8dff3becb69ec50e792aa33cd86bb5f31c35261b1d07fec731895dc3bfe3c7f6401c0abd487b55c702",
          "sha256": "378c8757069dc0d132ca4cb33b5c65f73e2e18312473364a627a75fa1bc2a72e",
          "sha1": "1ab56870ac1d298600eda1b83190f87adfac2fe6",
          "md5": "cae8addccb792b59b4588b4f70bb83a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.10-sources.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.10-sources.jar",
          "size": 798300,
          "sha512": "c4ee2930f0d2c7d95bb7c244656f654845f38288ee05b8d5f036174b101b0b91b945dd85834882a050d5bb1110983e4259666bd54d7e09c3c74263594cb2f039",
          "sha256": "149e088429ed6ac96fc363d4acac421a2e2f11c4f411cdf9d186352e7d1b4109",
          "sha1": "a46acd76c0e3e169be3e57aa38242878d3801803",
          "md5": "05d5c020e1187b469301bf37b2539a11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.10-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.10-javadoc.jar",
          "size": 148337,
          "sha512": "a6870fe98d8e1f1debdcf4aca1b1cb2f194ca9b0f6a9349f7aef3fb99fe1ba8458523034e039865661848b0663d62f01330891ddf9f051407d370c6751892d43",
          "sha256": "2490c274411464118499608eb1bbf77e580b196b1cefea49105cd2be3aa6a786",
          "sha1": "d818837f205643bbef9d11c713ebe3588a9bc676",
          "md5": "c027be85577ed31a8690cb982cde3d4f"
        }
      ]
    }
  ]
}
