{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.8.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.8.jar",
          "size": 2072714,
          "sha512": "0306fc5aa8d4f36bf1639c64486696c48c760d9988c8a51af05a0669b5de56a91051e59bc4342224ac04cfa4101a59031f36532bff3743247e8fa47201f802a4",
          "sha256": "ebe4cd6e6ac0ea5611bbc940c94d5d2caa0b4c8bfe4c08e7a1e91b207816183b",
          "sha1": "2202443d568bf9736383ae68955dba85d537f6ac",
          "md5": "9ccba4390e8da874139bf02e87ef1d82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.8.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.8.jar",
          "size": 2072714,
          "sha512": "0306fc5aa8d4f36bf1639c64486696c48c760d9988c8a51af05a0669b5de56a91051e59bc4342224ac04cfa4101a59031f36532bff3743247e8fa47201f802a4",
          "sha256": "ebe4cd6e6ac0ea5611bbc940c94d5d2caa0b4c8bfe4c08e7a1e91b207816183b",
          "sha1": "2202443d568bf9736383ae68955dba85d537f6ac",
          "md5": "9ccba4390e8da874139bf02e87ef1d82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.8-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.8-sources.jar",
          "size": 601853,
          "sha512": "0d8c478921189a1f69a22047591ba0ad8c05f351f860c55eb8ab39c41fcd438e10952152f8d0c937768fe7fbb4c3c5c364bdf3b93a1f27c2c459ddf05ef4391c",
          "sha256": "f63c138f8fbaecab2d79111f8daf2db130081ba862f1f96dd8289fe05eef4288",
          "sha1": "378f23664e6f0d9fddfd582cd24043ae2450aa02",
          "md5": "b203d97281789d7be07e648768a7acd1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.8-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.8-javadoc.jar",
          "size": 259422,
          "sha512": "47008a906bb9432a7e70a504a01b4612b853943cb0ae117d42722b43c29fa1b61fc6dec0f50dbd51232facd88d8d1ffe0210f96a60ccec0b0ba3a5198efec622",
          "sha256": "eb0a3d4a8d6d45a58c800e9dd3881bb630763cd60833b704e4aa5023f4bb2e7a",
          "sha1": "0ced8d8bf9dc5b897764701691779ef58f6a13cf",
          "md5": "468093a732c3858040e97a5aac4f385e"
        }
      ]
    }
  ]
}
