{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.12.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.12.jar",
          "size": 2106090,
          "sha512": "d6721f75c26069fbf55b4a97dd24bcad3362244f8e76e44db0bab027ab667164a2c6180c13bf45370c5cd53033ce8348278f1b4ddd64eff71b0f366c4b392655",
          "sha256": "a359f6bc0c4ee440baa10a7ae2b7d1c12ca9b73cf8cb66bf1e3e5effe39b8485",
          "sha1": "de27e0cb46a39bcf6f58e8619f421905216c9d62",
          "md5": "d137bb3bef7e37fdf4cd56e2fadb2209"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.12.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.12.jar",
          "size": 2106090,
          "sha512": "d6721f75c26069fbf55b4a97dd24bcad3362244f8e76e44db0bab027ab667164a2c6180c13bf45370c5cd53033ce8348278f1b4ddd64eff71b0f366c4b392655",
          "sha256": "a359f6bc0c4ee440baa10a7ae2b7d1c12ca9b73cf8cb66bf1e3e5effe39b8485",
          "sha1": "de27e0cb46a39bcf6f58e8619f421905216c9d62",
          "md5": "d137bb3bef7e37fdf4cd56e2fadb2209"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.12-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.12-sources.jar",
          "size": 629547,
          "sha512": "0c83726dabddc1f30a1bf4778b7b122fba9d582a11aa4e810307b1951286c6fdb5214a9e02c0545c2305a52a6eac7da92be2c62a2969b9182fabe25ab1ab19fb",
          "sha256": "c431a9302d5eaf532fe6648dffeed68c5328f36cdb9ab47b2ce85453bb8b6904",
          "sha1": "31c4a748aec9cf5498864880c73c85f2269653f4",
          "md5": "49a4952b556e62af9cecb240d3894b93"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.12-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.12-javadoc.jar",
          "size": 262156,
          "sha512": "e8d97dfd052b08bcd16a0f0b44a25640efcfcd8d4b33654c82396f9cf664778945bad1eb62e491b3e1886c2dcb64d3b106cf1328a6ee37ce0f06eec6aa41be79",
          "sha256": "ac72cebc8587cf5192a0dcb3ef2c5dc065b00922ba12888ef582b2bdfabd045f",
          "sha1": "4e415324c68843d7f05838051f76c38b31b3da7c",
          "md5": "3c33ce82169dd3070d0de5cfa9a8c33b"
        }
      ]
    }
  ]
}
