{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.19.2-0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.8.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.8.jar",
          "size": 1699386,
          "sha512": "96cecf7b382d998aee696e565499c84361bb6421786a0913df61186663273d2e080e469127421deeaee35d430372c9348de185d2416ba8ecaa8f1edf36e54604",
          "sha256": "28eb54a8fe49b08af06095a8c5a7d6909d42538a857a957aeb1fe484f04f0f39",
          "sha1": "139485db4b0d73a784fc4b9d391f7e2afdd68bc3",
          "md5": "b01c076888adf6ece327d594e91907bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.19.2-2.1.12"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.8.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.8.jar",
          "size": 1699386,
          "sha512": "96cecf7b382d998aee696e565499c84361bb6421786a0913df61186663273d2e080e469127421deeaee35d430372c9348de185d2416ba8ecaa8f1edf36e54604",
          "sha256": "28eb54a8fe49b08af06095a8c5a7d6909d42538a857a957aeb1fe484f04f0f39",
          "sha1": "139485db4b0d73a784fc4b9d391f7e2afdd68bc3",
          "md5": "b01c076888adf6ece327d594e91907bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.8-sources.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.8-sources.jar",
          "size": 75383,
          "sha512": "bf49aa11015ab95df34bfc8037e14ddba74db8fd93ad8ba2eb4a346ddb38b59dcd336c6d2772e2c8daf0c1f6f6abfe9fdb782bd67751db53bcfbe8a8bb84b967",
          "sha256": "1ee03b164587282b5c30abd8b5f645d9fad38594cf4e58e765fc7e2fa1c5d6dc",
          "sha1": "8baf73a1e9ebd1188a415450402024f62dc66ada",
          "md5": "87c0b31334c20a3441b585af65ea37fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.8-javadoc.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.8-javadoc.jar",
          "size": 75314,
          "sha512": "f6fe079570e95b5cfe63a139ad56b0117f5bd6c53963bd724ce1904c258b460733851f5680d25ed8b78de0310135a4ae2e3e79c9e4f1c615d2f2a69822c0e9bd",
          "sha256": "b60a1adb45405a290b3610959ef2f181382c53595f6867cae4829cc23129056b",
          "sha1": "9ba2fbfbe7cc18c16b20b70b9777a66c955733bd",
          "md5": "574d0f9f58d16fa1914ea323261eb723"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.8-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.8-dev-shadow.jar",
          "size": 333919,
          "sha512": "4f282e5a492c4b35d1ababecf3f5d887c32a7ff80790f302be9e8a7f5ad13d6cdb07b308e27662050ca15e6ec1bbb858ba2608aacdf3777be84cd97ffcf0a426",
          "sha256": "615c59c1ef1b6056a4db92fd94102f755fdb6ddad968467dd4102f24f9e57aa0",
          "sha1": "693ce824aecc8accad7eaff7f5b36b9772ccf677",
          "md5": "be18088d2158b8ab4e7ba2c439faf4b9"
        }
      ]
    }
  ]
}
