{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-beta-3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.4.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.4.jar",
          "size": 1833890,
          "sha512": "782feb22953a1cf52f55e833dc10615124610b901c6a245d1993f924064c5d1e2cfdbdc690d0ed5b484095a2e01103b7d422d5788b20afc350e22ccc14dd4ab6",
          "sha256": "4497d7be6b3d5c4af4cb0972f757057b05067ce30fc5b9614af27342d41784ca",
          "sha1": "6026f7bbbd43c4851ff77d183142a9ef3c06caa0",
          "md5": "452a5e36696048edfae5373dfea3dd1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "curse.maven",
          "module": "time-control-303570",
          "version": {
            "requires": "5095704"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180900"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.4.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.4.jar",
          "size": 1833890,
          "sha512": "782feb22953a1cf52f55e833dc10615124610b901c6a245d1993f924064c5d1e2cfdbdc690d0ed5b484095a2e01103b7d422d5788b20afc350e22ccc14dd4ab6",
          "sha256": "4497d7be6b3d5c4af4cb0972f757057b05067ce30fc5b9614af27342d41784ca",
          "sha1": "6026f7bbbd43c4851ff77d183142a9ef3c06caa0",
          "md5": "452a5e36696048edfae5373dfea3dd1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.4-sources.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.4-sources.jar",
          "size": 780666,
          "sha512": "179f817612c371dcefbfeda7ef881358641984b85a9ef350078fdb9735408fb0716b018f6b8f377d25276efc0394e80e3dfbc86d517d2a0c68908cde237a456b",
          "sha256": "7688bc1380941a4b538eec02c46245912caa467ff93639df7c572877eba3da04",
          "sha1": "d1fbe32f81bf8eeaf6cfb63e01a388a4ca408fd8",
          "md5": "cd0e27dfff331211489c5ed88147cff3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-beta-3.0.4-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-beta-3.0.4-javadoc.jar",
          "size": 148353,
          "sha512": "de29f53245bf2d93c91276240fe4c4634863ff247e9d155b38adb880125fdfb789e9cca44fc642d05c51827654c9a0449e84dd7f14de5ff56b380b0d270167e3",
          "sha256": "99072b8ec36eab943310511f79286d4dd99cad472b2b58960ab949ebe4ff2226",
          "sha1": "d7bf890bc3da6dcbaf982833c3eaa774f391e1fd",
          "md5": "881d046915f5f8269980e53eb395ca5c"
        }
      ]
    }
  ]
}
