{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-neoforge",
    "version": "1.20.4-beta-0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-neoforge-1.20.4-beta-0.2.0.jar",
          "url": "dragnsounds-neoforge-1.20.4-beta-0.2.0.jar",
          "size": 1843077,
          "sha512": "8808e40f03c47e5ddf2448b9b9510c146aefca586a893061d2a22491a6b9292bbef91f881b39eb86ac02d2e29461e5ddd9adac674c1929d70bb17328b4114edc",
          "sha256": "ed35d9e00024d5016e3eac49bb1e1270b4f9fea5b1879f9c96dd321b57fb8e53",
          "sha1": "bd46a6be3269c225a39016a47010c0f358094793",
          "md5": "d0adaf5bf29f10f479a11460efbd395b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-neoforge",
          "version": {
            "requires": "20.4.3"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-neoforge",
          "version": {
            "requires": "1.20.4-2.2.24"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-neoforge-1.20.4-beta-0.2.0.jar",
          "url": "dragnsounds-neoforge-1.20.4-beta-0.2.0.jar",
          "size": 1843077,
          "sha512": "8808e40f03c47e5ddf2448b9b9510c146aefca586a893061d2a22491a6b9292bbef91f881b39eb86ac02d2e29461e5ddd9adac674c1929d70bb17328b4114edc",
          "sha256": "ed35d9e00024d5016e3eac49bb1e1270b4f9fea5b1879f9c96dd321b57fb8e53",
          "sha1": "bd46a6be3269c225a39016a47010c0f358094793",
          "md5": "d0adaf5bf29f10f479a11460efbd395b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-neoforge-1.20.4-beta-0.2.0-sources.jar",
          "url": "dragnsounds-neoforge-1.20.4-beta-0.2.0-sources.jar",
          "size": 200599,
          "sha512": "cf223995b9dd243ecfa08f2c71c63e5efbd989a57b447adc4451825e09b883811c9972b60300f47588e02d1a3a2bf28f4d630f23f3e0a0d4df1a3dc3b7d9b1f6",
          "sha256": "3e13c1206373a75797baa6c38f62cc4a13d4c4b9fe546cb09c92ae1e0bef0dc2",
          "sha1": "62b508a43bf6b286fbaaf2689ca9a767c23aa043",
          "md5": "717abdf03350b240883bc9570c876e85"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-neoforge-1.20.4-beta-0.2.0-javadoc.jar",
          "url": "dragnsounds-neoforge-1.20.4-beta-0.2.0-javadoc.jar",
          "size": 86150,
          "sha512": "536b67553a52d2f84b50c419d20373e4cb4d6d405c2c8b76eeceada8176c05486d7d020ace57fcb861151b579c2a831f458628e06620ab24d8935ad51d6b5ee4",
          "sha256": "4d919d2fe7d84359fe02f8ca7365b7a0d05a7cb9ea5e2e825e40436dd4e64caa",
          "sha1": "471fc5562023eee53de2607c74ad2c84429ebd15",
          "md5": "9c66cae82a13b8ae972da531912e6df3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-neoforge-1.20.4-beta-0.2.0-dev-shadow.jar",
          "url": "dragnsounds-neoforge-1.20.4-beta-0.2.0-dev-shadow.jar",
          "size": 488876,
          "sha512": "05d7709269b4e30deeb6c17ae06c521f60c7d42128ebae7e7c0518a38a5da829d4a60cd161ceb49b3cb96abbffe1821a4e2d5010ea52e2d3a97ce72317d0f7c5",
          "sha256": "bfb8974265ad7f9a39bee2c1d8c72dc8b154c0ef3546e62f2843c0f82282a118",
          "sha1": "5c82ace71dd7d5b9f9b857484e35a994d3e1d7c5",
          "md5": "8bffd51f0ca26db1b8bf75d7cf2192d1"
        }
      ]
    }
  ]
}
