{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-forge",
    "version": "1.18.2-0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.5.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.5.jar",
          "size": 1620840,
          "sha512": "19f92d9f44c9fb3483496249d0e9a6c51f72c9d68e2844773893902e2718354971872e6e0300cf4f89fad76a70de1b0f1e1974761c2a23aa6fd10906ae166696",
          "sha256": "fe99e2f902a9900ca35b46a7687a2cb775ac1d90ae1793e6c62f34d84d212d61",
          "sha1": "2e40cccf08a29edea4633ccaca78fc4f2fcd5c14",
          "md5": "83155cbf8ed02e6afb0b105837f45148"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.18.2-2.1.11"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.5.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.5.jar",
          "size": 1620840,
          "sha512": "19f92d9f44c9fb3483496249d0e9a6c51f72c9d68e2844773893902e2718354971872e6e0300cf4f89fad76a70de1b0f1e1974761c2a23aa6fd10906ae166696",
          "sha256": "fe99e2f902a9900ca35b46a7687a2cb775ac1d90ae1793e6c62f34d84d212d61",
          "sha1": "2e40cccf08a29edea4633ccaca78fc4f2fcd5c14",
          "md5": "83155cbf8ed02e6afb0b105837f45148"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.5-sources.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.5-sources.jar",
          "size": 330934,
          "sha512": "09a238173603c30a0db676cf324abc5c0161ce0ee0f4d81868533e7b9b003a8ef0b1f19f1ab91a79099b67fc28a03aefc39cbf30db0d461882da44c439e5272b",
          "sha256": "3088ba6a9e1244be0fe19326a22aa59f399abfff5bd1774586fb85420eabd6e9",
          "sha1": "98c8c44778824a6c862689ca5b2070e6865fe8df",
          "md5": "93b6ba759c8c786e4bdf2c792a462981"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.5-javadoc.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.5-javadoc.jar",
          "size": 74694,
          "sha512": "1efb88d2e1a8ca8976887f8b2c65b85087c81dff2b6a7f4041cbd51b915ce790e76ccea8f74ae5113a89393528d506a9c995d259377c0bbdb452967a1cc57a49",
          "sha256": "8e895116ab76f6601a0762bad84dbe97635406cff973762de8fde4d2e5d1886b",
          "sha1": "9980a6f5d420a4d41ee61343f28296a4f5a79964",
          "md5": "c80111244816a2cbc855f36c454078ca"
        }
      ]
    }
  ]
}
