{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.19.2-2.2.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.22.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.22.jar",
          "size": 1466203,
          "sha512": "a6b5d99b9a3018fc5a3bdb5c6bf2e686042896b6eb26bc832bee888e41cd9dc8022c70362d67cb4cb76834d92f8814128b98accac632b1191de68958d40142ac",
          "sha256": "eb5464d0b6a1bc85083c017699129529d159716417edaa82afe0844bc485ec37",
          "sha1": "14d1680528f73d27427a95e8a03fec5cff7ce038",
          "md5": "a1797b089a4daed8fb3e05ab5e7e1a38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.5.85"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.22.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.22.jar",
          "size": 1466203,
          "sha512": "a6b5d99b9a3018fc5a3bdb5c6bf2e686042896b6eb26bc832bee888e41cd9dc8022c70362d67cb4cb76834d92f8814128b98accac632b1191de68958d40142ac",
          "sha256": "eb5464d0b6a1bc85083c017699129529d159716417edaa82afe0844bc485ec37",
          "sha1": "14d1680528f73d27427a95e8a03fec5cff7ce038",
          "md5": "a1797b089a4daed8fb3e05ab5e7e1a38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.22-sources.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.22-sources.jar",
          "size": 352449,
          "sha512": "6182ec2353f145eb5d74a9daac24fa99c4feb787a5829d774d3df140208f91b3ecae6f48cd83f2261115a6ecfdfadce1db570d10c0b02ffbaf0cb81ccecee6c2",
          "sha256": "bd81448987ef85ac926d51947300b84d24878aa50fa54750fcfcb5fbe57e4fbc",
          "sha1": "b2ec948ee8cb510ea8ad593d20b2f186473fe793",
          "md5": "9a9e1bd7ff391daa02b4433db90eb7d1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.22-javadoc.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.22-javadoc.jar",
          "size": 74407,
          "sha512": "6f802f43ec7b53b86ed0ddd7a51c80062b05ebd828a93d6c3d31fd4a4a2f6aa6622808ced7110abd925ad2e861507ba5d0ea0c3cd0e5a3c1d5b1579e83878673",
          "sha256": "7bec0cb5beffdd29c4075e04675f898f63d4fc644acca694c2fa4021fddd954f",
          "sha1": "7e13495ba7f515312991a446bfd0b7c8f374a4af",
          "md5": "4da417b38d06241c83ecfb5a44e84501"
        }
      ]
    }
  ]
}
