{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.18.2-2.2.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.21.jar",
          "url": "dragonlib-forge-1.18.2-2.2.21.jar",
          "size": 1263337,
          "sha512": "59689cb9abef6e2124335516df626b3dd516446e9640d4cc783ae336f86b8b4960555f7da1e0ed3a0ea2726c3f2db5c449a098e3c69a010769ba5b18ce1c40c1",
          "sha256": "f97807f03e963da7f6e164e129bdc895fb72cb50d81896e515c3e3f9389bb43c",
          "sha1": "03bd8574bb88d04130db2e47e9b24b966e3449cd",
          "md5": "cd9a06f5d1e6539ce7e88d06c76a73e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "4.11.93"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.21.jar",
          "url": "dragonlib-forge-1.18.2-2.2.21.jar",
          "size": 1263337,
          "sha512": "59689cb9abef6e2124335516df626b3dd516446e9640d4cc783ae336f86b8b4960555f7da1e0ed3a0ea2726c3f2db5c449a098e3c69a010769ba5b18ce1c40c1",
          "sha256": "f97807f03e963da7f6e164e129bdc895fb72cb50d81896e515c3e3f9389bb43c",
          "sha1": "03bd8574bb88d04130db2e47e9b24b966e3449cd",
          "md5": "cd9a06f5d1e6539ce7e88d06c76a73e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.21-sources.jar",
          "url": "dragonlib-forge-1.18.2-2.2.21-sources.jar",
          "size": 573112,
          "sha512": "59d7bf3174723e4aef3a4ed53dc414a309aedf374e76f71b3c475d5907e04ea941bad2864e05d8ef109f63518caf47d3f28e1805c6c29f209272a72a094f178f",
          "sha256": "f12d4c3c7f4e11082db12c8b260a463fc29cd2d79f22f5e288de56c3137ad723",
          "sha1": "b8750ee8cf660b34905a6ea79805c40a106849cf",
          "md5": "a172da01a8bf5b37a98522312e05dcce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.21-javadoc.jar",
          "url": "dragonlib-forge-1.18.2-2.2.21-javadoc.jar",
          "size": 73792,
          "sha512": "974e4510e66b0269e0c3d5a6e478245a381d57645f1cf08f10fb47403581baa8cd31eda467aab7db09ead4b1fbe5cee335469c5a74c0e553149012c8d2406374",
          "sha256": "c6b95143eff8ab6438bb7abb173c4720826d3037f244f6b8e82f8af2a368cdd2",
          "sha1": "f2b7e259179d9e6e2d8c088eafd56157fb809a09",
          "md5": "e1ab6a3a8ae7ae54e2174199a2664cf6"
        }
      ]
    }
  ]
}
