{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-2.2.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.20.jar",
          "url": "dragonlib-forge-1.20.1-2.2.20.jar",
          "size": 1279738,
          "sha512": "41cbe78710047d2ef659c1123b8e05894f60e947d8543fdcbb0f5c63533038f56149218f4c876a23c7d32585452ed8b3768db93163cb9c94cbbe460fe97cdc21",
          "sha256": "980f49c5f668e3fc7479795531493b9b4d2559eadca7622eac71ec69e439caa4",
          "sha1": "7002ee8e2da62fda6f0e3f5e75fc5dfe2d7d878c",
          "md5": "0da570a337ed46faede66b82a9533dcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.20.jar",
          "url": "dragonlib-forge-1.20.1-2.2.20.jar",
          "size": 1279738,
          "sha512": "41cbe78710047d2ef659c1123b8e05894f60e947d8543fdcbb0f5c63533038f56149218f4c876a23c7d32585452ed8b3768db93163cb9c94cbbe460fe97cdc21",
          "sha256": "980f49c5f668e3fc7479795531493b9b4d2559eadca7622eac71ec69e439caa4",
          "sha1": "7002ee8e2da62fda6f0e3f5e75fc5dfe2d7d878c",
          "md5": "0da570a337ed46faede66b82a9533dcc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.20-sources.jar",
          "url": "dragonlib-forge-1.20.1-2.2.20-sources.jar",
          "size": 573401,
          "sha512": "79d9d17bb068ba5b41f7b4bdb4ff41e16f9213e0b1c5a7d876527b633afff186c76c6285eb8a497eea36d835f74746dc31d5d8b8b367d9f393fee93bdcdcbd3a",
          "sha256": "c52932b3d40c05e1f963130d36b8f81ced1c9568145700a9f6c17420f558d4d4",
          "sha1": "8099b10c90ef3bd866c39f59b73c2cdb8998fbde",
          "md5": "ef5bbde75a6a4f876f217d3469840c39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.2.20-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-2.2.20-javadoc.jar",
          "size": 86081,
          "sha512": "d2311630cadd75e24cb59dbcbe1d72c82b7b2add148c0cea9421ed1018f58be374d9cf33fb31be6d37a7adc288337e3673cbe88f3e9c1d9fce365df3b1fd273b",
          "sha256": "56a990831eba954270865458718bc12ab03de91b407da9328ec7fb7fc43c6071",
          "sha1": "3f913f03a66623afd118b8dfc146129f7b248449",
          "md5": "1aaa161b4ceb45421fbccc61f3eb4af9"
        }
      ]
    }
  ]
}
