{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.19.2-2.2.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.20.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.20.jar",
          "size": 1461454,
          "sha512": "e8a3acfd5b83d2f5cb3a9698be92986bd3708d3e49f19299be71c5b3085ffba681fb6ef2231f6b014920b8a66567b0fb934a2b4bf46e7e2ad25aa56d2a5dac90",
          "sha256": "1a2c99d2eab1caad12324f66d57e83f2990010e2958007d79beace825ab3d1e0",
          "sha1": "c5fd736eb67cf69ff4d8fe787f5064d11c820994",
          "md5": "dd029a955065d3eb6aca65dbf2dfa3c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.5.85"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.20.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.20.jar",
          "size": 1461454,
          "sha512": "e8a3acfd5b83d2f5cb3a9698be92986bd3708d3e49f19299be71c5b3085ffba681fb6ef2231f6b014920b8a66567b0fb934a2b4bf46e7e2ad25aa56d2a5dac90",
          "sha256": "1a2c99d2eab1caad12324f66d57e83f2990010e2958007d79beace825ab3d1e0",
          "sha1": "c5fd736eb67cf69ff4d8fe787f5064d11c820994",
          "md5": "dd029a955065d3eb6aca65dbf2dfa3c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.20-sources.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.20-sources.jar",
          "size": 349967,
          "sha512": "f6a6acf59090f9131a460a33bcfe44b314ab20e027871ed86e2a60b77ae6ce25be4800bebe81d706eab60ef79394c06c7932f0664056b2a79e5236e6b404f8c8",
          "sha256": "26e282dd76121b351dc2b0bbefc0f1dae7c13f71e3b7320997654945c4718e92",
          "sha1": "31ae010475f767b981ec24f0fb8766a630176de5",
          "md5": "b23d74a2800288cc6ce6d519235f1be1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.20-javadoc.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.20-javadoc.jar",
          "size": 86643,
          "sha512": "82cefc39bbc8a842e515e0e25b01158eb3d5381f7733e5916b79890992f20ca183780f5c01c92466dd41e83eae93fd17d5d2315660b76d6dabd1cd74a68a40ba",
          "sha256": "0a15885f074ddd333daf57719f2bfa941d6da837c58a67d040b08c7513de38e7",
          "sha1": "2ad6e02d3d3974d9a4359fd0e11fcc9dde1b2930",
          "md5": "8037920134f640603cbbb1ba2e13259c"
        }
      ]
    }
  ]
}
