{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.18.2-0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.6.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.6.jar",
          "size": 1611480,
          "sha512": "00fa16550b544c1a7ece0039d13b141b0c07d1326a89e0edebd7ad0c2d24895768e89199acfa19eef4b989a0199bb4e42412ad1b5d5529e86dde51ef9bdb0382",
          "sha256": "abe974dbcafd4d1b633976fa9743c1c1fd4d6e92dee1ced74a7845a79f518efe",
          "sha1": "e966eae387162ebb0b8e12e561abd71c968acd1b",
          "md5": "7b66f52c8244039647e91908b691a7dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.18.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.18.2-2.1.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.6.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.6.jar",
          "size": 1611480,
          "sha512": "00fa16550b544c1a7ece0039d13b141b0c07d1326a89e0edebd7ad0c2d24895768e89199acfa19eef4b989a0199bb4e42412ad1b5d5529e86dde51ef9bdb0382",
          "sha256": "abe974dbcafd4d1b633976fa9743c1c1fd4d6e92dee1ced74a7845a79f518efe",
          "sha1": "e966eae387162ebb0b8e12e561abd71c968acd1b",
          "md5": "7b66f52c8244039647e91908b691a7dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.6-sources.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.6-sources.jar",
          "size": 75384,
          "sha512": "8e4b2c3e30bd342fadef881a43f767771e0f7bf1e685dd1bfaf0e917a26d195a784be3e81575b1947d11afe45164c8f146e0bbc3c9e757c41898d0a1df6a8cb2",
          "sha256": "3ab40e0ddbd57bd0080218f9dade153c75237483541cf83344b265a4a5435463",
          "sha1": "44c930b6fa3f691e82bb084ad7d2731fda539017",
          "md5": "f44b1ea684b0d60555ff8f2c8345af81"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.6-javadoc.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.6-javadoc.jar",
          "size": 75315,
          "sha512": "5a8d901188f88dfed156932729302a094648714fb9a826aa1fa2b1206b150362d1883f52ed7304c7c275d00bc0d2504982a5628e73be31a04ef84acafcd89542",
          "sha256": "11e362391410dde1c836b5d2d230c2199a4c228c066b70238861778abc57b7cc",
          "sha1": "e4da24d844275091c9512eb682b943336b6bdc42",
          "md5": "9a17dc38bc00d77ad55241fa794e3110"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.18.2-0.1.6-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.18.2-0.1.6-dev-shadow.jar",
          "size": 331655,
          "sha512": "a99ec61aea6e0a61cd942add619ac12db496ba798c11ba9aa5d23ab48ef0e4c6b1726bddab811bee405aa201f9d244b63018c6d62cce4046122ed4103415a257",
          "sha256": "b245d2b81c40b914556f545e44743b2a2399ff5e09360a0f97d90d229526bff3",
          "sha1": "17e33372b688cf1d8d15e93fb475d6df5fcb0faa",
          "md5": "b4b84c42e457f0cab72d168fd087dc47"
        }
      ]
    }
  ]
}
