{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.19.2-0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.7.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.7.jar",
          "size": 1698597,
          "sha512": "8d3e036b8ebd0b07cabebbe73ce3be8038ccc290f2fb30576166d360ebd581769313a049fa8878a0bc4e7a75518088ef54146b1e24484d4a16391039ebd09dc2",
          "sha256": "40bde7ea7c93810505039354424dfb6064a8a6fac13b67e81001b302a8174464",
          "sha1": "31699615915f538047cd3a7d3e8eeb6f9d544845",
          "md5": "17c7de5c7768c8b8da0eb8c6ff6eec6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.19.2-2.1.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.7.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.7.jar",
          "size": 1698597,
          "sha512": "8d3e036b8ebd0b07cabebbe73ce3be8038ccc290f2fb30576166d360ebd581769313a049fa8878a0bc4e7a75518088ef54146b1e24484d4a16391039ebd09dc2",
          "sha256": "40bde7ea7c93810505039354424dfb6064a8a6fac13b67e81001b302a8174464",
          "sha1": "31699615915f538047cd3a7d3e8eeb6f9d544845",
          "md5": "17c7de5c7768c8b8da0eb8c6ff6eec6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.7-sources.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.7-sources.jar",
          "size": 75383,
          "sha512": "27051815b157f55785f519a494cfa75bd56d6ac22fad5eeb9feafcb72d69b1766c8cfcec11263ab04aa17d4add52fe63c78d612baf9c080d0da345939ddbc9b2",
          "sha256": "de7ba21d61c69fcf137fcd6a7de0e6bd51208588a0a32e3ae494e8431ffc72d6",
          "sha1": "8ce5fab92fa2691d2ebfe804e6fbd7b397325d5c",
          "md5": "7e35ebeadfa7c35d6b38593edd971766"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.7-javadoc.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.7-javadoc.jar",
          "size": 75315,
          "sha512": "080d48ac10ba07b83bc0a4991593b3fb6295e42f2eb17d4787034edfbc63ebd42fe3e8e17e24162155052cb587f4b0cf6224bc4efa8d0fb4b81aff286d534b48",
          "sha256": "d235534f17ebe341692149b2cbcbe9a4df7b2977476fcdeb87c1779801be5b93",
          "sha1": "799dfd92d12b85446a31d1e26fa74d9d996cb5c5",
          "md5": "38302026e4668aee5e3c574439cd936b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.19.2-0.1.7-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.19.2-0.1.7-dev-shadow.jar",
          "size": 333594,
          "sha512": "a8deec871e6b5c97410f7e47dea0e3824eb37bcf554f75937e32067dba4414e466142fb487da5947f15e18583ac753aa11f57794de230c6723ed1c9d539a2c2e",
          "sha256": "34e2fd0a37ea922bd10ef4593187988439f6b1c6e265fdfdfd6b4b8764207f39",
          "sha1": "dbc31bfcb4a3a1f51a4cbd4362d4626607903d5d",
          "md5": "c7a8ce8dfa29201716e9027cd63d9adc"
        }
      ]
    }
  ]
}
