{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-forge",
    "version": "1.18.2-beta-0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-beta-0.2.0.jar",
          "url": "dragnsounds-forge-1.18.2-beta-0.2.0.jar",
          "size": 1726171,
          "sha512": "6609351dec69dcb455b3ae83acdeaa0f179b6f6e51bd4814988318014c2c8d8b91685eaec00a3dd4c568557c85f59ebc10a95e8c0ddb69e745220053c1c2aa7f",
          "sha256": "15e8cbc5c1538cbd4b051c9de6f889c48db9e5cf4da049a2ace7934df8459b65",
          "sha1": "68cea94b04e56c9910325d91be53dbe7855be4ef",
          "md5": "e9ee207b4f316b7bf21eebfcf680351c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.18.2-2.2.24"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-beta-0.2.0.jar",
          "url": "dragnsounds-forge-1.18.2-beta-0.2.0.jar",
          "size": 1726171,
          "sha512": "6609351dec69dcb455b3ae83acdeaa0f179b6f6e51bd4814988318014c2c8d8b91685eaec00a3dd4c568557c85f59ebc10a95e8c0ddb69e745220053c1c2aa7f",
          "sha256": "15e8cbc5c1538cbd4b051c9de6f889c48db9e5cf4da049a2ace7934df8459b65",
          "sha1": "68cea94b04e56c9910325d91be53dbe7855be4ef",
          "md5": "e9ee207b4f316b7bf21eebfcf680351c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-beta-0.2.0-sources.jar",
          "url": "dragnsounds-forge-1.18.2-beta-0.2.0-sources.jar",
          "size": 343284,
          "sha512": "51ff278db413fa7c51b0852f4d91e1c1d0fb2bc5bd0a862a17d995ab10db1d4329ddacc9d04aee371d97ead01f0071dbe016121c72dd01216bd60811d5423fdf",
          "sha256": "e0bde5b0df8a43b9554ad40936b9e284fec08170d782d5eadf4e538cbf73a128",
          "sha1": "5d0eb180eff256e3882843064a2e3bd035a8806d",
          "md5": "d0e796f899478027ccb924d49d87ae60"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-beta-0.2.0-javadoc.jar",
          "url": "dragnsounds-forge-1.18.2-beta-0.2.0-javadoc.jar",
          "size": 86088,
          "sha512": "ad71b43b962c78ef59998daa290d123b49ba76feba9b17173ff04cef404d52df8553c18f46724d807b42798f13f76a85bb770c15ffd898ef5efc13e8741d747b",
          "sha256": "6a441f37fc3e5e17226d4390a45238ee135298c9f54e047047c751e1aa62be3f",
          "sha1": "1c74bda8e73a6be6dafb9254f1ee1e3ad3b6dc03",
          "md5": "6f4be4ff2ea26e9274fcd364a2fb4ec6"
        }
      ]
    }
  ]
}
