{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.13.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.13.jar",
          "size": 2106048,
          "sha512": "511eb2b2e3439988684dd839f4066971025337f733b45310ca5e5c7cc6d463789122e8d3d82e925ac1e09817b10601ee10b7b4afd8170ce493bfe339921acf1b",
          "sha256": "d7e0012c02b6de40b98715c15f81d02873f0df91574389cdfea6a2f5a07fb28f",
          "sha1": "c33e3538185f2d6d2469c8941b9d766077d08c06",
          "md5": "1215149c6896a9a0772731db937e130d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.13.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.13.jar",
          "size": 2106048,
          "sha512": "511eb2b2e3439988684dd839f4066971025337f733b45310ca5e5c7cc6d463789122e8d3d82e925ac1e09817b10601ee10b7b4afd8170ce493bfe339921acf1b",
          "sha256": "d7e0012c02b6de40b98715c15f81d02873f0df91574389cdfea6a2f5a07fb28f",
          "sha1": "c33e3538185f2d6d2469c8941b9d766077d08c06",
          "md5": "1215149c6896a9a0772731db937e130d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.13-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.13-sources.jar",
          "size": 629596,
          "sha512": "96ee3dd455fee62a3d57ef51d47ca0a3669b0cc2ffd75840eac4ae489bf9cf614c404fbfe4b361de41c764e1dcaae859ec3bdf79d3477ab14511b42bf835f397",
          "sha256": "2c7b284ec46b2166e573614fcd59cdd51ea1807f43c7a143e07f6284c0435f9c",
          "sha1": "d980456dcc895b2f3de83564e29957fb7d26fd46",
          "md5": "ed73a1b67256bd126dd1a2a4d7e6fb80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.13-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.13-javadoc.jar",
          "size": 262160,
          "sha512": "4871bbcebab56bf7ba18bec51e4e269ea0caab397987d36c449b6ee42b0932839aa468740fb219abb4c43bcd40c01e3378d2a088d2826d06130349d912eab172",
          "sha256": "87a36088196fa76f628cbf0bf7e70bbb1f850e03ae0a600b02498e6ac834d586",
          "sha1": "3cb2867aba0bcdc5b0a6e6aa9fda3c88518b00f2",
          "md5": "50ce852a5d09510c706d99742e4c75c3"
        }
      ]
    }
  ]
}
