{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.19.2-2.2.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.24.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.24.jar",
          "size": 1468443,
          "sha512": "ddf9931eab7f661a63ee37e3c825ff9d80dd5753670b22e63c703c37a039cd937e93503eecfe0d11b4f2540875dae95d50f2c50de26094b35799395926eea0fe",
          "sha256": "2e27b52e3bf7802e43fba696d3df6f1bb332be17f741cf7ff8adb9b4e0f379ba",
          "sha1": "bdf7be8c2307c5a67e6c6d03a7445ba74135a59f",
          "md5": "2c68d33cbf31d3ac8904b6bd7f6d9082"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.5.85"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.24.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.24.jar",
          "size": 1468443,
          "sha512": "ddf9931eab7f661a63ee37e3c825ff9d80dd5753670b22e63c703c37a039cd937e93503eecfe0d11b4f2540875dae95d50f2c50de26094b35799395926eea0fe",
          "sha256": "2e27b52e3bf7802e43fba696d3df6f1bb332be17f741cf7ff8adb9b4e0f379ba",
          "sha1": "bdf7be8c2307c5a67e6c6d03a7445ba74135a59f",
          "md5": "2c68d33cbf31d3ac8904b6bd7f6d9082"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.24-sources.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.24-sources.jar",
          "size": 354169,
          "sha512": "3687faa93a9d04f1fa5c6797a962e86b119408fc68c7798d2398e270d516d3403cd7615e80ecbdfcf4fdddfaad815eb25cef89d2697e291a6ada640d2293fe64",
          "sha256": "b87cde9ecedf7759cd224e2d87d55025fb3b6629252d88e704b875b4472d5a1f",
          "sha1": "73a48b59defaff52fd6d01f270e78cee8dc5bf68",
          "md5": "3b2dafc9c553efad00a46251a002435b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.24-javadoc.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.24-javadoc.jar",
          "size": 86644,
          "sha512": "b8a366a25c4452a631efd74c5af386a50fa2bc8d62e25d25cc7e044bc16ee448b83a78b1ba5ea77f2bfb674d963ec7990a2a618c81a4f0267c0b349934a2b90a",
          "sha256": "e54e95e18c37bb1381d8d7de1957a6c72d92aab6c46b1df4a4f35321733e9a47",
          "sha1": "3ebe3f950b560804217b2477bb9ba7f8d81336ce",
          "md5": "1b0e957021eb8d46f0c83d56a7003e11"
        }
      ]
    }
  ]
}
