{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.20.1-2.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.1.14.jar",
          "url": "dragonlib-forge-1.20.1-2.1.14.jar",
          "size": 1202441,
          "sha512": "ab5e01a45305affa67aa0c8c88c09578e2984ea3c8fd05d2eb07bfbc09c0a25483e92a0dfcdd7e41bd8c1df9b831769a3e9da39a86f2879f7cc2d96615cb16cd",
          "sha256": "3d08bd035c19361e8424c0c6a5e51bcf7259f402012498e15f7d3dc6fc0bc981",
          "sha1": "9814ca500c66bef5f413ffb92cd5be1be2e6177f",
          "md5": "ede5102276cf463f84bc3ad6a715abc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.1.14.jar",
          "url": "dragonlib-forge-1.20.1-2.1.14.jar",
          "size": 1202441,
          "sha512": "ab5e01a45305affa67aa0c8c88c09578e2984ea3c8fd05d2eb07bfbc09c0a25483e92a0dfcdd7e41bd8c1df9b831769a3e9da39a86f2879f7cc2d96615cb16cd",
          "sha256": "3d08bd035c19361e8424c0c6a5e51bcf7259f402012498e15f7d3dc6fc0bc981",
          "sha1": "9814ca500c66bef5f413ffb92cd5be1be2e6177f",
          "md5": "ede5102276cf463f84bc3ad6a715abc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.1.14-sources.jar",
          "url": "dragonlib-forge-1.20.1-2.1.14-sources.jar",
          "size": 539427,
          "sha512": "2e847ebdf95d29d192d303d412e780289407a9ec5cf16ef5103859027c4ab8b4e3a2c48c3103817e6512f0fe71a2d5d72334b051a7f0cd23321fe9414dc0e294",
          "sha256": "49b65a4defcee40d8a68a14a3a1413922e745eec9de170c3ee09dc980261c2f2",
          "sha1": "e813706e1806494c44065d7a1f358675ba739a82",
          "md5": "bac262ebdb8f5e289308f618e96258e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.20.1-2.1.14-javadoc.jar",
          "url": "dragonlib-forge-1.20.1-2.1.14-javadoc.jar",
          "size": 74936,
          "sha512": "d4538333217a5624f8240f1c4e7136905952683a57df5581ece04f911599fccea1e23fb07278d4cf786c33700bb8103c2a500c2a82430579c8b08bb8ca578225",
          "sha256": "fe7908b0d4e79c58305c53cc332aa01ae867a945634517ecad65935ea2fcb727",
          "sha1": "7c0b5679caa9265828e5ba06f2a04514bbb5b7ca",
          "md5": "523d5cf7147b5a28b82ff95f7dbfcb7a"
        }
      ]
    }
  ]
}
