{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-neoforge",
    "version": "1.21.1-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19.jar",
          "size": 1372645,
          "sha512": "ec1f785608b83aa397f859d8352e06bc62c3cc43328584656518d653f80cf097aae09afec67f1bca8e119000dac68f9517061b9634168e4c0af88540cb41281c",
          "sha256": "6f72dcb7aa3a0d16768ca1b9a8d811f36bd8e53dcdab757bba1de011973f5144",
          "sha1": "84420d12f3dda77e9f46cedb79d34c0784f30bf1",
          "md5": "deecaf4a643c04dcefb139a1fd0ebfcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.6"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-neoforge",
          "version": {
            "requires": "21.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19.jar",
          "size": 1372645,
          "sha512": "ec1f785608b83aa397f859d8352e06bc62c3cc43328584656518d653f80cf097aae09afec67f1bca8e119000dac68f9517061b9634168e4c0af88540cb41281c",
          "sha256": "6f72dcb7aa3a0d16768ca1b9a8d811f36bd8e53dcdab757bba1de011973f5144",
          "sha1": "84420d12f3dda77e9f46cedb79d34c0784f30bf1",
          "md5": "deecaf4a643c04dcefb139a1fd0ebfcc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19-sources.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19-sources.jar",
          "size": 297759,
          "sha512": "4cb2fff0a8a2fabf0affac95003cccff29c3af58314904c2f2a21ee7e9b3b1afe93914b316a410b588bb8edb7c95e009b35609e974d8cb82da1025192d8872c1",
          "sha256": "b1755bf3bd51dec521886f4a442891196f47bc99ec2afeaecfa55e093236544f",
          "sha1": "559c52cd2295f6c377889b8e999919b426e4fad0",
          "md5": "e9d3c1b07192a6dca6d3f323d97a7cba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19-javadoc.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19-javadoc.jar",
          "size": 86653,
          "sha512": "d2260c44f342726d4815248bad859b2ca0004245fe86d490ed29bded94a654fcf780d5213f15b2c6f381a353ad1c85b18a7df01951561108b7ca1d366722f138",
          "sha256": "160e4b23e24c8d0db61b851f7e2b1698aeef91d82c1cc22df024866704219afa",
          "sha1": "b9a5c09e36ba6a2fb2b156a9b861f7a6f258690e",
          "md5": "ae252b9cd375c23645a945fc020e07f6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19-dev-shadow.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19-dev-shadow.jar",
          "size": 752341,
          "sha512": "df2dd90487f1cfa141650840e675f4ba7dcf309b0657dd703139ed34aec57da34b0d13a36f4e4852a5966ae6748f7942c7eb027c0816624713a221d84a70034b",
          "sha256": "4a5e6f91af6ada6ef425e9246bb752d26db9ca961c8a34beccc6251963b26541",
          "sha1": "be9ab2e3db7d0c77f153dadc84481ac22b78d949",
          "md5": "38acb45335db7705b4447853bbe71d19"
        }
      ]
    }
  ]
}
