{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-neoforge",
    "version": "1.21.1-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19.jar",
          "size": 1370634,
          "sha512": "2779f848050a769fb711aacc9145aee441ccfd8bfebcea22b9ab506c5cccb43af630bdcc99cd5c753d3dcf25149a8507a1ecb5cf1c335ee66bb3e01ed6771b05",
          "sha256": "0eb8493abaf16d34b9428ccb2629cb952fb239071662dd4307737a04b71fcfce",
          "sha1": "46a492b4482114421844a3377a1a4ce97cc9460d",
          "md5": "84b06e80110534ba8a5def1fe3717793"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.6"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-neoforge",
          "version": {
            "requires": "21.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19.jar",
          "size": 1370634,
          "sha512": "2779f848050a769fb711aacc9145aee441ccfd8bfebcea22b9ab506c5cccb43af630bdcc99cd5c753d3dcf25149a8507a1ecb5cf1c335ee66bb3e01ed6771b05",
          "sha256": "0eb8493abaf16d34b9428ccb2629cb952fb239071662dd4307737a04b71fcfce",
          "sha1": "46a492b4482114421844a3377a1a4ce97cc9460d",
          "md5": "84b06e80110534ba8a5def1fe3717793"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19-sources.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19-sources.jar",
          "size": 297759,
          "sha512": "79d28beb3529d0ad604e2ba5dc6c2b21d57fb6d0441044ee7fe4bda3471cf57a082efd1f8043f8e4514724882764047ec461b654ed7c4268b407e5013c6e98fe",
          "sha256": "2124f9dbabeb6a4d770a0621e8c8a23bcbaac354b9ad3f2df20e1bdca3bd278f",
          "sha1": "26835ea2e65045e5147e34a811ca6fdd9e2a4536",
          "md5": "3aa9598798caef366c2750524e399007"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19-javadoc.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19-javadoc.jar",
          "size": 86653,
          "sha512": "d2260c44f342726d4815248bad859b2ca0004245fe86d490ed29bded94a654fcf780d5213f15b2c6f381a353ad1c85b18a7df01951561108b7ca1d366722f138",
          "sha256": "160e4b23e24c8d0db61b851f7e2b1698aeef91d82c1cc22df024866704219afa",
          "sha1": "b9a5c09e36ba6a2fb2b156a9b861f7a6f258690e",
          "md5": "ae252b9cd375c23645a945fc020e07f6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-neoforge-1.21.1-2.2.19-dev-shadow.jar",
          "url": "dragonlib-neoforge-1.21.1-2.2.19-dev-shadow.jar",
          "size": 750328,
          "sha512": "921da784710b49dc614db5158fc5bf256ceabd93b28b78f134289c0d1aab1090152580b6f0248376495fe06798c982d5bfa7aeda8b7cdedb306bdce9afe93633",
          "sha256": "9d5ddd41e46c078ff2cb206a57e884f2a165f3e539cda9ed1277339ad68a3ff7",
          "sha1": "b1e351f4a43ba9f911699c3936bfdc8e6e61b961",
          "md5": "9e9ef83fead06916eb986074eec726b3"
        }
      ]
    }
  ]
}
