{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.19.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19.jar",
          "size": 1247793,
          "sha512": "8d07f22e12f5e78553c59309d97cb88cb9d2039c0c84cb21f053b7c339c1e7eaaf77f58800d90232d70d4544fdbb20666f2b13f8c31c6572b5b92ad9e48ddfaf",
          "sha256": "2e673bbb344906a3a9b1fd9b51941c3c18ed83529699f223011b8ea7e3c4906b",
          "sha1": "0dd6a68e7ebd31c55651b5a30b58eef115a2b654",
          "md5": "1da1c5b03818fbb4376bd34209771093"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "6.5.85"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19.jar",
          "size": 1247793,
          "sha512": "8d07f22e12f5e78553c59309d97cb88cb9d2039c0c84cb21f053b7c339c1e7eaaf77f58800d90232d70d4544fdbb20666f2b13f8c31c6572b5b92ad9e48ddfaf",
          "sha256": "2e673bbb344906a3a9b1fd9b51941c3c18ed83529699f223011b8ea7e3c4906b",
          "sha1": "0dd6a68e7ebd31c55651b5a30b58eef115a2b654",
          "md5": "1da1c5b03818fbb4376bd34209771093"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19-sources.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19-sources.jar",
          "size": 567052,
          "sha512": "dcf7adc6dc8f76b7ed98ad6539d8ac97b8dec7ba3cbde00cf0310ffc27d44d68325cdc418d025d0c2c4f02698d7d06892c909ce522fd17a6c4caa277f693fdca",
          "sha256": "0a263aff4043f0ea1bb827ee7cf4acbc4c351bf48601ed86b42416c9aa1f538c",
          "sha1": "138595e5bc28753fecc961e7012075539773d227",
          "md5": "b38f96e90691fca3f531ff057dc0254c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19-javadoc.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19-javadoc.jar",
          "size": 74764,
          "sha512": "e33e5f6fb274d12e5cd5dc56238bed44984c9a37611ddee390f96aee5843fb384f39557d6e3983793eb8e7fea35e420a5769c2b54c39f34aa3edf21d8f964a5c",
          "sha256": "70d8eb0e933d1475906deab40611f07b3b05792bd7eca866982a58ae93fea954",
          "sha1": "3929e833417316245350de5afb886d43e413ee83",
          "md5": "9ccb2cb6b6e37a810c85c7d472503d67"
        }
      ]
    }
  ]
}
