{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.19.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19.jar",
          "size": 1246065,
          "sha512": "50e0d5b1fafdfea52ba9a1bb20d0f6ab6b207367f0916a38186ab6f839ef7154509d7e3559d6a0cf344076ed7a171026da2931d5aab8ea479199e54dbb5874ee",
          "sha256": "3f45814ed40026c27d1a51ba2417e4c55a9d93eeae4ea1ba96721f4858ee3626",
          "sha1": "4491cf872c34e9db962c350c72171f993a3312d1",
          "md5": "5c3e37c457e524d552999b041bbc276f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "6.5.85"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19.jar",
          "size": 1246065,
          "sha512": "50e0d5b1fafdfea52ba9a1bb20d0f6ab6b207367f0916a38186ab6f839ef7154509d7e3559d6a0cf344076ed7a171026da2931d5aab8ea479199e54dbb5874ee",
          "sha256": "3f45814ed40026c27d1a51ba2417e4c55a9d93eeae4ea1ba96721f4858ee3626",
          "sha1": "4491cf872c34e9db962c350c72171f993a3312d1",
          "md5": "5c3e37c457e524d552999b041bbc276f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19-sources.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19-sources.jar",
          "size": 566953,
          "sha512": "9539becbb1077bcb5a0360d9c8c92b73940fddc3fdbbabf476a217d23d14cb0aed4bf6af976fbba04749cd5d34cabdf2531d40ece5d3138b2192fcf0a48b5fbd",
          "sha256": "789f0e39ceb58109115ef45c9705b9c6c3fefe3ff50783fd32a101cf37668f67",
          "sha1": "1fe57b29bf6c2bf17acdcb42041e1f9289262c2c",
          "md5": "764a59454af21059a44d1a16c9107fb4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19-javadoc.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19-javadoc.jar",
          "size": 86073,
          "sha512": "030bf05e7e3e1c28b4d20bac4831cd70ff285970140e5e049180c5898016ba5b71f2b992ac17eefdcadfa00c6692da384811f9ec024f1b30dc95e75ab8235c2a",
          "sha256": "979af8a7eaa17849c62f10d244144d84c21bf7aba8f038e9a80ea244dbe23ac4",
          "sha1": "3c7f808e23cd5ffcea2ffa79bba7d59b298d7ab0",
          "md5": "b1963451ed78a71d4c6e580d285f2ffa"
        }
      ]
    }
  ]
}
