{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.19.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19.jar",
          "size": 1235042,
          "sha512": "5dbf0d87353acd01d5472701cbabc70f4c3d72f76b22b977798dece4acb81df0edc79a64d32a7470a4587293e511b1c2c138a60fd0ed40dfbe81a131041d6939",
          "sha256": "37d476625509355d038807052b9ee71870546705f29687f9cc1c4c05f7fc21db",
          "sha1": "dab8a53260b432112ff03eb060cdb4bb555072c7",
          "md5": "eed30e0811cf514f6b81524409875991"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "6.5.85"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19.jar",
          "size": 1235042,
          "sha512": "5dbf0d87353acd01d5472701cbabc70f4c3d72f76b22b977798dece4acb81df0edc79a64d32a7470a4587293e511b1c2c138a60fd0ed40dfbe81a131041d6939",
          "sha256": "37d476625509355d038807052b9ee71870546705f29687f9cc1c4c05f7fc21db",
          "sha1": "dab8a53260b432112ff03eb060cdb4bb555072c7",
          "md5": "eed30e0811cf514f6b81524409875991"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19-sources.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19-sources.jar",
          "size": 561523,
          "sha512": "b1d9ebb9b41e61a761fea4b448d29757947fbd5b8765cc368efa29e373bb78c9a508df5de7aa7e01b3140ba21e25e84f2b7b3f8b834e241470ac395a0b025419",
          "sha256": "0a9f1425286a8d45003d611c6291f8c981984360d0a3f5b7ae0b763d5984d247",
          "sha1": "0c94f9c53aeb19c1e7ce0e2d509b33b922dc674f",
          "md5": "6df5f52e85e24fd01158465948617c1e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.19.2-2.2.19-javadoc.jar",
          "url": "dragonlib-forge-1.19.2-2.2.19-javadoc.jar",
          "size": 86073,
          "sha512": "030bf05e7e3e1c28b4d20bac4831cd70ff285970140e5e049180c5898016ba5b71f2b992ac17eefdcadfa00c6692da384811f9ec024f1b30dc95e75ab8235c2a",
          "sha256": "979af8a7eaa17849c62f10d244144d84c21bf7aba8f038e9a80ea244dbe23ac4",
          "sha1": "3c7f808e23cd5ffcea2ffa79bba7d59b298d7ab0",
          "md5": "b1963451ed78a71d4c6e580d285f2ffa"
        }
      ]
    }
  ]
}
