{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.18.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.19.jar",
          "url": "dragonlib-forge-1.18.2-2.2.19.jar",
          "size": 1250900,
          "sha512": "a616b6ad5759874c5c29f35a6ed4bd57968a1609403becaedd7af49fbf526fa2ae511ad51d44b7debeb9816f37cdf5b4a6d231e9d953badd6c911d0d20f6f00b",
          "sha256": "03df4fe6469dbe53a11f9dfdc9053c5aed0135eb216956a27fdaef900b6421ff",
          "sha1": "208faaf7dd7f89bb0031ae8391760fd490129eaa",
          "md5": "08ecdc2b5128e94977bb223ab9be810b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "4.12.94"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.19.jar",
          "url": "dragonlib-forge-1.18.2-2.2.19.jar",
          "size": 1250900,
          "sha512": "a616b6ad5759874c5c29f35a6ed4bd57968a1609403becaedd7af49fbf526fa2ae511ad51d44b7debeb9816f37cdf5b4a6d231e9d953badd6c911d0d20f6f00b",
          "sha256": "03df4fe6469dbe53a11f9dfdc9053c5aed0135eb216956a27fdaef900b6421ff",
          "sha1": "208faaf7dd7f89bb0031ae8391760fd490129eaa",
          "md5": "08ecdc2b5128e94977bb223ab9be810b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.19-sources.jar",
          "url": "dragonlib-forge-1.18.2-2.2.19-sources.jar",
          "size": 566829,
          "sha512": "a0af79be9d17ae66e5ccfc6d6c802fcfe4c33caef01f9473036af0985cf9c831c6b5a71e75e402526cfc1d3f9de4b6e3f84c4106bf0a8ccc182b40deead76ffe",
          "sha256": "6e160687f4d70083d2aa1351e7e22084f310b62cfebc89c000105163b37b5de3",
          "sha1": "49fc4c3ab3efa317f5ea214a5a4e028f3c1ba1f5",
          "md5": "90272a143ebeee790ee41c6bd1380ffc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.19-javadoc.jar",
          "url": "dragonlib-forge-1.18.2-2.2.19-javadoc.jar",
          "size": 86093,
          "sha512": "6766849e94c69a5966374046482510d79468a84b3ff2af3ff40169e07356a80fa80c55b9c5170ec64b4fd405b9143be7be0f24abdc6e237a44c79a85cbbd8a97",
          "sha256": "a0a4fa160fbfff4ee8b37282c4ad4a52a3588b7510d63c88bdb9d0604b8cc508",
          "sha1": "dbe19517c8327cf1c177d3102390d23e9262d963",
          "md5": "a575a6108c7b5c571030e8ea3594dff7"
        }
      ]
    }
  ]
}
