{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-forge",
    "version": "1.18.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.19.jar",
          "url": "dragonlib-forge-1.18.2-2.2.19.jar",
          "size": 1252573,
          "sha512": "051acd6774c5a1dc6312a600c93155a121d13c226faba4afcb7321eefa9ab2b82f0e86888f6db4c579c258d1f896dbde17ed004a033ea4e82debfbcb70d573c4",
          "sha256": "3124d4867651410e50af280fbd7a8cf7d1e347ce8be9abdb0b4c5245cf5b5b6c",
          "sha1": "8c791881753b7ce6547ae06f9719b0e1f8456573",
          "md5": "9e490a589055ff06e95e5ceb96a9e35a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "4.12.94"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.19.jar",
          "url": "dragonlib-forge-1.18.2-2.2.19.jar",
          "size": 1252573,
          "sha512": "051acd6774c5a1dc6312a600c93155a121d13c226faba4afcb7321eefa9ab2b82f0e86888f6db4c579c258d1f896dbde17ed004a033ea4e82debfbcb70d573c4",
          "sha256": "3124d4867651410e50af280fbd7a8cf7d1e347ce8be9abdb0b4c5245cf5b5b6c",
          "sha1": "8c791881753b7ce6547ae06f9719b0e1f8456573",
          "md5": "9e490a589055ff06e95e5ceb96a9e35a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.19-sources.jar",
          "url": "dragonlib-forge-1.18.2-2.2.19-sources.jar",
          "size": 566885,
          "sha512": "8cc2dfba4b75c306bff7edb6d839ffb02624dbbbc5bc198f942ad66a2db430af2819f55c0ffd1492995d34b008f7f97729584ff7f857306a2eaae506081ec3db",
          "sha256": "1f57a3c59d60c01a8426e0a808c2b31de2f3478fff1cd6dbd901734ae437ef5b",
          "sha1": "38f389acce463fff3caa9b67509c6ad5303c339b",
          "md5": "2f1f98ebfa4268b3d22a1fc79789c37c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-forge-1.18.2-2.2.19-javadoc.jar",
          "url": "dragonlib-forge-1.18.2-2.2.19-javadoc.jar",
          "size": 74781,
          "sha512": "7f8bf773ad90081384a04c3a9e2cd30bc4bfd1722b508e90d384135a4b523fbb8e5f074e55d4e436fc49a3e78688585eee88a29266b0bad18bc27e8c2eb6b481",
          "sha256": "5c0ffc39d96ca30c5f32c62ac4cfbf5894a7d5f2945dd6a35b1a28c22c770d5b",
          "sha1": "0f1a325a2f0a9133bb9c788526a2c49f80b46251",
          "md5": "12e11ea9e2b8aa4a486b0460db6ab394"
        }
      ]
    }
  ]
}
