{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.0-006",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.0-006.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.0-006.jar",
          "size": 1931805,
          "sha512": "51c3d0c1e628483d5040109f309421ad60771bd295fa6ef758c1648762f87b4dfb3f679d7a51a17f405766600ebaacd4b73f6e0184a86bbedc8f2131def4ed1f",
          "sha256": "82d77c943bc6fa941efe0023797232b2bf94b2a9c8d2c21980d5693429ddda00",
          "sha1": "08b43ce6fc02c6a05519d814cb64e4a86b0696b4",
          "md5": "5fe0501e7b5afb686cd189787a17bd3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.0-006.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.0-006.jar",
          "size": 1931805,
          "sha512": "51c3d0c1e628483d5040109f309421ad60771bd295fa6ef758c1648762f87b4dfb3f679d7a51a17f405766600ebaacd4b73f6e0184a86bbedc8f2131def4ed1f",
          "sha256": "82d77c943bc6fa941efe0023797232b2bf94b2a9c8d2c21980d5693429ddda00",
          "sha1": "08b43ce6fc02c6a05519d814cb64e4a86b0696b4",
          "md5": "5fe0501e7b5afb686cd189787a17bd3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.0-006-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.0-006-sources.jar",
          "size": 571836,
          "sha512": "ea52e01d3b7873d8b29013a22545b8606d1892701a6a6877072fbaf6575c02b1dbbc6324c042bd10249985219b0baa99972bd5ddca5c23266734cdfe8b342a18",
          "sha256": "dc4eacbefff9f8010a9a7e74938440883526d94842749ed1ea4b61a6bda8be69",
          "sha1": "e47588e3097bcb6d36705ba520e4821e4f5115e8",
          "md5": "4eb227caaa1cdd14c3b93be69468079c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.0-006-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.0-006-javadoc.jar",
          "size": 105170,
          "sha512": "383dd07f15a308504c052d5d8942fa1522152e302a39859cda827ed1541be9e1bfcd6a5163e2ac1c95b1a7e1d3af7d45d4212f76b00c516cd354927103ca5294",
          "sha256": "6669c5701aad3b9f15f41d4f788cef0056c31ec3412ff7d133485961616e912d",
          "sha1": "901e326df73fd9bace32e064e13852020ad52185",
          "md5": "76a57260b2bab0c97f3d9557ef4ddb53"
        }
      ]
    }
  ]
}
