{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-forge",
    "version": "1.18.2-0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.7.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.7.jar",
          "size": 1620989,
          "sha512": "9fd563310185e6a2f3dbc77a5724c605d5aaf631461aa002570f4c217d3ea7f160bd5e4ad82dae2eaf939873094e721722aa3869f5378d6bff80cd839ec208e2",
          "sha256": "88c6353974044fd9172b0135e92382be1ef50ab4b9587c2c389c07b8578d224c",
          "sha1": "5f9779e595e71a8d22aa27f643cde60d3ceb54dc",
          "md5": "b14db44601b8af4b294844078913ab1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.18.2-2.1.11"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "3.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.7.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.7.jar",
          "size": 1620989,
          "sha512": "9fd563310185e6a2f3dbc77a5724c605d5aaf631461aa002570f4c217d3ea7f160bd5e4ad82dae2eaf939873094e721722aa3869f5378d6bff80cd839ec208e2",
          "sha256": "88c6353974044fd9172b0135e92382be1ef50ab4b9587c2c389c07b8578d224c",
          "sha1": "5f9779e595e71a8d22aa27f643cde60d3ceb54dc",
          "md5": "b14db44601b8af4b294844078913ab1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.7-sources.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.7-sources.jar",
          "size": 331040,
          "sha512": "a409a39ed5faa6c47b6e8d8618206ae2c6de71ca7e1e6904b0b05d04590cdc413d9919376b9d6f27fec3bcf56a552c65f0e5b19eca6c8a29e55604c6c2de9f26",
          "sha256": "57c15f50acab6d49fdd47b5d33bdcdc366634354aca6e8d0dd66e819569709bc",
          "sha1": "9486eb00e2bc04da61cf82cd38c1e13732b67009",
          "md5": "8156da054f4c9fd22bd6c5fb993d0f20"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.18.2-0.1.7-javadoc.jar",
          "url": "dragnsounds-forge-1.18.2-0.1.7-javadoc.jar",
          "size": 74691,
          "sha512": "8e4c7293669b888506459c3d353216ebcc53262bccbb64fda1ffb58b80fe45fb5646d8e47ee32d160fed071e7156c202fdf116d62ec625b6e2384e053f3fd803",
          "sha256": "a288194634ea660dd1c30a4104bbb228b317f69113edc17d337cfa02c5a1d6e3",
          "sha1": "9644cd54fc0194d1cae0d1b63f5561b2dc354d88",
          "md5": "a5e5c7c94a69b5f7ad41ffa59cf26af3"
        }
      ]
    }
  ]
}
