{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.19.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.19.jar",
          "size": 1452823,
          "sha512": "dadf38964720fe0de71b8430c71c4de2967777052458f678e200c4c406f67fa5680cceb09a228f08fdfd322ae95c1124a98c856e9717627d748445f1034b3201",
          "sha256": "16b731e1943e069c3480b40db634cf7d7fc8c295e9cd645919d91448468f82a0",
          "sha1": "0a1a321131a4f57f36b7f2e78cd70fc874fefbbf",
          "md5": "9d538982610bd3c2b6743f50a7f29b1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.5.85"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.19.jar",
          "size": 1452823,
          "sha512": "dadf38964720fe0de71b8430c71c4de2967777052458f678e200c4c406f67fa5680cceb09a228f08fdfd322ae95c1124a98c856e9717627d748445f1034b3201",
          "sha256": "16b731e1943e069c3480b40db634cf7d7fc8c295e9cd645919d91448468f82a0",
          "sha1": "0a1a321131a4f57f36b7f2e78cd70fc874fefbbf",
          "md5": "9d538982610bd3c2b6743f50a7f29b1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.19-sources.jar",
          "size": 346554,
          "sha512": "71f26d9c5b6342046b60b78634ecb1c976bece0262f5e324699bbeac5c8de8b575893c2d6145019a9d35d3874a95594ea0318a472e57d0d7db60f887e4308914",
          "sha256": "21c4b293f9077bb321ae206466b55304c1b69a372514c33a1155ae5d93258369",
          "sha1": "1848ef1304d0fa6bca88c2515159ac01b0ad1582",
          "md5": "bbe4d02e29708f4e4ee3affb1e100bcd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.19-javadoc.jar",
          "size": 86633,
          "sha512": "7dbded8b5455c5fd36abd6300d9da3707c139d7dce03c7638252e76940b4647aab91a2915875bd51e59d72622ca0067bea52d48c7c551707d18fc8693768cd2e",
          "sha256": "606a5b0649c7ecc95ca1021dd3b821059f93dd494702374ee6826452873c65ed",
          "sha1": "dcbd33ecdca0b542a7b0c2cd5f4d0874c88e1125",
          "md5": "9e3b38089e3a66b9977e317543247b19"
        }
      ]
    }
  ]
}
