{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.19.2-2.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.19.jar",
          "size": 1454549,
          "sha512": "0a937de829666e10330b31c51e0fe68ed14991238b6c4f4a574890ad6e4d725650a2dc3d2a3dda4b8ffeaff11f852c95a373801c492c9e565caa75215b2c4521",
          "sha256": "bb7b2455bcc338c2a2462e30f2e6e1ff0e5403e185fee90ccf1285aae713b203",
          "sha1": "cda2a0a778a5ef87dd0b8dda34b1e2d329b3ab6b",
          "md5": "dcdfe604284069ce4e78f0b9ab210970"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.5.85"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.19.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.19.jar",
          "size": 1454549,
          "sha512": "0a937de829666e10330b31c51e0fe68ed14991238b6c4f4a574890ad6e4d725650a2dc3d2a3dda4b8ffeaff11f852c95a373801c492c9e565caa75215b2c4521",
          "sha256": "bb7b2455bcc338c2a2462e30f2e6e1ff0e5403e185fee90ccf1285aae713b203",
          "sha1": "cda2a0a778a5ef87dd0b8dda34b1e2d329b3ab6b",
          "md5": "dcdfe604284069ce4e78f0b9ab210970"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.19-sources.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.19-sources.jar",
          "size": 346650,
          "sha512": "d6b699b67f5bcbcc459d47fa0ce8979403ed9cebd92c18e604a5fd365a902782a202f5ff5ebeeaa9579d25a93fdd8dfc4abd375a68a69ccd6a7734b8f5f9a703",
          "sha256": "4489b7622ed68f8e1b6f54b69f86fb4fd06ad0954ea90421bb138acc61f7be17",
          "sha1": "13ebdcf9a1107ee154342dac04e856c5df34fdc7",
          "md5": "45569ed448c301d3a81e8159df9fdd59"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.2.19-javadoc.jar",
          "url": "dragonlib-fabric-1.19.2-2.2.19-javadoc.jar",
          "size": 75381,
          "sha512": "d0da1199930c24af14886063a02d0af46b3e2dec8a11ec82df41211f9c1d64c1002032aaabd40c804a59d174e2ad65c6e4dd34024d065fee0a02b8a16abfbf16",
          "sha256": "6abb10a9fd2d791a3b33e6429a8e23a5581c1114d5421a075e5b9708e963b4bd",
          "sha1": "1357481a86179573f1b9b544a06f602ceda112ea",
          "md5": "c21af50e24280e7d92adf019b756b8b9"
        }
      ]
    }
  ]
}
