{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-2.2.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.24.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.24.jar",
          "size": 1419257,
          "sha512": "f35fd970a8781b95c87a0eb186c4ec3fcd90a3e8da5587a9307178aba4d313b4a1878cd29fd78d626a189c808ba94f8b7b1db3a119267a7b9ede4001cadabebf",
          "sha256": "3dcdd306701cf34ac063b51b6f3b676433838d0811fd51d9ea3419ba0232d4a6",
          "sha1": "a73bd87ddf7e53a9b35f54915e896b681586b16c",
          "md5": "9491b2ea686d16be620e353f8d5e9c26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.24.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.24.jar",
          "size": 1419257,
          "sha512": "f35fd970a8781b95c87a0eb186c4ec3fcd90a3e8da5587a9307178aba4d313b4a1878cd29fd78d626a189c808ba94f8b7b1db3a119267a7b9ede4001cadabebf",
          "sha256": "3dcdd306701cf34ac063b51b6f3b676433838d0811fd51d9ea3419ba0232d4a6",
          "sha1": "a73bd87ddf7e53a9b35f54915e896b681586b16c",
          "md5": "9491b2ea686d16be620e353f8d5e9c26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.24-sources.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.24-sources.jar",
          "size": 356587,
          "sha512": "990da3074da28a9163a3481f4f81644ad5fd4c94daca723685647ae8558c9084c82d590c99f7f5f5765e3af49b1b0dd8c2e914607ea1902f73208b14fe65da36",
          "sha256": "9e4ea80faf9b405e56ff841d4a7ad812a3aa2259787433ef78735877e6911053",
          "sha1": "e8d7a2168f004ce626e0bbde9408dbd44bead6fb",
          "md5": "6f496b940f7f98eb1f2896f94e32a288"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.24-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.24-javadoc.jar",
          "size": 86643,
          "sha512": "d670216d62a6a288dc14ac2158c69b2f454e67414aafeffaba3e63835018975bf6bd5acc78a79d79685d87b7a8192cbf2508fedd0a6b480e804536eb6400e0a6",
          "sha256": "8be9f3c5d33039e028fd48ecc65d797f086d400860bf768153be4951fb30d976",
          "sha1": "c6556665c078c15185b77c03fe1232e073cca39e",
          "md5": "15d80204db5e7c75948bc2f85700021f"
        }
      ]
    }
  ]
}
