{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.20.1-0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.8.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.8.jar",
          "size": 1650937,
          "sha512": "c96514db43b42ccce3b6e02291185cf0c8723a3b36725eae23c5be64fffb5ee0fdfb4182da3bc28d7a045d5762e1b65837b09d0850f93dd5effa119f8af5883c",
          "sha256": "baadba66cdf2e3c1cb6726d59ffe5b21a8a73a1ff5e1ce79596bc86d454a3197",
          "sha1": "89a2851cb1b1929239c24e260fc104311cc4b402",
          "md5": "1217163f773628f8ff398f5a9c1fc666"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.20.1-2.1.12"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.8.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.8.jar",
          "size": 1650937,
          "sha512": "c96514db43b42ccce3b6e02291185cf0c8723a3b36725eae23c5be64fffb5ee0fdfb4182da3bc28d7a045d5762e1b65837b09d0850f93dd5effa119f8af5883c",
          "sha256": "baadba66cdf2e3c1cb6726d59ffe5b21a8a73a1ff5e1ce79596bc86d454a3197",
          "sha1": "89a2851cb1b1929239c24e260fc104311cc4b402",
          "md5": "1217163f773628f8ff398f5a9c1fc666"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.8-sources.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.8-sources.jar",
          "size": 75400,
          "sha512": "6b3e570711250d6e58960fd4e46b992f5408dd636872bcdee5ef79155a5fd75b44273b09f6d56348b4d97934ffcac01d4da6011fb3aeffc6be9bed6ae5de4fa2",
          "sha256": "bcd3f356b2f1b88ec80fab10e97f31cd7d852628bd198e407bc3d77a4312cc8d",
          "sha1": "1e2453607c1f47e3b8148b00856e7c0781fd411b",
          "md5": "87aa6c2609e8d568c924113376383514"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.8-javadoc.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.8-javadoc.jar",
          "size": 75314,
          "sha512": "b27b94f18578ef66d411fa8aaa563105969657232502a54ca8ce258f9641d2040a53c56551619b95e895a6b40d6e18622f14a78a3ad9c4761a3789ed821912e6",
          "sha256": "80833ec9e6dfcdb9d96675fefa4b1e97100508c7342aa247970b52acbd992b6e",
          "sha1": "0ca88cc6380a49fa4b563c494078443bcf3520de",
          "md5": "7511de99fa4546e3890153de25975bac"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-0.1.8-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.20.1-0.1.8-dev-shadow.jar",
          "size": 334569,
          "sha512": "9e6ce5105aab348fb68b8a589e92b2ee3e62ca9a39acdf5e6f278f9f1852da1fd08bb0452156c2026e1dfe570837b7d28a89a02ea9f36f3a46aa57bb82e37adc",
          "sha256": "80360e84afbe1c73d2fc3d74a409baa135d353a728ac0d0c0ae4084730176315",
          "sha1": "4ff65651ae1f387ce6e0219b99584db6c4dcc35f",
          "md5": "933486f19504c98017e9b126d99af60c"
        }
      ]
    }
  ]
}
