{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.5.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.5.jar",
          "size": 2038326,
          "sha512": "62e6875e4b7c6d02d2202f0e4499b3fa36761c6c69377b97f82167bac1b00530a7cfedd58441b3a7b39d39fea28d9844aa6a7d306de8d50cda4afc987dd9e1dc",
          "sha256": "4df4813f5187ea178220a3c1d2120ee4e232a475b478ab565058f40bd231145f",
          "sha1": "3501b1c6d53bd30b70cdcb09792749f06d7fdf35",
          "md5": "b1e9f74c2d1ca43f6b93d007381912d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.5.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.5.jar",
          "size": 2038326,
          "sha512": "62e6875e4b7c6d02d2202f0e4499b3fa36761c6c69377b97f82167bac1b00530a7cfedd58441b3a7b39d39fea28d9844aa6a7d306de8d50cda4afc987dd9e1dc",
          "sha256": "4df4813f5187ea178220a3c1d2120ee4e232a475b478ab565058f40bd231145f",
          "sha1": "3501b1c6d53bd30b70cdcb09792749f06d7fdf35",
          "md5": "b1e9f74c2d1ca43f6b93d007381912d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.5-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.5-sources.jar",
          "size": 590235,
          "sha512": "95f60b1b368389d3f69147c3a3670c114c5530fb18c0d4ab80788a56f2c8dd42cd994b4c079791881a69d4f53a1c9d0bf5e9725d727e9f589059238f4ff67962",
          "sha256": "0e9fa2a94c92920ae3ea8027bc61ecaf1e6d1c761355d729ddf6894f12aec0f6",
          "sha1": "fd715158763cb033e7b43eb47147863d717cba40",
          "md5": "9af4e8e9014b4417f0acf6c6a405bc0f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.5-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.5-javadoc.jar",
          "size": 259567,
          "sha512": "33e19ff524477ae06429a05268ed01123a2cf5632b4341e1a606ea306ddfce2ec6274cadcc6adfcef3cfcb57dad2a833f151c1094faaef79e0f402816b8c4d0d",
          "sha256": "92d1555961e2495094572864f75f69b051f9ba5cabb2d014b0b835ed70e0388f",
          "sha1": "ad84c782349d6b546eaa0c1c331b52a2cd487dfe",
          "md5": "526beaadba42dec63e66dff5fca30d49"
        }
      ]
    }
  ]
}
