{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-forge",
    "version": "1.20.1-0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.20.1-0.1.7.jar",
          "url": "dragnsounds-forge-1.20.1-0.1.7.jar",
          "size": 1641523,
          "sha512": "48c033756601a062a0a66c5a5e9df4f924e9636bd865278d7d8792dc9cc6dce283dc1f0dc05af668c9bbf3a5abb3d3eac25d9dd322d0c6802f0767b8e421ae1b",
          "sha256": "806cf313eac63325034285feafd5f63015a80e9f504f35d88bfd89efd4747fef",
          "sha1": "8c0f54547b84004f100e137528b201d076d22665",
          "md5": "7fe01fd1f409afa3381c81554adeda22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.20.1-2.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-forge-1.20.1-0.1.7.jar",
          "url": "dragnsounds-forge-1.20.1-0.1.7.jar",
          "size": 1641523,
          "sha512": "48c033756601a062a0a66c5a5e9df4f924e9636bd865278d7d8792dc9cc6dce283dc1f0dc05af668c9bbf3a5abb3d3eac25d9dd322d0c6802f0767b8e421ae1b",
          "sha256": "806cf313eac63325034285feafd5f63015a80e9f504f35d88bfd89efd4747fef",
          "sha1": "8c0f54547b84004f100e137528b201d076d22665",
          "md5": "7fe01fd1f409afa3381c81554adeda22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.20.1-0.1.7-sources.jar",
          "url": "dragnsounds-forge-1.20.1-0.1.7-sources.jar",
          "size": 331944,
          "sha512": "cc3c00e02abd3d3174d8a73b803834fd1620196f2b21c2fd8d0023b0ba552ae01a39690c1bef0dfa9d05562678581f2d132b1d16783b53389e97380048783971",
          "sha256": "38edad3f180ed8b68c23cacfdf5049da9785793cff6c01bbf7cd7a569122e72b",
          "sha1": "82a963bcf071b51ffbbca3b44433a3f34a71097b",
          "md5": "9f36529a48508f20523e777402ba0097"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.20.1-0.1.7-javadoc.jar",
          "url": "dragnsounds-forge-1.20.1-0.1.7-javadoc.jar",
          "size": 74691,
          "sha512": "5dc70685ad8aadb56421c2fde11427967ee8425acb34be1670f2d81e6e8967d6603ef304efcacbe441e1da8ea123bd025c8e3acec75b5a65d00f3eff21fc8d3f",
          "sha256": "6a7fed3ea548b9fbee053dc30dc436d34b8d6b2917b6741b5b78d9419038b896",
          "sha1": "fba0e03d352f7591ccac1b74231da9ae430f05c0",
          "md5": "ea6c9b46b10235877ec7892101dc0f28"
        }
      ]
    }
  ]
}
