{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.19.2-2.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.1.12.jar",
          "url": "dragonlib-fabric-1.19.2-2.1.12.jar",
          "size": 1386078,
          "sha512": "fa4b68e6d26b58d64409bb44dbc57207829deadfecfced40806abcc5e11f8f10f1b5fc29377dff9ba02f46ece275cac50c3bfdda1808bafa4dd6798f6b69a5bd",
          "sha256": "61c4ba7420e6cf6668b200a6cf06a6187a4768c9b20e245ebee9f15a72c9ce7b",
          "sha1": "9567188038bfc83fd0ba12a40779b78017fcb66e",
          "md5": "b40e94b05f181c5582e66db8ff15ef16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.5.85"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.1.12.jar",
          "url": "dragonlib-fabric-1.19.2-2.1.12.jar",
          "size": 1386078,
          "sha512": "fa4b68e6d26b58d64409bb44dbc57207829deadfecfced40806abcc5e11f8f10f1b5fc29377dff9ba02f46ece275cac50c3bfdda1808bafa4dd6798f6b69a5bd",
          "sha256": "61c4ba7420e6cf6668b200a6cf06a6187a4768c9b20e245ebee9f15a72c9ce7b",
          "sha1": "9567188038bfc83fd0ba12a40779b78017fcb66e",
          "md5": "b40e94b05f181c5582e66db8ff15ef16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.1.12-sources.jar",
          "url": "dragonlib-fabric-1.19.2-2.1.12-sources.jar",
          "size": 316666,
          "sha512": "b3049628e30fa83e5416ca122a2c7e4efa10181e3de16db9a4692abc57d1451295ae30ae5c1bbc9234c66e43acff7161f833d847fa96b501518a0b0abb2ef6df",
          "sha256": "db2796750084b04fbe8d80ca3d217e0953daea693dbae959266e32de8c6fd8ae",
          "sha1": "f7c7510f9abf7c75753ecdee5b29b3cd14a9806b",
          "md5": "2742e32dd1ed003ebbadb2ef14a6f77c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.19.2-2.1.12-javadoc.jar",
          "url": "dragonlib-fabric-1.19.2-2.1.12-javadoc.jar",
          "size": 75459,
          "sha512": "b984d776910fa9001a4ce2410f6d21731525d9d99ce8fffd65ceef13f281736287f1dd7611de075cc0385d8c23482701ff7e79b9672d76f492840339a451c0d1",
          "sha256": "fdcb46b9b3d2624a9d092feab5437a3a8c8befdab37178a553c9992dbb116ff8",
          "sha1": "86e2da60ca92e27e9a508ecb071ed0d7d8c25880",
          "md5": "93763262d363d622644d3efc74c93e9a"
        }
      ]
    }
  ]
}
