{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-forge",
    "version": "1.19.2-0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.19.2-0.1.8.jar",
          "url": "dragnsounds-forge-1.19.2-0.1.8.jar",
          "size": 1618770,
          "sha512": "bdec021554fb12f76e49a0ab9f009a6bf7532d8a8903a7e435cf320d1c05762ff2dba71494bba62b7abfc8121e6df4c9431425871d0f0e3d54f310825c1886ad",
          "sha256": "9f3491e9820949bbceb4a85c1bd8c23a56a73fc8da93c19f8aebeaead2e543fc",
          "sha1": "6654f43b44efc3047e41b77d24d95cd60203063c",
          "md5": "1e35a5e7c928d36d9e2caef88363c61b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-forge",
          "version": {
            "requires": "1.19.2-2.1.12"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "4.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-forge-1.19.2-0.1.8.jar",
          "url": "dragnsounds-forge-1.19.2-0.1.8.jar",
          "size": 1618770,
          "sha512": "bdec021554fb12f76e49a0ab9f009a6bf7532d8a8903a7e435cf320d1c05762ff2dba71494bba62b7abfc8121e6df4c9431425871d0f0e3d54f310825c1886ad",
          "sha256": "9f3491e9820949bbceb4a85c1bd8c23a56a73fc8da93c19f8aebeaead2e543fc",
          "sha1": "6654f43b44efc3047e41b77d24d95cd60203063c",
          "md5": "1e35a5e7c928d36d9e2caef88363c61b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.19.2-0.1.8-sources.jar",
          "url": "dragnsounds-forge-1.19.2-0.1.8-sources.jar",
          "size": 332236,
          "sha512": "b63e2092aa8e341e7b7d8b794e372d625a92e4a1875b18fca9f7369859c5bd81300100ba5cf7731c48287b01da351f8d06057391b5b2d36d1494bee18cebb335",
          "sha256": "0f3e8ccaff0504cd425038d0a95e79e422b84213b4af1fe90c3d23ede5eaf7db",
          "sha1": "0248b98422409590aa6f8b20de502386d8b5fdf5",
          "md5": "810e50584d48f5acd17042f1fddd2c0e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-forge-1.19.2-0.1.8-javadoc.jar",
          "url": "dragnsounds-forge-1.19.2-0.1.8-javadoc.jar",
          "size": 74692,
          "sha512": "ada56eb7a50714ed684e2371514f766ff0f39dcf62d2683ef9a5b373dd6c093e91c3782c9a19f6432bb64ececcfd4cbedf7fa932ae3db9711f057055e5b73017",
          "sha256": "393eec1908b486f1a9ed40d46bab5854240d6202b7badd15e17a70773db40d52",
          "sha1": "66b4db572064746b92a8c1b03751b6ab6821d0ae",
          "md5": "4ff27fe52dd2d22f1037cdf87b14425c"
        }
      ]
    }
  ]
}
