{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.dragnsounds",
    "module": "dragnsounds-fabric",
    "version": "1.20.1-beta-0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-beta-0.2.1.jar",
          "url": "dragnsounds-fabric-1.20.1-beta-0.2.1.jar",
          "size": 1755062,
          "sha512": "6031160159232a0c888e4300e9f64d85e49fa354fbd326417ad9a17e76d64f6362c540cb0952564e1c1d3381a8394a8061cfd3c9bd8908b8380954fcf7d146ee",
          "sha256": "6c40f973f97367b5cc24e77eb7444c5bb56cddafc665f11dfa129444b53d804a",
          "sha1": "987a44ff96fb4f1f02cd7866da0f48afcfc4bc49",
          "md5": "a0a1519c86e6de5cf9922583ca245be4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "de.mrjulsen.mcdragonlib",
          "module": "dragonlib-fabric",
          "version": {
            "requires": "1.20.1-2.2.24"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-beta-0.2.1.jar",
          "url": "dragnsounds-fabric-1.20.1-beta-0.2.1.jar",
          "size": 1755062,
          "sha512": "6031160159232a0c888e4300e9f64d85e49fa354fbd326417ad9a17e76d64f6362c540cb0952564e1c1d3381a8394a8061cfd3c9bd8908b8380954fcf7d146ee",
          "sha256": "6c40f973f97367b5cc24e77eb7444c5bb56cddafc665f11dfa129444b53d804a",
          "sha1": "987a44ff96fb4f1f02cd7866da0f48afcfc4bc49",
          "md5": "a0a1519c86e6de5cf9922583ca245be4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-beta-0.2.1-sources.jar",
          "url": "dragnsounds-fabric-1.20.1-beta-0.2.1-sources.jar",
          "size": 75235,
          "sha512": "061581302bfdb9f157c84f82b471701e629c453b44e5f53605c697d46cd9ab659e2de935b6b6c10da7d69328ed94933fa122b6b5252f4df6ac1935fa88138e45",
          "sha256": "722e5d9dbbc7fead2b62a72d85f2cc4b0d355a2e3b188ef218ec644c60b05652",
          "sha1": "d29165474a8baedbda3dc462e4f0e627651b29b4",
          "md5": "4fee2a1649b614e5047f37453329849a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-beta-0.2.1-javadoc.jar",
          "url": "dragnsounds-fabric-1.20.1-beta-0.2.1-javadoc.jar",
          "size": 86652,
          "sha512": "7e8d11d9d7de03cdac0d41b5c3953808c913e938629d46b9322df8ae4b21f4f6dab9ee992ec7b2ce0da6c09e424421132a12568614e22c53ac07a96cf84d8617",
          "sha256": "f4e7ce2a4d14d9fd9c227230274406df01a41b8070f7a4470c16c166c81cef14",
          "sha1": "8918883047c782070010b1a6ebed123d149c4937",
          "md5": "f051f0dfef5f519e324dd1d80539eefc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragnsounds-fabric-1.20.1-beta-0.2.1-dev-shadow.jar",
          "url": "dragnsounds-fabric-1.20.1-beta-0.2.1-dev-shadow.jar",
          "size": 362067,
          "sha512": "6382d9e50aba32b5131d7fc2383305db95e29170b8d439b57f6d3b44a326329172564bacf1b64af59c74f924f2d27683a12a7c58ab1f039e7ff4025b14a8f1cc",
          "sha256": "ef69b34885c1a80eb922163e6716706d7b2726af85ee35e3fcdc62616ca6aba7",
          "sha1": "51da6b4077b4214e7d6ddc4ef55c394e54d7ca01",
          "md5": "328701189e6eb72820a07f6f4165983d"
        }
      ]
    }
  ]
}
