{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-2.2.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.16.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.16.jar",
          "size": 1388068,
          "sha512": "f371555e194de85b5eb850fe91b9a452a7cf66651c17477d285687665f30aa046869d231b6624540fe2aedf1ca83d6e186825eda6f88df89066ab75f94fb90de",
          "sha256": "1ff8accddee670a8405f004c7a985075e1dfe2579a81676ea5d0c07ce1c9f07f",
          "sha1": "c909cbabec7470388c6b377aa6b2c197505f3ca1",
          "md5": "0b4e4b83ae2905496b16f041097d56c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.16.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.16.jar",
          "size": 1388068,
          "sha512": "f371555e194de85b5eb850fe91b9a452a7cf66651c17477d285687665f30aa046869d231b6624540fe2aedf1ca83d6e186825eda6f88df89066ab75f94fb90de",
          "sha256": "1ff8accddee670a8405f004c7a985075e1dfe2579a81676ea5d0c07ce1c9f07f",
          "sha1": "c909cbabec7470388c6b377aa6b2c197505f3ca1",
          "md5": "0b4e4b83ae2905496b16f041097d56c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.16-sources.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.16-sources.jar",
          "size": 340436,
          "sha512": "80ae5416b851c60625f7c3b6511028330b7dcf478196338182e85802abc1a6270f77e563920c9f923082aa8076670ba3d0bcedd7b552e3a543238b67bc436ca3",
          "sha256": "b456a43cb95a011948329e8630f86c30f6c4811123feea3722a197ea7fc695b2",
          "sha1": "4ef1f34569e5b7c58fe16ddfd4b88fa9c32fb756",
          "md5": "b37e653f2369309f9bfafc91ba41768f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-2.2.16-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-2.2.16-javadoc.jar",
          "size": 75551,
          "sha512": "e3f13f008dc2ccffed8504f98d6f2f38fe3e705ea038f6d6a701415facf6b02bd41ac43d94eb57aa24b817461c32284875b5f16c5169a2c36de41beb375abb6d",
          "sha256": "da791757ca0fd305bc0f362fa36b54cca67565709d942b536faa6b094b5fb773",
          "sha1": "f4bbdefb639dad3d8fd6f68e20a76cf89a3e4787",
          "md5": "d564f9edfd451ed5e6bfbfd6eafcf7d1"
        }
      ]
    }
  ]
}
