{
  "formatVersion": "1.1",
  "component": {
    "group": "de.mrjulsen.mcdragonlib",
    "module": "dragonlib-fabric",
    "version": "1.20.1-beta-3.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.7.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.7.jar",
          "size": 2061560,
          "sha512": "07bf0a16a04405d6a49d4e5cdbfe022f319070c8e7ddcaa6f16572dae07341abe87dffa3bb72c891703db03441be34861f5cac79cf29c276d8c7ac81c328dd69",
          "sha256": "0c043826189193824d2e47c21a91a2b3b53c039514bb63391d29b34b5844ff56",
          "sha1": "59e357a4f297738d18b5c9e6b3dd1437f72c79a0",
          "md5": "461c02d84e77042ee44ac2b96e4ad656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.7.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.7.jar",
          "size": 2061560,
          "sha512": "07bf0a16a04405d6a49d4e5cdbfe022f319070c8e7ddcaa6f16572dae07341abe87dffa3bb72c891703db03441be34861f5cac79cf29c276d8c7ac81c328dd69",
          "sha256": "0c043826189193824d2e47c21a91a2b3b53c039514bb63391d29b34b5844ff56",
          "sha1": "59e357a4f297738d18b5c9e6b3dd1437f72c79a0",
          "md5": "461c02d84e77042ee44ac2b96e4ad656"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.7-sources.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.7-sources.jar",
          "size": 598660,
          "sha512": "bd5a45e37a8b01869c4064e2150d6084e9deafba33c74590e88ce2b32f4dfec342bc983bea62a67d1938ebbb61343d69a2314934f805347bf9caac747fb1d43a",
          "sha256": "88c2eb7879e1b41d6fc72b038010df25d3a6c98058494d1519432dda19cc7323",
          "sha1": "c8e15163365439ec17938a003d76a3b3dfc9dd31",
          "md5": "b9d69fa4656fa598bf01381fac475a9a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dragonlib-fabric-1.20.1-beta-3.0.7-javadoc.jar",
          "url": "dragonlib-fabric-1.20.1-beta-3.0.7-javadoc.jar",
          "size": 259421,
          "sha512": "c6df5da3183e266b0c9fe9426271d0264839fe2c1377a674a8f2f27438fd1d881a20f4f871b3ada12de3dd76acdba74fd2b21fbab2755c33b11cb26045c6f2ff",
          "sha256": "aceccf008b1d400e878b4ad46178374b1c79cc737cb526be13618b2e0b00515e",
          "sha1": "eb6db55a6943b8989d118d76c10d449c9b8334f1",
          "md5": "481d41c1344dad0cb92fd969bd5b59e0"
        }
      ]
    }
  ]
}
